act_code: '205376'
requisite: Решение Таразского городского маслихата Жамбылской области от 26 декабря 2024 года № 25-6. Зарегистрировано Департаментом юстиции Жамбылской области 31 декабря 2024 года № 5254-08
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по городу Тараз
  kaz: Тараз қаласы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '158002000002'
version_date:
  kaz: 2025-10-31
  rus: 2025-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/205376/kaz/31.10.2025
  rus: https://zan.gov.kz/client/#!/doc/205376/rus/31.10.2025
caused_by:
  code: '216893'
  requisite: Решение Таразского городского маслихата Жамбылской области от 31 октября 2025 года № 33-6
  title:
    rus: О внесении дополнения в решение Таразского городского маслихата от 26 декабря 2024 года № 25-6 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в городе Тараз»
    kaz: Тараз қаласында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» Тараз қалалық мәслихатының 2024 жылғы 26 желтоқсандағы № 25-6 шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216893/rus
