act_code: '144289'
requisite: Решение Байзакского районного маслихата Жамбылской области от 24 июня 2020 года № 67-11. Зарегистрировано Департаментом юстиции Жамбылской области 30 июня 2020 года № 4656
title:
  rus: Об определении специализированных мест для проведения собраний, митингов, демонстраций, шествий, пикетирований и правил их использования в Байзакском районе
  kaz: Байзақ ауданында жиналыстар, митингілер, демонстрациялар, шерулер мен пикеттерді өткізуге арналған арнайы орындарды белгілеу және оларды пайдалану тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '158003000002'
version_date:
  kaz: 2023-12-28
  rus: 2023-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/144289/kaz/28.12.2023
  rus: https://zan.gov.kz/client/#!/doc/144289/rus/28.12.2023
caused_by:
  code: '191778'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 28 декабря 2023 года № 17-5. Зарегистрировано Департаментом юстиции Жамбылской области от 5 января 2024 года № 5142
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата №67-11 от 24 июня 2020 года «Об определении специализированных мест для проведения собраний, митингов, демонстраций, шествий, пикетирований и правил их использования в Байзакском районе»
    kaz: «Байзақ ауданында жиналыстар, митингілер, демонстрациялар, шерулер мен пикеттерді өткізуге арналған арнайы орындарды белгілеу және оларды пайдалану тәртібі туралы» Байзақ аудандық мәслихатының 2020 жылғы 24 маусымдағы №67-11 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/191778/rus
