act_code: '87012'
requisite: Решение акима Актоганского сельского округа Меркенского района Жамбылской области от 29 января 2015 года № 1-03/05. Зарегистрировано Департаментом юстиции Жамбылской области 27 февраля 2015 года № 2540
title:
  rus: О присвоении  наименования новой улице
  kaz: Жаңа көшеге  атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-01-29
approved_by:
- '158008005001'
version_date:
  kaz: 2015-01-29
  rus: 2015-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/87012/kaz/29.01.2015
  rus: https://zan.gov.kz/client/#!/doc/87012/rus/29.01.2015
