act_code: '53596'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2010 жылғы 15 маусымдағы № 32-14 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 19 шілдеде 6-10-102 нөмірімен тіркелді
title:
  rus: Талас ауданы бойынша елді мекендер орналасқан жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенті бекіту туралы
  kaz: Талас ауданы бойынша елді мекендер орналасқан жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенті бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-15
approved_by:
- '158011000002'
version_date:
  kaz: 2010-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/53596/kaz/15.06.2010
