act_code: '76227'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 11 декабря 2013 года № 27-4. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2013 года № 2079. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 08.05.2019 № 42-3
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Жамбылскому району
  kaz: Жамбыл ауданы бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегiн көрсету Қағидаларын бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '158004000002'
version_date:
  kaz: 2013-12-11
  rus: 2013-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/76227/kaz/11.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76227/rus/11.12.2013
