act_code: '142179'
requisite: Решение Таласского районного маслихата Жамбылской области от 20 апреля 2020 года № 71-7. Зарегистрировано Департаментом юстиции Жамбылской области 22 апреля 2020 года № 4570
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и  ветеринарии, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының  мамандарына отын сатып  алу үшін көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-20
approved_by:
- '158011000002'
version_date:
  kaz: 2021-04-16
  rus: 2021-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/142179/kaz/16.04.2021
  rus: https://zan.gov.kz/client/#!/doc/142179/rus/16.04.2021
caused_by:
  code: '155097'
  requisite: Решение Таласского районного маслихата Жамбылской области от 16 апреля 2021 года № 5-3. Зарегистрировано Департаментом юстиции Жамбылской области 23 апреля 2021 года № 4949
  title:
    rus: О внесении изменений в решение Таласского районного маслихата от 20 апреля 2020 года № 71-7 «О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии проживающим и работающим в сельских населенных пунктах»
    kaz: «Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін көмек беру туралы» Талас аудандық мәслихатының 20 сәуір 2020 жылғы № 71-7 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155097/rus
