act_code: '21788'
requisite: Жамбыл облыстық мәслихатының 2004 жылғы 27 тамыздағы № 5-5 шешімі. Жамбыл облыстық әділет Департаментінде 2004 жылғы 28 қазанда 1475 нөмірімен тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облысы Әділет департаментінің 2007 жылғы 24 сәуірдегі № 4-1874 хатымен
title:
  rus: Жамбыл облысының 2005-2007 жылдарға арналған ана мен баланы қорғау Бағдарламасы туралы
  kaz: Жамбыл облысының 2005-2007 жылдарға арналған ана мен баланы қорғау Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-08-26
approved_by:
- '158000000002'
version_date:
  kaz: 2005-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/21788/kaz/29.04.2005
caused_by:
  code: '24167'
  requisite: Жамбыл облыстық мәслихатының 2005 жылғы 29 сәуірдегі № 8-20 шешімі. Жамбыл облыстық әділет Департаментінде 2005 жылғы 18 мамырда № 1616 тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облысы Әділет департаментінің 2007 жылғы 24 сәуірдегі № 4-1874 хатымен
  title:
    rus: Үшінші шақырылған Жамбыл облыстық мәслихаттың 2004 жылғы 27 тамыздағы N 5-5 "Жамбыл облысының 2005-2007 жылдарға арналған ана мен баланы қорғау Бағдарламасы туралы" шешіміне өзгеріс енгізу туралы
    kaz: Үшінші шақырылған Жамбыл облыстық мәслихаттың 2004 жылғы 27 тамыздағы N 5-5 "Жамбыл облысының 2005-2007 жылдарға арналған ана мен баланы қорғау Бағдарламасы туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24167/rus
