act_code: '21788'
requisite: Жамбыл облыстық мәслихатының 2004 жылғы 27 тамыздағы № 5-5 шешімі. Жамбыл облыстық әділет Департаментінде 2004 жылғы 28 қазанда 1475 нөмірімен тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облысы Әділет департаментінің 2007 жылғы 24 сәуірдегі № 4-1874 хатымен
title:
  rus: Жамбыл облысының 2005-2007 жылдарға арналған ана мен баланы қорғау Бағдарламасы туралы
  kaz: Жамбыл облысының 2005-2007 жылдарға арналған ана мен баланы қорғау Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-08-26
approved_by:
- '158000000002'
version_date:
  kaz: 2004-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/21788/kaz/26.08.2004
