act_code: '205494'
requisite: Решение Таласского районного маслихата Жамбылской области от 27 декабря 2024 года № 34-2
title:
  rus: О бюджете города и сельских округов на 2025-2027 годы
  kaz: 2025 - 2027 жылдарға арналған қала және ауылдық округ бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '158011000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205494/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205494/rus/27.12.2024
