act_code: '194017'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 25 февраля 2024 года № 17-3
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Жуалынского районного маслихата»
  kaz: «Жуалы аудандық мәслихаты аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2024-02-25
approved_by:
- '158005000002'
version_date:
  kaz: 2024-02-25
  rus: 2024-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/194017/kaz/25.02.2024
  rus: https://zan.gov.kz/client/#!/doc/194017/rus/25.02.2024
