act_code: '55015'
requisite: Жамбыл облысы Т.Рысқұлов ауданы Құлан ауылдық округі Әкімінің 2010 жылғы 21 қыркүйектегі № 110 шешімі. Жамбыл облысы Т.Рысқұлов ауданының Әділет басқармасында 2010 жылғы 22 қазанда 6-8-109 нөмірімен тіркелді
title:
  rus: Қарақат ауылындағы Сарыбұлақ көшесінің атауын өзгерту туралы
  kaz: Қарақат ауылындағы Сарыбұлақ көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-21
approved_by:
- '158007001002'
version_date:
  kaz: 2010-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/55015/kaz/21.09.2010
