act_code: '134948'
requisite: Решение Жамбылского областного маслихата от 26 сентября 2019 года № 38-11. Зарегистрировано Департаментом юстиции Жамбылской области 27 сентября 2019 года № 4337
title:
  rus: Об утверждении правил и условий размещения наружной (визуальной) рекламы на открытом пространстве за пределами помещений в населенных пунктах, в полосе отвода автомобильных дорог общего пользования, на открытом пространстве за пределами помещений вне населенных пунктов и вне полосы отвода автомобильных дорог общего пользования на территории Жамбылской области
  kaz: Жамбыл облысы аумағында сыртқы (көрнекі) жарнаманы елді мекендердегі үй-жайлардың шегінен тыс ашық кеңістікте, жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеуінде, елді мекендерден тыс жердегі үй-жайлардың шегінен тыс ашық кеңістікте және жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеуінен тыс жерде орналастыру қағидалары мен шарттарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-09-26
approved_by:
- '158000000002'
version_date:
  kaz: 2019-09-26
  rus: 2019-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/134948/kaz/26.09.2019
  rus: https://zan.gov.kz/client/#!/doc/134948/rus/26.09.2019
