act_code: '177996'
requisite: Решение Шуского районного маслихата Жамбылской области от 16 января 2023 года № 40-4
title:
  rus: О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Шуского района на 2023 год
  kaz: 2023 жылы Шу ауданында ауылдық елдi мекендерге жұмыс iстеуге және тұруға келген денсаулық сақтау, бiлiм беру, әлеуметтiк қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтiк қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-01-16
approved_by:
- '158012000002'
version_date:
  kaz: 2023-01-16
  rus: 2023-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/177996/kaz/16.01.2023
  rus: https://zan.gov.kz/client/#!/doc/177996/rus/16.01.2023
