act_code: '57094'
requisite: Решение Байзакского районного маслихата Жамбылской области от 24 декабря 2010 года № 36-11. Зарегистрировано Управлением юстиции Байзакского района Жамбылской области 28 января 2011 года за № 6-1-126. Утратило силу решением Байзакского районного маслихата Жамбылской области от 29 марта 2013 года № 13-12
title:
  rus: Об установлении стоимости разовых талонов
  kaz: Бір жолғы талон құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158003000002'
version_date:
  kaz: 2010-12-24
  rus: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/57094/kaz/24.12.2010
  rus: https://zan.gov.kz/client/#!/doc/57094/rus/24.12.2010
