act_code: '100325'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 22 февраля 2016 года № 42-6. Зарегистрировано Департаментом юстиции Жамбылской области 14 марта 2016 года № 2977. Утратило силу решением маслихата района Т.Рыскулова Жамбылской области от 26 июня 2020 года № 56-5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций по району Т.Рыскулова
  kaz: Т.Рысқұлов ауданы бойынша жиналыстар, митингiлер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-22
approved_by:
- '158007000002'
version_date:
  kaz: 2016-02-22
  rus: 2016-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/100325/kaz/22.02.2016
  rus: https://zan.gov.kz/client/#!/doc/100325/rus/22.02.2016
