act_code: '51421'
requisite: Жамбыл облысы Байзақ ауданы Мырзатай ауылдық округі әкімінің 2010 жылғы 25 ақпандағы № 4 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 25 наурызда 6-2-107 нөмірімен тіркелді
title:
  rus: Мырзатай ауылындағы Новая көшесінің атын өзгерту туралы
  kaz: Мырзатай ауылындағы Новая көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-25
approved_by:
- '158003011002'
version_date:
  kaz: 2010-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/51421/kaz/25.02.2010
