act_code: '213626'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 18 августа 2025 года № 48-9
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Жуалынскому району на 2025-2029 годы
  kaz: Жуалы ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2025-2029 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-18
approved_by:
- '158005000002'
version_date:
  kaz: 2025-08-18
  rus: 2025-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/213626/kaz/18.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213626/rus/18.08.2025
