act_code: '175638'
requisite: Решение Жамбылского областного маслихата от 14 декабря 2022 года № 23-3
title:
  rus: Об областном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-14
approved_by:
- '158000000002'
version_date:
  kaz: 2022-12-14
  rus: 2022-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/175638/kaz/14.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175638/rus/14.12.2022
