act_code: '181825'
requisite: Решение Меркенского районного маслихата Жамбылской области от 19 мая 2023 года № 3-4. Утратило силу решением Меркенского районного маслихата Жамбылской области от 15 сентября 2025 года № 45-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Меркенского районного маслихата»
  kaz: «Меркі аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-05-19
approved_by:
- '158008000002'
version_date:
  kaz: 2023-05-19
  rus: 2023-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/181825/kaz/19.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181825/rus/19.05.2023
