act_code: '181825'
requisite: Решение Меркенского районного маслихата Жамбылской области от 19 мая 2023 года № 3-4. Утратило силу решением Меркенского районного маслихата Жамбылской области от 15 сентября 2025 года № 45-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Меркенского районного маслихата»
  kaz: «Меркі аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-05-19
approved_by:
- '158008000002'
version_date:
  kaz: 2023-07-24
  rus: 2023-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/181825/kaz/24.07.2023
  rus: https://zan.gov.kz/client/#!/doc/181825/rus/24.07.2023
caused_by:
  code: '184414'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 24 июля 2023 года № 5-4
  title:
    rus: О внесении изменений и дополнений в решение Меркенского районного маслихата от 19 мая 2023 года №3-4 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Меркенского районного маслихата»
    kaz: Меркі аудандық мәслихатының 2023 жылғы 19 мамырдағы №3-4 «Меркі аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы шешіміне» өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184414/rus
