act_code: '56487'
requisite: Решение Таразского городского маслихата Жамбылской области от 23 декабря 2010 года № 36-3. Зарегистрировано Управлением юстиции города Тараз Жамбылской области 29 декабря 2010 года за номером 6-1-118. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
title:
  rus: О городском бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '158002000002'
version_date:
  rus: 2011-08-26
source:
  rus: https://zan.gov.kz/client/#!/doc/56487/rus/26.08.2011
caused_by:
  code: '60258'
  requisite: Решение Таразского городского маслихата Жамбылской области от 26 августа 2011 года № 41-3. Зарегистрировано Управлением юстиции города Тараз Жамбылской области 1 сентября 2011 года за номером 6-1-134. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
  title:
    rus: О внесении изменений в решение Таразского городского маслихата от 23 декабря 2010 года № 36-3 "О городском бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған қалалық бюджет туралы" Тараз қалалық мәслихатының 2010 жылғы 23 желтоқсандағы № 36-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/60258/rus
