act_code: '175268'
requisite: Решение акима Сарымолдаевского сельского округа Меркенского района Жамбылской области от 8 декабря 2022 года № 199. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 декабря 2022 года № 31090
title:
  rus: О переименовании некоторых составных частей в селе Сарымолдаева Сарымолдаевского сельского округа
  kaz: Сарымолдаев ауылдық округінің Сарымолдаев ауылындағы кейбір құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-08
approved_by:
- '158008003002'
version_date:
  kaz: 2022-12-08
  rus: 2022-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/175268/kaz/08.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175268/rus/08.12.2022
