act_code: '85362'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 22 декабря 2014 года № 39-3. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2014 года № 2447
title:
  rus: О районном бюджете на 2015 - 2017 годы
  kaz: 2015 - 2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-22
approved_by:
- '158005000002'
version_date:
  kaz: 2015-07-01
  rus: 2015-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/85362/kaz/01.07.2015
  rus: https://zan.gov.kz/client/#!/doc/85362/rus/01.07.2015
caused_by:
  code: '91375'
  requisite: Решение маслихата Жуалынского района Жамбылской области от 1 июля 2015 года № 44-4. Зарегистрировано Департаментом юстиции Жамбылской области 7 июля 2015 года № 2694
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 22 декабря 2014 года № 39-3 «О  районном бюджете на 2015 - 2017 годы»
    kaz: «2015 - 2017 жылдарға арналған аудандық бюджет туралы» Жуалы аудандық мәслихатының 2014 жылғы 22 желтоқсандағы № 39-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91375/rus
