act_code: '150787'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 25 декабря 2020 года № 77-7. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2020 года № 4870
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '158005000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/150787/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150787/rus/25.12.2020
