act_code: '154667'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 7 апреля 2021 года № 4-3. Зарегистрировано Департаментом юстиции Жамбылской области 14 апреля 2021 года № 4937. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 13 декабря 2023 года № 14-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечния отделных категорий нуждающихся граждан по Сарысускому району
  kaz: Сарысу ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2021-04-07
approved_by:
- '158010000002'
version_date:
  kaz: 2022-08-25
  rus: 2022-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/154667/kaz/25.08.2022
  rus: https://zan.gov.kz/client/#!/doc/154667/rus/25.08.2022
caused_by:
  code: '171119'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 25 августа 2022 года № 29-5. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 сентября 2022 года № 29346. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 13 декабря 2023 года № 14-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 7 апреля 2021 года № 4-3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Сарысускому району»
    kaz: Сарысу аудандық мәслихатының 2021 жылғы 7 сәуірдегі № 4-3 «Сарысу ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешiмiне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171119/rus
