act_code: '201924'
requisite: Решение Меркенского районного маслихата Жамбылской области от 21 октября 2024 года № 31-6
title:
  rus: Об установлении стимулирующих надбавок к должностным окладам гражданских служащих коммунального государственного учреждения «Молодежный ресурсный центр» отдела внутренней политики акимата Меркенского района
  kaz: Меркі ауданы әкімдігі ішкі саясат бөлімінің «Жастар ресурстық орталығы» коммуналдық мемлекеттік мекемесінің азаматтық қызметкерлерінің лауазымдық айлықақыларына ынталандыру үстемақыларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-21
approved_by:
- '158008000002'
version_date:
  kaz: 2024-10-21
  rus: 2024-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/201924/kaz/21.10.2024
  rus: https://zan.gov.kz/client/#!/doc/201924/rus/21.10.2024
