act_code: '22456'
requisite: Решение Таразского городского маслихата Жамбылской области от 23 ноября 2004 года № 8-5. Зарегистрировано Департаментом юстиции Жамбылской области 28 декабря 2004 года за № 1536. Утратило силу решением Таразского городского маслихата Жамбылской области от 28 августа 2014 года № 32-4
title:
  rus: Об утверждении Правил предоставления жилищной помощи и компенсации повышения тарифов абонентской платы за телефон
  kaz: Тұрғын үй көмегін беру және телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы төлеу Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-11-23
approved_by:
- '158002000002'
version_date:
  kaz: 2005-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/22456/kaz/16.11.2005
caused_by:
  code: '26089'
  requisite: Решение Таразского городского маслихата Жамбылской области от 16 ноября 2005 года № 17-13. Зарегистрировано Управлением юстиции г. Тараз Жамбылской области 7 декабря 2005 года за № 6-1-17. Утратило силу решением Жамбылского областного маслихата от 28 августа 2014 года № 32-4
  title:
    rus: О внесении изменений и дополнений в решение Таразского городского маслихата третьего созыва от 23 ноября 2004 года N 8-5 "Об утверждении Правил предоставления жилищной помощи и компенсации повышения тарифов абонентской платы за телефон"
    kaz: Тараз қалалық мәслихатының 2004 жылғы 23 қарашадағы N 8-5 "Тұрғын үй көмегін беру және телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы төлеу Ережелерін бекіту туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/26089/rus
