act_code: '84430'
requisite: Решение акима Карасуского сельского округа Кордайского района Жамбылской области от 3 ноября 2014 года № 44. Зарегистрировано Департаментом юстиции Жамбылской области 17 ноября 2014 года № 2375
title:
  rus: О присвоении наименования новой улице № 3 в селе Карасу
  kaz: Қарасу ауылындығы № 3 жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-03
approved_by:
- '158006014001'
version_date:
  kaz: 2014-11-03
  rus: 2014-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/84430/kaz/03.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84430/rus/03.11.2014
