act_code: '54875'
requisite: Жамбыл облысы Жамбыл ауданы Көлқайнар селолық округінің әкімінің 2010 жылғы 1 қазандағы № 10 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 14 қазанда 6-3-124 нөмірімен тіркелді
title:
  rus: Тастөбе ауылындағы Көлқайнар көшесінің атауын өзгерту туралы
  kaz: Тастөбе ауылындағы Көлқайнар көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-01
approved_by:
- '158004009002'
version_date:
  kaz: 2010-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/54875/kaz/01.10.2010
