act_code: '49443'
requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2009 жылғы 3 желтоқсандағы № 22-3 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2009 жылғы 21 желтоқсанда Нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 6-4-81 болып енгізілді. Күші жойылды - Жамбыл облысы Жуалы аудандық мәслихатының 2010 жылғы 4 ақпандағы № 24-5 шешімімен
title:
  rus: '"2009 жылға арналған аудандық бюджет туралы" Жуалы аудандық мәслихаттың 2008 жылғы 26 желтоқсандағы № 12-4 шешіміне өзерістер енгізу туралы'
  kaz: '"2009 жылға арналған аудандық бюджет туралы" Жуалы аудандық мәслихаттың 2008 жылғы 26 желтоқсандағы № 12-4 шешіміне өзерістер енгізу туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-03
approved_by:
- '158005000002'
version_date:
  kaz: 2009-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/49443/kaz/03.12.2009
