act_code: '137287'
requisite: Решение Байзакского районного маслихата Жамбылской области от 19 декабря 2019 года № 59-9. Зарегистрировано Департаментом юстиции Жамбылской области 23 декабря 2019 года № 4457. Утратило силу решением Байзакского районного маслихата Жамбылской области от 23 декабря 2021 года № 20-7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организации здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен отын сатып алу үшін көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-19
approved_by:
- '158003000002'
version_date:
  kaz: 2019-12-19
  rus: 2019-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/137287/kaz/19.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137287/rus/19.12.2019
