act_code: '53670'
requisite: Жамбыл облысы Меркі аудандық мәслихатының 2010 жылғы 18 маусымдағы № 35-5 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 27 шілдеде 6-6-82 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Меркі ауданы мәслихатының 2012 жылғы 16 мамырдағы № 5-8 шешімімен
title:
  rus: Меркі ауданы елді мекендерінің аумақтарын көріктендіру және жасыл желектерді күтіп ұстау мен қорғау Ережелерін бекіту туралы
  kaz: Меркі ауданы елді мекендерінің аумақтарын көріктендіру және жасыл желектерді күтіп ұстау мен қорғау Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-18
approved_by:
- '158008000002'
version_date:
  kaz: 2010-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/53670/kaz/18.06.2010
