act_code: '79210'
requisite: Решение Байзакского районного маслихата Жамбылской области от 14 апреля 2014 года № 28-4. Зарегистрировано Департаментом юстиции Жамбылской области 25 апреля 2014 года № 2191. Утратило силу решением Байзакского районного маслихата Жамбылской области от 27.06.2018 № 31-13
title:
  rus: Об утверждении положения государственного учреждения "Аппарат Байзакского районного маслихата"
  kaz: '"Байзақ аудандық мәслихаты аппараты" мемлекеттік мекемесінің Ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-14
approved_by:
- '158003000002'
version_date:
  kaz: 2014-04-14
  rus: 2014-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/79210/kaz/14.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79210/rus/14.04.2014
