act_code: '151182'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 23 декабря 2020 года № 64-5. Зарегистрировано Департаментом юстиции Жамбылской области 31 декабря 2020 года № 4876
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '158007000002'
version_date:
  kaz: 2021-06-24
  rus: 2021-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/151182/kaz/24.06.2021
  rus: https://zan.gov.kz/client/#!/doc/151182/rus/24.06.2021
caused_by:
  code: '156654'
  requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 24 июня 2021 года № 6-6. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 июня 2021 года № 23221
  title:
    rus: О внесении изменений в решение маслихата района Т.Рыскулова «О районном бюджете на 2021-2023 годы» от 23 декабря 2020 года №64-5
    kaz: «2021-2023 жылдарға арналған аудандық бюджет туралы» Т.Рысқұлов аудандық мәслихатының 2020 жылдың 23 желтоқсандағы №64-5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156654/rus
