act_code: '151182'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 23 декабря 2020 года № 64-5. Зарегистрировано Департаментом юстиции Жамбылской области 31 декабря 2020 года № 4876
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '158007000002'
version_date:
  kaz: 2021-12-06
  rus: 2021-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/151182/kaz/06.12.2021
  rus: https://zan.gov.kz/client/#!/doc/151182/rus/06.12.2021
caused_by:
  code: '161593'
  requisite: Решение района маслихата Т.Рыскулова Жамбылской области от 6 декабря 2021 года № 11-5. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 декабря 2021 года № 25750
  title:
    rus: О внесении изменений в решение маслихата района Т.Рыскулова от 23 декабря 2020 года №64-5 «О районном бюджете на 2021-2023 годы»
    kaz: Т.Рысқұлов аудандық мәслихатының 2020 жылдың 23 желтоқсандағы №64-5 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161593/rus
