act_code: '53483'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2010 жылғы 15 маусымдағы № 32-15 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 8 шілдеде 6-10-101 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Талас аудандық мәслихатының 2012 жылғы 26 маусымдағы № 6-3 шешімімен
title:
  rus: Талас ауданы елді мекендерінің аумақтарын көріктендіру ережесін бекіту туралы
  kaz: Талас ауданы елді мекендерінің аумақтарын көріктендіру ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-15
approved_by:
- '158011000002'
version_date:
  kaz: 2010-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/53483/kaz/15.06.2010
