act_code: '108552'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 22 декабря 2016 года № 8-2. Зарегистрировано Департаментом юстиции Жамбылской области 26 декабря 2016 года № 3262
title:
  rus: О районном бюджете на 2017 - 2019 годы
  kaz: «2017 – 2019 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-22
approved_by:
- '158009000002'
version_date:
  kaz: 2016-12-22
  rus: 2016-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/108552/kaz/22.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108552/rus/22.12.2016
