act_code: '79048'
requisite: Решение Меркенского районного маслихата Жамбылской области от 28 марта 2014 года № 26-6. Зарегистрировано Департаментом юстиции Жамбылской области 18 апреля 2014 года № 2167. Утратило силу решением Меркенского районного маслихата Жамбылской области от 10 мая 2024 года № 23-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) по Меркенскому району
  kaz: Меркі ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-28
approved_by:
- '158008000002'
version_date:
  kaz: 2014-03-28
  rus: 2014-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/79048/kaz/28.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79048/rus/28.03.2014
