act_code: '137728'
requisite: Решение Меркенского районного маслихата Жамбылской области от 27 декабря 2019 года № 62-2. Зарегистрировано Департаментом юстиции Жамбылской области 31 декабря 2019 года № 4483
title:
  rus: О бюджете сельских округов Меркенского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Меркі ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '158008000002'
version_date:
  kaz: 2020-11-12
  rus: 2020-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137728/kaz/12.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137728/rus/12.11.2020
caused_by:
  code: '148763'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 12 ноября 2020 года № 75-2. Зарегистрировано Департаментом юстиции Жамбылской области 20 ноября 2020 года № 4810
  title:
    rus: О внесении изменений в решение Меркенского районного маслихата от 27 декабря 2019 года №62-2 «О бюджете сельских округов Меркенского района на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Меркі ауданы ауылдық округтерінің бюджеттері туралы» Меркі аудандық мәслихатының 2019 жылғы 27 желтоқсандағы №62-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148763/rus
