act_code: '71937'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 29 марта 2013 года № 10-6. Зарегистрировано Департаментом юстиции Жамбылской области 10 апреля 2013 года № 1911. Утратило силу решением маслихата района Т. Рыскулова Жамбылской области от 7 сентября 2020 года № 59-5 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Т.Рыскуловскому району
  kaz: Т.Рысқұлов ауданы бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегiн көрсету Қағидаларын бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-29
approved_by:
- '158007000002'
version_date:
  kaz: 2013-03-29
  rus: 2013-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/71937/kaz/29.03.2013
  rus: https://zan.gov.kz/client/#!/doc/71937/rus/29.03.2013
