act_code: '53504'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2010 жылғы 15 маусымдағы № 38-8 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2010 жылғы 14 шілдеде 6-9-97 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2011 жылғы 18 қазандағы № 55-5 шешімімен
title:
  rus: Отын сатып алу үшін әлеуметтік көмек беру туралы
  kaz: Отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-15
approved_by:
- '158010000002'
version_date:
  kaz: 2010-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/53504/kaz/15.06.2010
