act_code: '49713'
requisite: Жамбыл облысы Сарысу ауданы әкімінің 2009 жылғы 2 желтоқсандағы № 12 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2010 жылғы 6 қаңтарда Нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 6-9-84 болып енгізілді
title:
  rus: 2010 жылы Сарысу ауданының аумағында тұратын 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2010 жылы Сарысу ауданының аумағында тұратын 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-02
approved_by:
- '158010000001'
version_date:
  kaz: 2009-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/49713/kaz/02.12.2009
