act_code: '27820'
requisite: Жамбыл облысы Шу аудандық мәслихатының 2006 жылғы 28 тамыздағы № 22-5-1 шешімі. Жамбыл облысы Шу ауданының Әділет басқармасында 2006 жылғы 6-11-31 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Шу аудандық мәслихатының 2010 жылғы 27 желтоқсандағы № 29-4 шешімімен
title:
  rus: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін беру және телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы төлеу Қағидасын бекіту туралы
  kaz: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін беру және телефон үшін абоненттік ақы тарифтерінің арттырылуына өтемақы төлеу Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-28
approved_by:
- '158012000002'
version_date:
  kaz: 2010-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/27820/kaz/12.08.2010
