act_code: '55257'
requisite: Жамбыл облысы Талас ауданы мәслихатының 2010 жылғы 28 қыркүйектегі № 36-7 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 4 қарашада нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 6-10-111 болып енгізілді
title:
  rus: Біржолғы талон құны туралы
  kaz: Біржолғы талон құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-28
approved_by:
- '158011000002'
version_date:
  kaz: 2010-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/55257/kaz/28.09.2010
