act_code: '43709'
requisite: Жамбыл облысы Шу ауданы әкімінің 2008 жылғы 15 желтоқсандағы № 10 шешімі. Жамбыл облысы Шу ауданының Әділет басқармасында 2009 жылғы 26 қаңтарда 6-11-69 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Шу ауданы әкімінің 2015 жылғы 10 қыркүйекте № 4 шешімімен
title:
  rus: 2009 жылы Шу ауданының аумағында тұратын азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2009 жылы Шу ауданының аумағында тұратын азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-15
approved_by:
- '158012000001'
version_date:
  kaz: 2008-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/43709/kaz/15.12.2008
