act_code: '206375'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 30 декабря 2024 года № 36-2
title:
  rus: О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '158005000002'
version_date:
  kaz: 2025-05-30
  rus: 2025-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206375/kaz/30.05.2025
  rus: https://zan.gov.kz/client/#!/doc/206375/rus/30.05.2025
caused_by:
  code: '210948'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 30 мая 2025 года № 45-2
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 30 декабря 2024 года № 36-2 «О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2025-2027 годы»
    kaz: Жуалы аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 36-2  «2025-2027  жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210948/rus
