act_code: '218661'
requisite: Решение Акима Камкалинского сельского округа Сарысуского района Жамбылской области от 19 сентября 2025 года № 15
title:
  rus: О переименовании улицы Жана в селе Жайлаукол Камкалинского сельского округа Сарысуского района
  kaz: Сарысу ауданы Қамқалы ауылдық округінің Жайлаукөл ауылындағы Жаңа көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-19
approved_by:
- '158010006002'
version_date:
  kaz: 2025-09-19
  rus: 2025-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/218661/kaz/19.09.2025
  rus: https://zan.gov.kz/client/#!/doc/218661/rus/19.09.2025
