act_code: '80270'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 21 апреля 2014 года № 24-9. Зарегистрировано Департаментом юстиции Жамбылской области 23 мая 2014 года № 2225
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии прибывшим для работы и проживания в сельские населенные пункты Т.Рыскуловского района на 2014 год
  kaz: 2014 жылға арналған Т.Рысқұлов ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын ұсыну  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-21
approved_by:
- '158007000002'
version_date:
  kaz: 2014-04-21
  rus: 2014-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/80270/kaz/21.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80270/rus/21.04.2014
