act_code: '96910'
requisite: Решение от 25.12.2015 №48-3, Маслихат Байзакского района. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2015 года № 2880
title:
  rus: 'О районном бюджете на 2016 – 2018 годы  '
  kaz: '2016 – 2018 жылдарға арналған аудандық бюджет туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '158003000002'
version_date:
  kaz: 2016-12-05
  rus: 2016-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/96910/kaz/05.12.2016
  rus: https://zan.gov.kz/client/#!/doc/96910/rus/05.12.2016
caused_by:
  code: '108145'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 5 декабря 2016 года № 8-2. Зарегистрировано Департаментом юстиции Жамбылской области 9 декабря 2016 года № 3250
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата от 25 декабря 2015 года № 48-3 «О районном бюджете на 2016 – 2018 годы»
    kaz: «2016 – 2018 жылдарға арналған аудандық бюджет туралы» Байзақ аудандық мәслихатының 2015 жылғы 25 желтоқсандағы №48-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108145/rus
