act_code: '118420'
requisite: Решение акима Жамбылского сельского округа Меркенского района Жамбылской области от 3 января 2018 года № 01. Зарегистрировано Департаментом юстиции Жамбылской области 18 января 2018 года № 3687
title:
  rus: О переименовании улицы 23-Партсъезда села Плодовоягодный Жамбылского сельского округа
  kaz: Жамбыл ауылдық округі, Плодовоягодное ауылындағы 23-Партсъезд көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-03
approved_by:
- '158008002002'
version_date:
  kaz: 2018-01-03
  rus: 2018-01-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/118420/kaz/03.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118420/rus/03.01.2018
