act_code: '87416'
requisite: Решение акима Асинского аульного округа Жамбылского районного акимата Жамбылской области от 12 февраля 2015 года № 17. Зарегистрировано Департаментом юстиции Жамбылской области 11 марта 2015 года № 2559
title:
  rus: 'О переименовании улицы села Аса Асинского аульного округа '
  kaz: 'Аса ауылдық округінің Аса ауылындағы көше атауын өзгерту туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-12
approved_by:
- '158004001001'
version_date:
  kaz: 2015-02-12
  rus: 2015-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/87416/kaz/12.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87416/rus/12.02.2015
