act_code: '128148'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 21 декабря 2018 года № 34-2. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2018 года № 4062
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '158004000002'
version_date:
  kaz: 2019-07-24
  rus: 2019-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128148/kaz/24.07.2019
  rus: https://zan.gov.kz/client/#!/doc/128148/rus/24.07.2019
caused_by:
  code: '133815'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 24 июля 2019 года № 47-2. Зарегистрировано Департаментом юстиции Жамбылской области 26 июля 2019 года № 4295
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 21 декабря 2018 года №34-2 «О районном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған аудандық бюджет туралы» Жамбыл аудандық мәслихатының 2018 жылғы 21 желтоқсандағы №34-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133815/rus
