act_code: '194523'
requisite: Решение Таласского районного маслихата Жамбылской области от 13 марта 2024 года № 17-4
title:
  rus: Об утверждении программы управления коммунальными отходами Таласского района на 2024-2028 годы
  kaz: Талас ауданы аумағындағы коммуналдық қалдықтарды басқарудың 2024-2028 жылдарға арналған бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2024-03-13
approved_by:
- '158011000002'
version_date:
  kaz: 2024-03-13
  rus: 2024-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/194523/kaz/13.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194523/rus/13.03.2024
