act_code: '163520'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 28 декабря 2021 года № 19-2
title:
  rus: О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '158005000002'
version_date:
  kaz: 2022-06-06
  rus: 2022-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/163520/kaz/06.06.2022
  rus: https://zan.gov.kz/client/#!/doc/163520/rus/06.06.2022
caused_by:
  code: '168673'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 6 июня 2022 года № 26-2
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 28 декабря 2021 года № 19-2 «О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2022-2024 годы»
    kaz: Жуалы ауданы мәслихатының 2021 жылғы 28 желтоқсандағы № 19-2 «2022-2024 жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168673/rus
