act_code: '128034'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 21 декабря 2018 года № 34-5. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2018 года № 4054
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '158007000002'
version_date:
  kaz: 2019-04-01
  rus: 2019-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/128034/kaz/01.04.2019
  rus: https://zan.gov.kz/client/#!/doc/128034/rus/01.04.2019
caused_by:
  code: '131817'
  requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 1 апреля 2019 года № 39-7. Зарегистрировано Департаментом юстиции Жамбылской области 3 апреля 2019 года № 4172
  title:
    rus: О внесении изменений в решение маслихата района Т.Рыскулова от 21 декабря 2018 года №34-5 «О районном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған аудандық бюджет туралы» Т.Рысқұлов аудандық мәслихатының 2018 жылдың 21 желтоқсандағы №34-5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131817/rus
