act_code: '81651'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 23 июня 2014 года № 25-12. Зарегистрировано Департаментом юстиции Жамбылской области 30 июля 2014 года № 2285. Утратило силу решением маслихата района Т.Рыскулова Жамбылской области от 21 июля 2023 года № 5-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении положения государственного учреждения Аппарат Т.Рыскуловского районного маслихата"
  kaz: '"Т.Рысқұлов аудандық мәслихат аппараты" мемлекеттік мекемесінің ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-23
approved_by:
- '158007000002'
version_date:
  kaz: 2014-06-23
  rus: 2014-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/81651/kaz/23.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81651/rus/23.06.2014
