act_code: '137549'
requisite: Решение Кордайского районного маслихата Жамбылской области от 23 декабря 2019 года № 62-4. Зарегистрировано Департаментом юстиции Жамбылской области 27 декабря 2019 года № 4470
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '158006000002'
version_date:
  kaz: 2020-04-21
  rus: 2020-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/137549/kaz/21.04.2020
  rus: https://zan.gov.kz/client/#!/doc/137549/rus/21.04.2020
caused_by:
  code: '142119'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 21 апреля 2020 года № 66-2. Зарегистрировано Департаментом юстиции Жамбылской области 22 апреля 2020 года № 4573
  title:
    rus: О внесении изменений в решение Кордайского районного маслихата от 23 декабря 2019 года № 62-4 «О районном бюджете на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған аудандық  бюджет туралы» Қордай аудандық мәслихатының 2019 жылғы 23 желтоқсандағы № 62-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142119/rus
