act_code: '137998'
requisite: Решение Шуского районного маслихата Жамбылской области от 27 декабря 2019 года № 58-2. Зарегистрировано Департаментом юстиции Жамбылской области 8 января 2020 года № 4488
title:
  rus: О бюджете города Шу и сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Шу қаласы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '158012000002'
version_date:
  kaz: 2020-04-24
  rus: 2020-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/137998/kaz/24.04.2020
  rus: https://zan.gov.kz/client/#!/doc/137998/rus/24.04.2020
caused_by:
  code: '142313'
  requisite: Решение Шуского районного маслихата Жамбылской области от 24 апреля 2020 года № 62-2. Зарегистрировано Департаментом юстиции Жамбылской области 28 апреля 2020 года № 4592
  title:
    rus: О внесении изменений в решение Шуского районного маслихата от 27 декабря 2019 года № 58-2 «О бюджете города Шу  и сельских округов на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Шу қаласы және ауылдық округтерінің бюджеттері туралы» Шу аудандық мәслихатының 2019 жылғы 27 желтоқсандағы № 58-2 шешіміне өзерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142313/rus
