act_code: '172236'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 8 сентября 2022 года № 30-2
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Жуалынскому району на 2022-2023 годы
  kaz: Жуалы ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2022-2023 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2022-09-08
approved_by:
- '158005000002'
version_date:
  kaz: 2022-09-08
  rus: 2022-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/172236/kaz/08.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172236/rus/08.09.2022
