act_code: '96493'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 23 ноября 2015 года № 37-9. Зарегистрировано Департаментом юстиции Жамбылской области 11 декабря 2015 года № 2854. Утратило силу решением маслихата района Т. Рыскулова Жамбылской области от 30.10.2019 № 47-5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении ставок земельного налога и ставок единного земельного налога на не используемые земли сельскохозяйственного назначения в районе Т.Рыскулова
  kaz: Т.Рысқұлов ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының  мөлшерлемелерін және бірыңғай жер салығының мөлшермелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-23
approved_by:
- '158007000002'
version_date:
  kaz: 2015-11-23
  rus: 2015-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/96493/kaz/23.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96493/rus/23.11.2015
