act_code: '204268'
requisite: Решение Жамбылского областного маслихата от 12 декабря 2024 года № 20-4
title:
  rus: Об областном бюджете на 2025 - 2027 годы
  kaz: 2025-2027 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-12
approved_by:
- '158000000002'
version_date:
  kaz: 2025-10-22
  rus: 2025-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/204268/kaz/22.10.2025
  rus: https://zan.gov.kz/client/#!/doc/204268/rus/22.10.2025
caused_by:
  code: '216049'
  requisite: Решение маслихата Жамбылской области от 22 октября 2025 года № 27-2
  title:
    rus: О внесении изменений в решение Жамбылского областного маслихата от 12 декабря 2024 года № 20-4 «Об областном бюджете на 2025-2027 годы»
    kaz: Жамбыл облыстық мәслихатының 2024 жылғы 12 желтоқсандағы  № 20-4 «2025-2027 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216049/rus
