act_code: '66570'
requisite: Решение маслихата Сарысуского района Жамбылской области от 21 июня 2012 года № 5-5. Зарегистрировано Управлением юстиции Сарысуского района 12 июля 2012 года за № 6-9-140. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 25 декабря 2013 года № 25-23
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) по Сарысускому району
  kaz: Сарысу ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-21
approved_by:
- '158010000002'
version_date:
  kaz: 2013-11-22
  rus: 2013-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/66570/kaz/22.11.2013
  rus: https://zan.gov.kz/client/#!/doc/66570/rus/22.11.2013
caused_by:
  code: '75797'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 22 ноября 2013 года № 23-3. Зарегистрировано Департаментом юстиции Жамбылской области 11 декабря 2013 года № 2066. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 10 июня 2014 года № 30-5
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 21 июня 2012 года № 5-5 "Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) по Сарысускому району"
    kaz: '"Сарысу ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Қағидаларын бекіту туралы" Сарысу аудандық мәслихатының 2012 жылғы 21 маусымдағы № 5-5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/75797/rus
