act_code: '66570'
requisite: Решение маслихата Сарысуского района Жамбылской области от 21 июня 2012 года № 5-5. Зарегистрировано Управлением юстиции Сарысуского района 12 июля 2012 года за № 6-9-140. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 25 декабря 2013 года № 25-23
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) по Сарысускому району
  kaz: Сарысу ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-21
approved_by:
- '158010000002'
version_date:
  kaz: 2012-06-21
  rus: 2012-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/66570/kaz/21.06.2012
  rus: https://zan.gov.kz/client/#!/doc/66570/rus/21.06.2012
