act_code: '45861'
requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2009 жылғы 25 ақпандағы № 14-6 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2009 жылғы 31 наурызда 6-8-79 нөмірімен тіркелді
title:
  rus: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
  kaz: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-25
approved_by:
- '158007000002'
version_date:
  kaz: 2009-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/45861/kaz/25.02.2009
