act_code: '45861'
requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2009 жылғы 25 ақпандағы № 14-6 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2009 жылғы 31 наурызда 6-8-79 нөмірімен тіркелді
title:
  rus: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
  kaz: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-25
approved_by:
- '158007000002'
version_date:
  kaz: 2010-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/45861/kaz/15.11.2010
caused_by:
  code: '56070'
  requisite: Жамбыл облысы Т.Рысқұлов аудандық мәслихатының 2010 жылғы 15 қарашадағы № 29-11 шешімі. Жамбыл облысы Т.Рысқұлов ауданының Әділет басқармасында 2010 жылғы 15 желтоқсанда 6-8-113 нөмірімен тіркелді
  title:
    rus: '"Бірыңғай тіркелген салық ставкаларын белгілеу туралы" Т.Рысқұлов аудандық мәслихатының 2009 жылдың 25 ақпанындағы № 14-6 шешіміне өзгеріс енгізу туралы'
    kaz: '"Бірыңғай тіркелген салық ставкаларын белгілеу туралы" Т.Рысқұлов аудандық мәслихатының 2009 жылдың 25 ақпанындағы № 14-6 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56070/rus
