act_code: '176405'
requisite: Решение Кордайского районного маслихата Жамбылской области от 29 декабря 2022 года № 34-2
title:
  rus: О бюджете сельских округов Кордайского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Қордай ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '158006000002'
version_date:
  kaz: 2023-07-14
  rus: 2023-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/176405/kaz/14.07.2023
  rus: https://zan.gov.kz/client/#!/doc/176405/rus/14.07.2023
caused_by:
  code: '183937'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 14 июля 2023 года № 6-2
  title:
    rus: О внесении изменений в решение Кордайского районного маслихата «О бюджете сельских округов Кордайского района на 2023–2025 годы» от 29 декабря 2022 года №34-2
    kaz: «2023-2025 жылдарға арналған Қордай ауданы ауылдық округтерінің бюджеттері туралы» Қордай аудандық мәслихатының 2022 жылғы 29 желтоқсандағы №34-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183937/rus
