act_code: '119436'
requisite: Решение акима Жайылминского аульного округа Сарысуского района Жамбылской области от 5 февраля 2018 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 1 марта 2018 года № 3724
title:
  rus: О переименовании улицы «Кенес» села Жайылма Жайылминского аульного округа
  kaz: Жайылма ауылдық округінің Жайылма ауылындағы «Кеңес» көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-05
approved_by:
- '158010009002'
version_date:
  kaz: 2018-02-05
  rus: 2018-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/119436/kaz/05.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119436/rus/05.02.2018
