act_code: '144246'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 25 июня 2020 года № 67-7. Зарегистрировано Департаментом юстиции Жамбылской области 29 июня 2020 года № 4651
title:
  rus: О дополнительном регулировании организации и проведения мирных собраний на территории Жуалынского района
  kaz: Жуалы ауданы аумағында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '158005000002'
version_date:
  kaz: 2024-03-18
  rus: 2024-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/144246/kaz/18.03.2024
  rus: https://zan.gov.kz/client/#!/doc/144246/rus/18.03.2024
caused_by:
  code: '194831'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 18 марта 2024 года № 18-4. Зарегистрированы Департаментом юстиции Жамбылской области 27 марта 2024 года № 5177-08
  title:
    rus: О внесении изменения в решение Жуалынского районого маслихата № 67-7 от 25 июня 2020 года «О дополнительном регулировании организации и проведения мирных собраний на территории Жуалынского района»
    kaz: «Жуалы ауданы аумағында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібін қосымша реттеу туралы» Жуалы аудандық мәслихатының 2020 жылғы 25 маусымдағы № 67-7 шешiмiне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194831/rus
