act_code: '144482'
requisite: Решение Меркенского районного маслихата Жамбылской области от 1 июля 2020 года № 68-3. Зарегистрировано Департаментом юстиции Жамбылской области 3 июля 2020 года № 4668
title:
  rus: Об определении специализированных мест, порядка использования специализированных мест, норм их предельного наполнения, а также требований к материально-техническому и организационному обеспечению для организации и проведения мирных собраний в Меркенском  районе
  kaz: Меркі ауданында бейбіт жиналыстарды ұйымдастыру және өткізуге арналған арнайы орындар, арнайы орындарды пайдалану тәртібі, олардың шекті толу нормалары, сондай-ақ материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-01
approved_by:
- '158008000002'
version_date:
  kaz: 2023-12-25
  rus: 2023-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/144482/kaz/25.12.2023
  rus: https://zan.gov.kz/client/#!/doc/144482/rus/25.12.2023
caused_by:
  code: '190924'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 25 декабря 2023 года № 17-6. Зарегистрировано Департаментом юстиции Жамбылской области от 27 декабря 2023 года № 5140
  title:
    rus: О внесении изменения в решение Меркенского района маслихата от 25 июня 2020 года № 68-3 «Об определении специализированных мест для проведения собраний, митингов, демонстраций, шествий, пикетирований и правил их использования в Меркенском районе»
    kaz: «Меркі ауданында бейбіт жиналыстарды ұйымдастыру және өткізуге арналған арнайы орындар, арнайы орындарды пайдалану тәртібі, олардың шекті толу нормалары, сондай-ақ материалдық-техникалық және ұйымдастырушылықты қамтамасыз етуге қойылатын талаптарды белгілеу туралы» Меркі аудандық мәслихатының 2020 жылғы 25 маусымдағы №68-3 шешiмiне өзгеріс енгізу енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190924/rus
