act_code: '43413'
requisite: Решение Кордайского районного маслихата Жамбылской области от 26 декабря 2008 года № 12-4. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 14 января 2009 года за № 6-5-71. Прекращено действие по истечении срока, на который решение было принято (письмо Департамента юстиции Жамбылской области от 11.03.2013 года № 2-2-17/388)
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '158006000002'
version_date:
  kaz: 2008-12-26
  rus: 2008-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43413/kaz/26.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43413/rus/26.12.2008
