act_code: '60539'
requisite: Решение Кордайского районного маслихата Жамбылской области от 2 сентября 2011 года № 41-6. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 20 сентября 2011 года за номером 6-5-128. Утратило силу решением Кордайского районного маслихата от 21 августа 2013 года № 20-6
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-02
approved_by:
- '158006000002'
version_date:
  kaz: 2011-09-02
  rus: 2011-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/60539/kaz/02.09.2011
  rus: https://zan.gov.kz/client/#!/doc/60539/rus/02.09.2011
