act_code: '204689'
requisite: Решение Меркенского районного маслихата Жамбылской области от 23 декабря 2024 года № 36-2
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '158008000002'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/204689/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204689/rus/23.12.2024
