act_code: '204689'
requisite: Решение Меркенского районного маслихата Жамбылской области от 23 декабря 2024 года № 36-2
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '158008000002'
version_date:
  kaz: 2025-12-05
  rus: 2025-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/204689/kaz/05.12.2025
  rus: https://zan.gov.kz/client/#!/doc/204689/rus/05.12.2025
caused_by:
  code: '218279'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 5 декабря 2025 года № 50-2
  title:
    rus: О внесении изменений в решение Меркенского районного маслихата от 23 декабря 2024 года № 36-2 «О районном бюджете на 2025-2027 годы»
    kaz: Меркі аудандық мәслихатының 2024 жылғы 23 желтоқсандағы № 36-2 «2025-2027 жылдарға арналған  аудандық бюджет туралы»  шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218279/rus
