act_code: '204689'
requisite: Решение Меркенского районного маслихата Жамбылской области от 23 декабря 2024 года № 36-2
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '158008000002'
version_date:
  kaz: 2025-08-12
  rus: 2025-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/204689/kaz/12.08.2025
  rus: https://zan.gov.kz/client/#!/doc/204689/rus/12.08.2025
caused_by:
  code: '213231'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 12 августа 2025 года № 43-2
  title:
    rus: О внесении изменений в решение Меркенского районного маслихата от 23 декабря 2024 года № 36-2 «О районном бюджете на 2025-2027 годы»
    kaz: Меркі аудандық мәслихатының 2024 жылғы 23 желтоқсандағы № 36-2 «2025-2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213231/rus
