act_code: '43440'
requisite: Жамбыл облысы Меркі аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 17-5 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда 6-6-62 нөмірімен тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Меркі аудандық Әділет басқармасының 2010 жылғы 27 мамырдағы № 4-1151 хатымен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '158008000002'
version_date:
  kaz: 2009-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/43440/kaz/08.12.2009
caused_by:
  code: '49298'
  requisite: Жамбыл облысы Меркі аудандық мәслихатының 2009 жылғы 8 желтоқсандағы № 28-3 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2009 жылғы 15 желтоқсанда Нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 6-6-71 болып енгізілді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Меркі аудандық Әділет басқармасының 2010 жылғы 27 мамырдағы № 4-1151 хатымен
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Меркі аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 17-5 шешіміне өзгерістер енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Меркі аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 17-5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/49298/rus
