act_code: '78648'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 28 марта 2014 года № 26-6. Зарегистрировано Департаментом юстиции Жамбылской области 9 апреля 2014 года № 2150. Утратило силу письмом Департамента юстиции Жамбылской области от 23 октября 2014 года № 2-2-17/17364
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшым для работы и проживания в сельские населенные пункты района в 2014 году
  kaz: 2014 жылы аудандық ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-28
approved_by:
- '158005000002'
version_date:
  kaz: 2014-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/78648/kaz/01.04.2014
