act_code: '56484'
requisite: Решение маслихата Сарысуского района Жамбылской области от 24 декабря 2010 года № 46-4. Зарегистрировано Управлением юстиции Сарысуского района 5 января 2011 года за № 6-9-105. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158010000002'
version_date:
  kaz: 2011-04-26
  rus: 2011-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/56484/kaz/26.04.2011
  rus: https://zan.gov.kz/client/#!/doc/56484/rus/26.04.2011
caused_by:
  code: '58819'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 26 апреля 2011 года № 49-2. Зарегистрировано Управлением юстиции Сарысуского района Жамбылской области 13 мая 2011 года за № 6-9-118. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 10 июня 2014 года № 30-5
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 24 декабря 2010 года № 46-4 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Сарысу аудандық  мәслихатының 2010 жылғы 24 желтоқсандағы № 46-4 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58819/rus
