act_code: '202460'
requisite: Решение Меркенского районного маслихата Жамбылской области от 8 ноября 2024 года № 33-4
title:
  rus: Об утверждении программы по управлению коммунальными отходами Меркенского района Жамбылской области на 2024-2028 гг
  kaz: Жамбыл облысы Меркі ауданының коммуналдық қалдықтарды басқару жөніндегі 2024-2028 жылдарға арналған бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-08
approved_by:
- '158008000002'
version_date:
  kaz: 2024-11-08
  rus: 2024-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/202460/kaz/08.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202460/rus/08.11.2024
