act_code: '122963'
requisite: Решение акима Корагатинского сельского округа района Т. Рыскулова Жамбылской области от 5 июня 2018 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 20 июня 2018 года № 3873
title:
  rus: О переименовании улицы станции Корагаты
  kaz: Қорағаты станциясындағы көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-05
approved_by:
- '158007009002'
version_date:
  kaz: 2018-06-05
  rus: 2018-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/122963/kaz/05.06.2018
  rus: https://zan.gov.kz/client/#!/doc/122963/rus/05.06.2018
