act_code: '128076'
requisite: Решение Таразского городского маслихата Жамбылского области от 19 декабря 2018 года № 40-3. Зарегистрировано Департаментом юстиции Жамбылской области 26 декабря 2018 года № 4065
title:
  rus: О городском бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-19
approved_by:
- '158002000002'
version_date:
  kaz: 2019-05-06
  rus: 2019-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/128076/kaz/06.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128076/rus/06.05.2019
caused_by:
  code: '131511'
  requisite: Решение Таразского городского маслихата Жамбылской области от 6 мая 2019 года № 45-3. Зарегистрировано Департаментом юстиции Жамбылской области 14 мая 2019 года № 4227
  title:
    rus: О внесении изменений в решение Таразского городского маслихата от 19 декабря 2018 года  №40-3 «О городском бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған қалалық бюджет туралы» Тараз қалалық мәслихатының 2018 жылғы 19 желтоқсандағы №40-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131511/rus
