act_code: '128076'
requisite: Решение Таразского городского маслихата Жамбылского области от 19 декабря 2018 года № 40-3. Зарегистрировано Департаментом юстиции Жамбылской области 26 декабря 2018 года № 4065
title:
  rus: О городском бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-19
approved_by:
- '158002000002'
version_date:
  kaz: 2018-12-19
  rus: 2018-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/128076/kaz/19.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128076/rus/19.12.2018
