act_code: '26436'
requisite: Решение маслихата Жамбылской области от 15 декабря 2005 года № 12-18. Зарегистрировано Департаментом юстиции Жамбылской области 9 января 2006 года за № 1634. Утратило силу решением Жамбылского областного маслихата от 25 июня 2015 года № 38-12
title:
  rus: Об утверждении норм бесплатного сбора лекарственного растительного сырья, дикорастущих плодов и других лесных ресурсов на территории государственного лесного фонда области
  kaz: Облыстың мемлекеттік орман қоры учаскелерінде дәрілік өсімдік шикізаттарын, жабайы жемістерді және басқа да орман ресурстарын тегін пайдалану нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-15
approved_by:
- '158000000002'
version_date:
  kaz: 2005-12-15
  rus: 2005-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/26436/kaz/15.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26436/rus/15.12.2005
