act_code: '98174'
requisite: Решение маслихата Жамбылской области от 14 декабря 2015 года № 43-15. Зарегистрировано Департаментом юстиции Жамбылской области 22 января 2016 года № 2915. Утратило силу решением Жамбылского областного маслихата от 11 декабря 2020 года № 52-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек на территории Таласского района  Жамбылской области
  kaz: Жамбыл облысы Талас ауданы аумағында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-14
approved_by:
- '158000000002'
version_date:
  kaz: 2015-12-14
  rus: 2015-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/98174/kaz/14.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98174/rus/14.12.2015
