act_code: '163720'
requisite: Решение Таласского районного маслихата Жамбылской области от 30 декабря 2021 года № 19-2
title:
  rus: О бюджете города и сельских округов на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған қала және ауылдық округ бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '158011000002'
version_date:
  kaz: 2022-12-06
  rus: 2022-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/163720/kaz/06.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163720/rus/06.12.2022
caused_by:
  code: '175056'
  requisite: Решение Таласского районного маслихата Жамбылской области от 6 декабря 2022 года № 35-2
  title:
    rus: О внесении изменений в решение Таласского районного маслихата от 30 декабря 2021 года № 19–2 «О бюджете города и сельских округов на 2022-2024 годы»
    kaz: Талас аудандық мәслихатының 2021 жылғы 30 желтоқсандағы №19-2 «2022-2024 жылдарға арналған қала және ауылдық округ бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175056/rus
