act_code: '100725'
requisite: Решение Таласского районного маслихата Жамбылской области от 17 февраля 2016 года № 51-3. Зарегистрировано Департаментом юстиции Жамбылской области 16 марта 2016 года № 2985. Утратило силу решением Таласского районного маслихата Жамбылской области от 23 июня 2020 года № 74-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций по Таласскому району
  kaz: Талас ауданы бойынша жиналыстар, митингiлер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-17
approved_by:
- '158011000002'
version_date:
  kaz: 2016-02-17
  rus: 2016-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/100725/kaz/17.02.2016
  rus: https://zan.gov.kz/client/#!/doc/100725/rus/17.02.2016
