act_code: '62072'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 15 декабря 2011 года № 42-2. Зарегистрировано Мойынкумским Управлением юстиции Жамбылской области 22 декабря 2011 года за № 6-7-75. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
title:
  rus: О районном бюджете на 2012 - 2014 годы
  kaz: 2012 - 2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-15
approved_by:
- '158009000002'
version_date:
  kaz: 2012-05-08
  rus: 2012-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/62072/kaz/08.05.2012
  rus: https://zan.gov.kz/client/#!/doc/62072/rus/08.05.2012
caused_by:
  code: '65380'
  requisite: Решение Мойынкумского районного маслихата Жамбылской области от 8 мая 2012 года № 4-2. Зарегистрировано Мойынкумским Управлением юстиции Жамбылской области 11 мая 2012 года № 6-7-83. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
  title:
    rus: О внесении изменений в решение Мойынкумского районного маслихата от 15 декабря 2011 года № 42-2 "О районном бюджете на 2012 - 2014 годы"
    kaz: '"2012 - 2014 жылдарға арналған аудандық бюджет туралы" Мойынқұм аудандық мәслихатының 2011 жылғы 15 желтоқсандағы № 42-2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/65380/rus
