act_code: '149498'
requisite: Решение Меркенского районного маслихата Жамбылской области от 27 ноября 2020 года № 76-7. Зарегистрировано Департаментом юстиции Жамбылской области 8 декабря 2020 года № 4822
title:
  rus: О корректировке ставок земельного налога по Меркенскому району
  kaz: Меркі ауданы бойынша жер салығының мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-27
approved_by:
- '158008000002'
version_date:
  kaz: 2020-11-27
  rus: 2020-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/149498/kaz/27.11.2020
  rus: https://zan.gov.kz/client/#!/doc/149498/rus/27.11.2020
