act_code: '194459'
requisite: Решение Таласского районного маслихата Жамбылской области от 13 марта 2024 года № 17-6. Зарегистрировано Департаментом юстиции Жамбылской области от 15 марта 2024 года № 5170-08
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога по Таласскому району
  kaz: Талас ауданы бойынша бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-13
approved_by:
- '158011000002'
version_date:
  kaz: 2024-03-13
  rus: 2024-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/194459/kaz/13.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194459/rus/13.03.2024
