act_code: '188349'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 9 ноября 2023 года № 10-2. Зарегистрировано Департаментом юстиции Жамбылской области от 15 ноября 2023 года № 5116. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 29 марта 2024 года № 19-2 (вводится в действие с 1 января 2024 года)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Жамбылском районе
  kaz: Жамбыл ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-09
approved_by:
- '158004000002'
version_date:
  kaz: 2023-11-09
  rus: 2023-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/188349/kaz/09.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188349/rus/09.11.2023
