act_code: '50000'
requisite: Жамбыл облысы Меркі аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 29-3 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда 6-6-74 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158008000002'
version_date:
  kaz: 2010-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/50000/kaz/11.12.2010
caused_by:
  code: '55998'
  requisite: Жамбыл облысы Меркі аудандық мәслихатының 2010 жылғы 11 желтоқсандағы № 40-3 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 20 желтоқсанда 6-6-87 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Меркі аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 29-3 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Меркі аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 29-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55998/rus
