act_code: '50000'
requisite: Жамбыл облысы Меркі аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 29-3 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда 6-6-74 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158008000002'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50000/kaz/25.12.2009
