act_code: '199802'
requisite: Решение акима Кордайского района Жамбылской области от 15 августа 2024 года № 61. Зарегистрировано Департаментом юстиции Жамбылской области от 15 августа 2024 года № 5224-08
title:
  rus: Об образовании избирательных участков на территории Кордайского района Жамбылской области
  kaz: Жамбыл облысы Қордай ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-15
approved_by:
- '158006000003'
version_date:
  kaz: 2024-08-15
  rus: 2024-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/199802/kaz/15.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199802/rus/15.08.2024
