act_code: '56822'
requisite: Решение акима Акыртюбинского сельского округа района Т.Рыскулова Жамбылской области от 14 декабря 2010 года № 19. Зарегистрировано Управлением юстиции района Т.Рыскулова 14 января 2011 года за № 6-8-118
title:
  rus: О переименовании название улицы Набережная в селе Акыртобе
  kaz: Ақыртөбе ауылындағы Набережная көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '158007005002'
version_date:
  kaz: 2010-12-14
  rus: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56822/kaz/14.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56822/rus/14.12.2010
