act_code: '98043'
requisite: Решение маслихата Жамбылской области от 14 декабря 2015 года № 43-14. Зарегистрировано Департаментом юстиции Жамбылской области 20 января 2016 года № 2911. Утратило силу решением Жамбылского областного маслихата от 06.04.2018 № 22-6
title:
  rus: Об утверждении Правил содержания животных в населенных пунктах Таласского района Жамбылской области
  kaz: Жамбыл облысы Талас ауданының елді мекендерінде жануарларды асырау  Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-14
approved_by:
- '158000000002'
version_date:
  kaz: 2015-12-14
  rus: 2015-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/98043/kaz/14.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98043/rus/14.12.2015
