act_code: '54993'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2010 жылғы 21 қыркүйектегі № 42-7 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2010 жылғы 21 қазанда 6-9-102 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 7 қыркүйектегі 2015 жылғы № 50-4 шешімімен
title:
  rus: Біржолғы талондардың құнын белгілеу туралы
  kaz: Біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-21
approved_by:
- '158010000002'
version_date:
  kaz: 2010-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/54993/kaz/21.09.2010
