act_code: '76367'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 26 декабря 2013 года № 24-3. Зарегистрировано Департаментом юстиции Жамбылской области 30 декабря 2013 года № 2096. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 1 июля 2015 года № 44-6
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-26
approved_by:
- '158005000002'
version_date:
  kaz: 2014-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/76367/kaz/22.04.2014
