act_code: '192454'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 25 декабря 2023 года № 15-11
title:
  rus: Об установлении стимулирующих надбавок к должностным окладам работников организаций, финансируемых из местного бюджета
  kaz: Жергілікті бюджеттен қаржыландырылатын ұйымдар жұмыскерлерінің лауазымдық айлықақыларына ынталандыру үстемеақы белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '158007000002'
version_date:
  kaz: 2023-12-25
  rus: 2023-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/192454/kaz/25.12.2023
  rus: https://zan.gov.kz/client/#!/doc/192454/rus/25.12.2023
