act_code: '74151'
requisite: Решение акима Кокбастауского сельского округа Жуалынского района Жамбылской области от 30 июля 2013 года № 10. Зарегистрировано Департаментом юстиции Жамбылской области 28 августа 2013 года № 1996
title:
  rus: Об установлении ветеринарного режима с введением ограничительных мероприятий на территории сел Терс и Бакалы Кокбастауского сельского округа
  kaz: Көкбастау ауылдық округінің Теріс және Бақалы ауылдары аумағына шектеу іс - шараларын енгізе отырып, ветеринариялық режим белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-07-30
approved_by:
- '158005010002'
version_date:
  kaz: 2013-07-30
  rus: 2013-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/74151/kaz/30.07.2013
  rus: https://zan.gov.kz/client/#!/doc/74151/rus/30.07.2013
