act_code: '46875'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2009 жылғы 16 маусымдағы № 23-12 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2009 жылғы 14 шілдеде 6-9-78 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2011 жылғы 23 мамырдағы № 50-7 шешімімен
title:
  rus: Ауылдық елді мекендерде жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы беру туралы
  kaz: Ауылдық елді мекендерде жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-16
approved_by:
- '158010000002'
version_date:
  kaz: 2009-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/46875/kaz/16.06.2009
