act_code: '20328'
requisite: Решение Кордайского районного маслихата Жамбылской области от 12 мая 2004 года № 4-6. Зарегистрировано Департаментом юстиции Жамбылской области 16 июня 2004 года за № 1375. Утратило силу решением Кордайского районного маслихата Жамбылской области от 4 ноября 2009 года № 20-3
title:
  rus: Об утверждении Правил, за нарушение которых на территории района предусматривается административная ответственность
  kaz: Аудан аумағында тәртіп бұзғаны үшін әкімшілік жауаптылық белгіленетін Ережелерді бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-05-11
approved_by:
- '158006000002'
version_date:
  rus: 2004-05-11
source:
  rus: https://zan.gov.kz/client/#!/doc/20328/rus/11.05.2004
