act_code: '77277'
requisite: Решение Таразского городского маслихата Жамбылской области от 25 декабря 2013 года № 22-7. Зарегистрировано Департаментом юстиции Жамбылской области 4 февраля 2014 года № 2113. Утратило силу решением Таразского городского маслихата Жамбылской области от 05.09.2018 № 35-4
title:
  rus: Об утверждении положения государственного учреждения "Аппарат Таразского городского маслихата"
  kaz: '"Тараз қалалық мәслихаты аппараты" мемлекеттік мекемесінің ережесін бекіту туралы'
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2013-12-25
approved_by:
- '158002000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/77277/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77277/rus/25.12.2013
