act_code: '222908'
requisite: Решение акима района Т. Рыскулова Жамбылской области от 22 февраля 2026 года № 1
title:
  rus: Об объявлении объектового чрезвычайного положения в школе № 3 села Кызылшаруа Акбулакского сельского округа района Т. Рыскулова Жамбылской области
  kaz: Жамбыл облысы Т. Рысқұлов ауданы Ақбұлақ ауылдық округі Қызылшаруа ауылында орналасқан № 3 мектепке объектiлiк табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-02-22
approved_by:
- '158007000003'
version_date:
  kaz: 2026-02-22
  rus: 2026-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/222908/kaz/22.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222908/rus/22.02.2026
