act_code: '55624'
requisite: Жамбыл облысы Мойынқұм аудандық мәслихатының 2010 жылғы 17 қарашадағы № 33-4 шешімі. Жамбыл облысы Мойынқұм ауданының Әділет басқармасында 2010 жылғы 26 қарашада нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 6-7-61 болып енгізілді. Күші жойылды - Жамбыл облысы Мойынқұм аудандық мәслихатының 2011 жылғы 15 желтоқсандағы № 42-6 шешімімен
title:
  rus: Мойынқұм ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегiн көрсету Ережелерiн бекiту туралы
  kaz: Мойынқұм ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегiн көрсету Ережелерiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-17
approved_by:
- '158009000002'
version_date:
  kaz: 2010-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/55624/kaz/17.11.2010
