act_code: '81491'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 24 июня 2014 года № 26-3. Зарегистрировано Департаментом юстиции Жамбылской области 24 июля 2014 года № 2280. Утратило силу решением Мойынкумского районного маслихата Жамбылской области от 26 февраля 2024 года № 16-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Мойынкумском районе
  kaz: Мойынқұм ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-24
approved_by:
- '158009000002'
version_date:
  kaz: 2014-06-24
  rus: 2014-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/81491/kaz/24.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81491/rus/24.06.2014
