act_code: '128015'
requisite: Решение Кордайского районного маслихата Жамбылской области от 24 декабря 2018 года № 42-4. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2018 года № 4058
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '158006000002'
version_date:
  kaz: 2019-05-14
  rus: 2019-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/128015/kaz/14.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128015/rus/14.05.2019
caused_by:
  code: '132199'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 14 мая 2019 года № 49-6. Зарегистрировано Департаментом юстиции Жамбылской области 16 мая 2019 года № 4236
  title:
    rus: О внесении изменений в решение Кордайского районного маслихата от 24 декабря 2018 года № 42-4 «О районном  бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған аудандық бюджет туралы» Қордай аудандық мәслихатының 2018 жылғы 24 желтоқсандағы № 42-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132199/rus
