act_code: '79194'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 21 апреля 2014 года № 24-4. Зарегистрировано Департаментом юстиции Жамбылской области 25 апреля 2014 года № 2193. Утратило силу решением Мойынкумского районного маслихата Жамбылской области от 26.11.2018 № 32-5
title:
  rus: Об утверждении положения государственного учреждения "Аппарат Мойынкумского районного маслихата"
  kaz: '"Мойынқұм аудандық мәслихаты аппараты" мемлекеттік мекемесінің ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-21
approved_by:
- '158009000002'
version_date:
  kaz: 2014-04-21
  rus: 2014-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/79194/kaz/21.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79194/rus/21.04.2014
