act_code: '76261'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 25 декабря 2013 года № 21-4. Зарегистрировано Департаментом юстиции Жамбылской области 28 декабря 2013 года № 2094
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '158007000002'
version_date:
  kaz: 2014-12-02
  rus: 2014-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/76261/kaz/02.12.2014
  rus: https://zan.gov.kz/client/#!/doc/76261/rus/02.12.2014
caused_by:
  code: '84924'
  requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 2 декабря 2014 года № 29-4. Зарегистрировано Департаментом юстиции Жамбылской области 11 декабря 2014 года № 2418
  title:
    rus: О внесении изменений в решение маслихата района Т. Рыскулова от 25 декабря 2013 года № 21-4 "О районном бюджете на 2014-2016 годы"
    kaz: О внесении изменений в решение маслихата района Т. Рыскулова от 25 декабря 2013 года № 21-4 "О районном бюджете на 2014-2016 годы"
  link: https://zan.gov.kz/client/#!/doc/84924/rus
