act_code: '115350'
requisite: Решение Жамбылского областного маслихата от 6 октября 2017 года № 15-10. Зарегистрировано Департаментом юстиции Жамбылской области 17 октября 2017 года № 3545
title:
  rus: Об утверждении правил регулирования миграционных процессов в Жамбылской области
  kaz: Жамбыл облысында көші-қон процестерін реттеудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-10-06
approved_by:
- '158000000002'
version_date:
  kaz: 2021-06-30
  rus: 2021-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/115350/kaz/30.06.2021
  rus: https://zan.gov.kz/client/#!/doc/115350/rus/30.06.2021
caused_by:
  code: '157533'
  requisite: Решение Жамбылского областного маслихата от 30 июня 2021 года № 7-9
  title:
    rus: О внесении изменений в решение маслихата Жамбылской области от 6 октября 2017 года № 15-10 «Об утверждении правил регулирования миграционных процессов в Жамбылской области»
    kaz: «Жамбыл облысында көші-қон процестерін реттеудің қағидаларын бекіту туралы» Жамбыл облыстық мәслихаттың 2017 жылғы 6 қазандағы № 15-10 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157533/rus
