act_code: '9621'
requisite: Решение Жамбылского областного маслихата от 22 июня 2001 года № 9-8. Зарегистрировано Управлением юстиции Жамбылской области 16 июля 2001 года за № 380. Утратил силу решением Жамбылского областного маслихата от 28 октября 2005 года № 11-7
title:
  rus: О схеме зонирования земель города Тараза
  kaz: О схеме зонирования земель города Тараза
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-06-21
approved_by:
- '158000000002'
version_date:
  rus: 2001-06-21
source:
  rus: https://zan.gov.kz/client/#!/doc/9621/rus/21.06.2001
