act_code: '117275'
requisite: Решение Байзакского районного маслихата Жамбылской области от 14 декабря 2017 года № 22-2. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2017 года № 3649
title:
  rus: О районном бюджете на 2018 – 2020 годы
  kaz: 2018 – 2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-14
approved_by:
- '158003000002'
version_date:
  kaz: 2018-11-26
  rus: 2018-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/117275/kaz/26.11.2018
  rus: https://zan.gov.kz/client/#!/doc/117275/rus/26.11.2018
caused_by:
  code: '126271'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 26 ноября 2018 года № 35-3. Зарегистрировано Департаментом юстиции Жамбылской области 27 ноября 2018 года № 3988
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата от 14 декабря 2017 года № 22-2 «О районном бюджете на 2018–2020 годы»
    kaz: «2018 – 2020 жылдарға арналған аудандық бюджет туралы» Байзақ аудандық мәслихатының 2017 жылғы 14 желтоқсандағы № 22-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126271/rus
