act_code: '84718'
requisite: Решение Таразского городского маслихата Жамбылской области от 24 декабря 2014 года № 37-7. Зарегистрировано Департаментом юстиции Жамбылской области 3 февраля 2015 года № 2488. Утратило силу решением Таразского городского маслихата Жамбылской области от 26.02.2016 № 51-4
title:
  rus: О дополнительном регламентировании  порядка проведения  собраний, митингов,  шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер мен  демонстрациялар өткізу тәртібін  қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '158002000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/84718/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/84718/rus/24.12.2014
