act_code: '52721'
requisite: Жамбыл облысы Байзақ ауданы Сарыкемер ауылдық округі әкімінің 2010 жылғы 23 сәуірдегі № 50 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 24 мамырда 6-2-116 нөмірімен тіркелді
title:
  rus: Сарыкемер ауылындағы Первомайская көшесінің атын өзгерту туралы
  kaz: Сарыкемер ауылындағы Первомайская көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-23
approved_by:
- '158003001002'
version_date:
  kaz: 2010-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/52721/kaz/23.04.2010
