act_code: '40904'
requisite: Жамбыл облысы Қордай ауданы Отар ауылдық округі әкімінің 2008 жылғы 27 маусымдағы № 20 шешімі. Жамбыл облысы Қордай ауданының әділет басқармасында 2008 жылғы 29 шілдеде 6-5-63 нөмірімен тіркелді
title:
  rus: Көше аттарын өзгерту туралы
  kaz: Көше аттарын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-27
approved_by:
- '158006011002'
version_date:
  kaz: 2008-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/40904/kaz/27.06.2008
