act_code: '219818'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 22 декабря 2025 года № 58-3
title:
  rus: «О районном бюджете на 2026-2028 годы»
  kaz: «2026-2028 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '158005000002'
version_date:
  kaz: 2026-06-29
  rus: 2026-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/219818/kaz/29.06.2026
  rus: https://zan.gov.kz/client/#!/doc/219818/rus/29.06.2026
caused_by:
  code: '227439'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 29 июня 2026 года № 69-6
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 22 декабря 2025 года № 58-3 «О районном бюджете на 2026-2028 годы»
    kaz: Жуалы аудандық мәслихатының 2025 жылғы 22 желтоқсандағы № 58-3 «2026-2028 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227439/rus
