act_code: '162555'
requisite: Решение Таласского районного маслихата Жамбылской области от 27 декабря 2021 года № 18-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26203
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '158011000002'
version_date:
  kaz: 2022-07-04
  rus: 2022-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/162555/kaz/04.07.2022
  rus: https://zan.gov.kz/client/#!/doc/162555/rus/04.07.2022
caused_by:
  code: '169615'
  requisite: Решение Таласского районного маслихата Жамбылской области от 4 июля 2022 года № 27-2
  title:
    rus: О внесении изменений в решение Таласского районного маслихата от 27 декабря 2021 года № 18-3 «О районном бюджете на 2022-2024 годы»
    kaz: Талас аудандық мәслихатының 2021 жылғы 27 желтоқсандағы № 18-3 «2022–2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169615/rus
