act_code: '200057'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 15 августа 2024 года № 25-4. Зарегистрировано Департаментом юстиции Жамбылской области от 26 августа 2024 года № 5228-08
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Мойынкумском районе
  kaz: Мойынқұм ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-15
approved_by:
- '158009000002'
version_date:
  kaz: 2024-08-15
  rus: 2024-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/200057/kaz/15.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200057/rus/15.08.2024
