act_code: '107030'
requisite: Решение Таразского городского маслихата Жамбылской области от 28 сентября 2016 года № 9-5. Зарегистрировано Департаментом юстиции Жамбылской области 20 октября 2016 года № 3184
title:
  rus: Об определение размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностям из числа инвалидов индивидуальному учебному плану по городу Тараз
  kaz: Тараз қаласында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-28
approved_by:
- '158002000002'
version_date:
  kaz: 2023-06-16
  rus: 2023-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/107030/kaz/16.06.2023
  rus: https://zan.gov.kz/client/#!/doc/107030/rus/16.06.2023
caused_by:
  code: '183344'
  requisite: Решение Таразского городского маслихата Жамбылской области от 16 июня 2023 года № 4-5. Зарегистрировано Департаментом юстиции Жамбылской области 22 июня 2023 года № 5046
  title:
    rus: О внесении изменении в решение Таразского городского маслихата от 28 сентября 2016 года №9-5 «Об определении порядка и размера возмещения затрат на обучение на дому детей с инвалидностью по индивидуальному учебному плану в городе Тараз»
    kaz: «Тараз қаласында мүгедектігі бар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі және мөлшерін айқындау туралы» Тараз қалалық мәслихатының 2016 жылғы 28 қыркүйектегі №9-5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183344/rus
