act_code: '107030'
requisite: Решение Таразского городского маслихата Жамбылской области от 28 сентября 2016 года № 9-5. Зарегистрировано Департаментом юстиции Жамбылской области 20 октября 2016 года № 3184
title:
  rus: Об определение размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностям из числа инвалидов индивидуальному учебному плану по городу Тараз
  kaz: Тараз қаласында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-28
approved_by:
- '158002000002'
version_date:
  kaz: 2016-09-28
  rus: 2016-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/107030/kaz/28.09.2016
  rus: https://zan.gov.kz/client/#!/doc/107030/rus/28.09.2016
