act_code: '107030'
requisite: Решение Таразского городского маслихата Жамбылской области от 28 сентября 2016 года № 9-5. Зарегистрировано Департаментом юстиции Жамбылской области 20 октября 2016 года № 3184
title:
  rus: Об определение размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностям из числа инвалидов индивидуальному учебному плану по городу Тараз
  kaz: Тараз қаласында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-28
approved_by:
- '158002000002'
version_date:
  kaz: 2020-08-21
  rus: 2020-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/107030/kaz/21.08.2020
  rus: https://zan.gov.kz/client/#!/doc/107030/rus/21.08.2020
caused_by:
  code: '145962'
  requisite: Решение Таразского городского маслихата Жамбылской области от 21 августа 2020 года № 61-5. Зарегистрировано Департаментом юстиции Жамбылской области 2 сентября 2020 года № 4715
  title:
    rus: О внесении изменений в решение Таразского городского маслихата от 28 сентября 2016 года №9-5 «Об определение размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностям из числа инвалидов индивидуальному учебному плану по городу Тараз»
    kaz: «Тараз қаласында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы» Тараз қалалық мәслихатының 2016 жылғы 28 қыркүйектегі №9-5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145962/rus
