act_code: '55845'
requisite: Жамбыл облысы Жуалы ауданы әкімінің 2010 жылғы 29 қазандағы № 3 шешімі. Жамбыл облысының Әділет департаментінде 2010 жылғы 9 желтоқсанда № 1762 тіркелді
title:
  rus: 2011 жылы Жуалы ауданының аумағында тұратын 1994 жылы туылған еркек-жынысты азаматтарды шақыру учаскесінде тіркеу жүргізуді ұйымдастыру туралы
  kaz: 2011 жылы Жуалы ауданының аумағында тұратын 1994 жылы туылған еркек-жынысты азаматтарды шақыру учаскесінде тіркеу жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-29
approved_by:
- '158005000003'
version_date:
  kaz: 2010-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/55845/kaz/29.10.2010
