act_code: '54994'
requisite: Жамбыл облысы Қордай ауданы Қордай ауылдық округі әкімінің 2010 жылғы 14 қыркүйектегі № 391 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 22 қазанда 6-5-103 нөмірімен тіркелді
title:
  rus: Қордай ауылындағы Зеленая көшесінің атауын өзгерту туралы
  kaz: Қордай ауылындағы Зеленая көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-14
approved_by:
- '158006001002'
version_date:
  kaz: 2010-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/54994/kaz/14.09.2010
