act_code: '19454'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2004 жылғы 17 ақпандағы № 4-15 шешімі. Жамбыл облыстық Әділет Департаментінде 2004 жылғы 9 сәуірде № 1309 тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2005 жылғы 27 желтоқсандағы № 19-10 шешімімен
title:
  rus: Жекелеген азаматтар топтарына әлеуметтік төлемді жүзеге асыру Ережесін бекіту туралы
  kaz: Жекелеген азаматтар топтарына әлеуметтік төлемді жүзеге асыру Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-02-17
approved_by:
- '158010000002'
version_date:
  kaz: 2005-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/19454/kaz/27.12.2005
