act_code: '56750'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 24 декабря 2010 года № 30-6. Зарегистрировано Управлением юстиции района Т.Рыскулова 13 января 2011 года за № 6-8-117. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158007000002'
version_date:
  kaz: 2011-11-07
  rus: 2011-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/56750/kaz/07.11.2011
  rus: https://zan.gov.kz/client/#!/doc/56750/rus/07.11.2011
caused_by:
  code: '61227'
  requisite: Решение районного маслихата района Т. Рыскулова Жамбылской области от 7 ноября 2011 года № 38-4. Зарегистрировано Управлением юстиции района Т.Рыскулова Жамбылской области 10 ноября 2011 года за № 6-8-128. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
  title:
    rus: О внесении изменений в решение маслихата района Т.Рыскулова № 30-6 от 24 декабря 2010 года "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Т.Рысқұлов аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 30-6 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61227/rus
