act_code: '56914'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 24 декабря 2010 года № 35-14. Зарегистрировано Управлением юстиции Жуалынского района Жамбылской области 20 января 2011 года за № 6-4-99. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 26 июня 2012 года № 6-3
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Жуалынскому району
  kaz: Жуалы ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158005000002'
version_date:
  kaz: 2010-12-24
  rus: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56914/kaz/24.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56914/rus/24.12.2010
