act_code: '76707'
requisite: Решение маслихата Таласского района Жамбылской области от 25 декабря 2013 года № 26-6. Зарегистрировано Департаментом юстиции Жамбылской области 17 января 2014 года № 2101. Утратило силу решением Таласского районного маслихата Жамбылской области от 13.05.2019 № 55-3
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Таласскому району
  kaz: Талас ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін  белгілеудің және мұқтаж азаматтардың  жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '158011000002'
version_date:
  kaz: 2014-06-23
  rus: 2014-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/76707/kaz/23.06.2014
  rus: https://zan.gov.kz/client/#!/doc/76707/rus/23.06.2014
caused_by:
  code: '81288'
  requisite: Решение Таласского районного маслихата Жамбылской области от 23 июня 2014 года № 34-8. Зарегистрировано Департаментом юстиции Жамбылской области 15 июля 2014 года № 2272. Утратило силу решением Таласского районного маслихата Жамбылской области от 13.05.2019 № 55-3
  title:
    rus: О внесении изменений в решение Таласского районного маслихата от 25 декабря 2013 года № 26-6 "Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Таласкому району"
    kaz: '"Талас ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы" Талас аудандық мәслихатының 2013 жылғы 25 желтоқсандағы № 26-6 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/81288/rus
