act_code: '50341'
requisite: Жамбыл облысы Т. Рысқұлов ауданы Қайыңды ауылы аймағы әкімінің 2009 жылғы 25 желтоқсандағы № 14 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2010 жылғы 28 қаңтарда 6-8-93 нөмірімен тіркелді
title:
  rus: Қайыңды ауылындағы Клубная көшесінің атауын Ұлы Отан соғысының ардагері Барлыбаев Жолшыбектің атына өзгерту туралы
  kaz: Қайыңды ауылындағы Клубная көшесінің атауын Ұлы Отан соғысының ардагері Барлыбаев Жолшыбектің атына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158007004001'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50341/kaz/25.12.2009
