act_code: '176288'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 28 декабря 2022 года № 29-2
title:
  rus: «О бюджете сельских округов Жамбылского района на 2023-2025 годы»
  kaz: «2023-2025 жылдарға арналған Жамбыл ауданы ауылдық округтерінің бюджеттері туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '158004000002'
version_date:
  kaz: 2023-08-28
  rus: 2023-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/176288/kaz/28.08.2023
  rus: https://zan.gov.kz/client/#!/doc/176288/rus/28.08.2023
caused_by:
  code: '185541'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 28 августа 2023 года № 6-2
  title:
    rus: О внесений изменений в решение Жамбылского районного маслихата Жамбылской области «О бюджете сельских округов Жамбылского района на 2023-2025 годы» от 28 декабря 2022 года №29-2
    kaz: «2023-2025 жылдарға арналған Жамбыл ауданы ауылдық округтерінің бюджеттері туралы» Жамбыл облысы Жамбыл аудандық мәслихатының 2022 жылғы 28 желтоқсандағы №29-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185541/rus
