act_code: '191502'
requisite: Решение Таразского городского маслихата Жамбылской области от 27 декабря 2023 года № 11-2
title:
  rus: О городском бюджете на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '158002000002'
version_date:
  kaz: 2024-03-15
  rus: 2024-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/191502/kaz/15.03.2024
  rus: https://zan.gov.kz/client/#!/doc/191502/rus/15.03.2024
caused_by:
  code: '194745'
  requisite: Решение Таразского городского маслихата Жамбылской области от 15 марта 2024 года № 14-6
  title:
    rus: О внесении изменений в решение Таразского городского маслихата от 27 декабря 2023 года №11-2 «О городском бюджете на 2024-2026 годы»
    kaz: «2024-2026 жылдарға арналған қалалық бюджет туралы» Тараз қалалық мәслихатының 2023 жылғы 27 желтоқсандағы №11-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194745/rus
