act_code: '76184'
requisite: Решение Жамбылского областного маслихата от 18 декабря 2013 года № 20-3. Зарегистрировано Департаментом юстиции Жамбылской области 23 декабря 2013 года № 2077
title:
  rus: Об областном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-18
approved_by:
- '158000000002'
version_date:
  kaz: 2014-06-12
  rus: 2014-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/76184/kaz/12.06.2014
  rus: https://zan.gov.kz/client/#!/doc/76184/rus/12.06.2014
caused_by:
  code: '80762'
  requisite: Решение Жамбылского областного маслихата от 12 июня 2014 года № 25-2. Зарегистрировано Департаментом юстиции Жамбылской области 18 июня 2014 года № 2242
  title:
    rus: О внесении изменений в решение Жамбылского областного маслихата от 18 декабря 2013 года № 20-3 "Об областном бюджете на 2014-2016 годы"
    kaz: '"2014-2016 жылдарға арналған облыстық бюджет туралы" Жамбыл облыстық мәслихатының 2013 жылғы 18 желтоқсандағы № 20-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/80762/rus
