act_code: '56849'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 24 декабря 2010 года № 46-14. Зарегистрировано Управлением юстиции Сарысуского района 19 января 2011 года за № 6-9-108. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 21 июня 2012 года № 5-13
title:
  rus: Об утверждении Правил содержания собак и кошек в Сарысуском районе
  kaz: Сарысу ауданында иттер мен мысықтарды ұстау ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158010000002'
version_date:
  kaz: 2010-12-24
  rus: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56849/kaz/24.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56849/rus/24.12.2010
