act_code: '137662'
requisite: Решение Байзакского районного маслихата Жамбылской области от 27 декабря 2019 года № 60-2. Зарегистрировано Департаментом юстиции Жамбылской области 30 декабря 2019 года № 4482
title:
  rus: О бюджете сельских округов Байзакского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Байзақ ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '158003000002'
version_date:
  kaz: 2020-12-10
  rus: 2020-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/137662/kaz/10.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137662/rus/10.12.2020
caused_by:
  code: '149711'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 10 декабря 2020 года № 76-2. Зарегистрировано Департаментом юстиции Жамбылской области 11 декабря 2020 года № 4833
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата от 27 декабря 2019 года №60-2 «О бюджете сельских округов Байзакского района на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Байзақ ауданы ауылдық округтерінің бюджеттері туралы» Байзақ аудандық мәслихатының 2019 жылғы 27 желтоқсандағы №60-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149711/rus
