act_code: '190035'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 11 декабря 2023 года № 12-5. Зарегистрировано Департаментом юстиции Жамбылской области 13 декабря 2023 года № 5131
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Жуалынскому району
  kaz: Жуалы ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-11
approved_by:
- '158005000002'
version_date:
  kaz: 2025-01-15
  rus: 2025-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190035/kaz/15.01.2025
  rus: https://zan.gov.kz/client/#!/doc/190035/rus/15.01.2025
caused_by:
  code: '206787'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 15 января 2025 года № 37-2. Зарегистрировано Департаментом юстиции Жамбылской области от 22 января 2025 года № 5257-08
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 11 декабря 2023 года № 12-5 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Жуалынскому району»
    kaz: «Жуалы ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Жуалы аудандық мәслихатының 2023 жылғы 11 желтоқсандағы № 12-5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/206787/rus
