act_code: '137436'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 19 декабря 2019 года № 52-2. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2019 года № 4465
title:
  rus: О районном бюджете на 2020 - 2022 годы
  kaz: 2020 – 2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-19
approved_by:
- '158009000002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/137436/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/137436/rus/24.06.2020
caused_by:
  code: '144306'
  requisite: Решение Мойынкумского районного маслихата Жамбылской области от 24 июня 2020 года № 60-2. Зарегистрировано Департаментом юстиции Жамбылской области 30 июня 2020 года № 4657
  title:
    rus: О внесении изменений в решение Мойынкумского районного маслихата от 19 декабря 2019 года №52-2 «О районном бюджете на 2020-2022 годы»
    kaz: «2020–2022 жылдарға арналған аудандық бюджет туралы» Мойынқұм аудандық мәслихатының 2019 жылғы 19 желтоқсандағы №52-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144306/rus
