act_code: '196215'
requisite: Решение Жамбылского областного маслихата от 24 апреля 2024 года № 14-3. Зарегистрированы Департаментом юстиции Жамбылской области 29 апреля 2024 года № 5198-08
title:
  rus: Об определении порядка и размера оказания социальной поддержки медицинских и фармацевтических работников, направленных для работы в сельской местности и поселках, городах районного и областного значения Жамбылской области
  kaz: Жамбыл облысының ауылдық жерге және кенттерге, аудандық және облыстық маңызы бар қалаларға жұмысқа жіберілген медицина және фармацевтика қызметкерлеріне әлеуметтік қолдау көрсету тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-24
approved_by:
- '158000000002'
version_date:
  kaz: 2024-04-24
  rus: 2024-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/196215/kaz/24.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196215/rus/24.04.2024
