act_code: '123674'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 29 июня 2018 года № 29-3. Зарегистрировано Департаментом юстиции Жамбылской области 13 июля 2018 года № 3908. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 11 декабря 2023 года № 12-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества сельских округов Жуалынского района
  kaz: Жуалы ауданының ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-29
approved_by:
- '158005000002'
version_date:
  kaz: 2021-09-29
  rus: 2021-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/123674/kaz/29.09.2021
  rus: https://zan.gov.kz/client/#!/doc/123674/rus/29.09.2021
caused_by:
  code: '159174'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 29 сентября 2021 года № 13-7. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 28 декабря 2023 года № 15-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Жуалынского районного маслихата от 29 июня 2018 года № 29-3 «Об утверждении регламента собрания местного сообщества сельских округов Жуалынского района»
    kaz: «Жуалы ауданының ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» Жуалы аудандық мәслихатының 2018 жылғы 29 маусымдағы № 29-3 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159174/rus
