act_code: '225545'
requisite: Решение Таласского районного маслихата Жамбылской области от 21 мая 2026 года № 57-4
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня  отдельных категорий нуждающихся  граждан по Таласскому району
  kaz: Талас ауданы бойынша Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-21
approved_by:
- '158011000002'
version_date:
  kaz: 2026-05-21
  rus: 2026-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/225545/kaz/21.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225545/rus/21.05.2026
