act_code: '97083'
requisite: Решение от 25.12.2015 №48-2, Маслихат Жамбылского района (Жамбылской области). Зарегистрировано Департаментом юстиции Жамбылской области 28 декабря 2015 года № 2877
title:
  rus: 'О районном бюджете на 2016--2018 годы '
  kaz: '2016-2018 жылдарға арналған аудандық бюджет туралы  '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '158004000002'
version_date:
  kaz: 2016-07-21
  rus: 2016-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/97083/kaz/21.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97083/rus/21.07.2016
caused_by:
  code: '104979'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 21 июля 2016 года № 3-2. Зарегистрировано Департаментом юстиции Жамбылской области 26 июля 2016 года № 3140
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 25 декабря 2015 года №48-2 «О районном бюджете на 2016-2018 годы
    kaz: «2016-2018 жылдарға арналған аудандық бюджет туралы» Жамбыл аудандық мәслихатының 2015 жылғы 25 желтоқсандағы №48-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104979/rus
