act_code: '186201'
requisite: Решение Таразского городского маслихата Жамбылской области от 15 сентября 2023 года № 7-7
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Таразского городского маслихата
  kaz: «Тараз қалалық мәслихаты аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-09-15
approved_by:
- '158002000002'
version_date:
  kaz: 2023-09-15
  rus: 2023-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/186201/kaz/15.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186201/rus/15.09.2023
