act_code: '96908'
requisite: Решение от 25.12.2015 № 41-4, Маслихат Мойынкумского района. Зарегистрировано Департаментом юстиции Жамбылской области 28 декабря 2015 года № 2873
title:
  rus: О районном бюджете на 2016 - 2018 годы
  kaz: «2016 – 2018 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '158009000002'
version_date:
  kaz: 2016-12-05
  rus: 2016-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/96908/kaz/05.12.2016
  rus: https://zan.gov.kz/client/#!/doc/96908/rus/05.12.2016
caused_by:
  code: '108144'
  requisite: Решение Мойынкумского районного маслихата Жамбылской области от 5 декабря 2016 года № 7-2. Зарегистрировано Департаментом юстиции Жамбылской области 8 декабря 2016 года № 3248
  title:
    rus: О внесении изменений в решение Мойынкумского районного маслихата от 25 декабря 2015  года №41-4 «О районном бюджете на 2016 - 2018 годы»
    kaz: «2016 – 2018 жылдарға арналған аудандық бюджет туралы» Мойынқұм аудандық мәслихатының 2015 жылғы 25 желтоқсандағы № 41-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108144/rus
