act_code: '14945'
requisite: Решение Кордайского районного маслихата Жамбылской области от 14 февраля 2003 года № 21-8. Зарегистрировано Управлением юстиции Жамбылской области 12 марта 2003 года за № 863. Утратило силу решением Кордайского районного маслихата Жамбылской области от 20 декабря 2006 года № 25-11
title:
  rus: Об утверждении Положения о размерах и порядке предоставления пособия малообеспеченным семьям (гражданам) на оплату содержания жилища и потребления коммунальных услуг
  kaz: Табысы аз отбасыларына /азаматтарға/ тұрғын жайды ұстауға және коммуналдық қызметтерді тұтынуға ақы төлеуге берілетін жәрдемақылардың мөлшері мен белгілену тәртібі жөніндегі ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-02-14
approved_by:
- '158006000002'
version_date:
  kaz: 2003-02-14
  rus: 2003-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/14945/kaz/14.02.2003
  rus: https://zan.gov.kz/client/#!/doc/14945/rus/14.02.2003
