act_code: '187934'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 30 октября 2023 года № 10-8. Зарегистрировано Департаментом юстиции Жамбылской области от 3 ноября 2023 года № 5110
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по району Т.Рыскулова
  kaz: Т.Рысқұлов ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-30
approved_by:
- '158007000002'
version_date:
  kaz: 2024-09-10
  rus: 2024-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/187934/kaz/10.09.2024
  rus: https://zan.gov.kz/client/#!/doc/187934/rus/10.09.2024
caused_by:
  code: '200803'
  requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 10 сентября 2024 года № 23-7. Зарегистрировано Департаментом юстиции Жамбылской области от 17 сентября 2024 года № 5235-08
  title:
    rus: О внесении изменение в решение маслихата района Т. Рыскулова Жамбылской области от 30 октября 2023 года № 10-8 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по району Т. Рыскулова»
    kaz: «Т. Рысқұлов ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2023 жылғы 30 қазандағы № 10-8 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200803/rus
