act_code: '161857'
requisite: Решение Жамбылского областного маслихата от 13 декабря 2021 года № 12-5. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 декабря 2021 года № 25874
title:
  rus: Об областном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-13
approved_by:
- '158000000002'
version_date:
  kaz: 2022-09-08
  rus: 2022-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/161857/kaz/08.09.2022
  rus: https://zan.gov.kz/client/#!/doc/161857/rus/08.09.2022
caused_by:
  code: '171680'
  requisite: Решение Жамбылского областного маслихата от 8 сентября 2022 года № 20-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 сентября 2022 года № 29633
  title:
    rus: О внесении изменений в решение Жамбылского областного маслихата от 13 декабря 2021 года №12-5 «Об областном бюджете на 2022-2024 годы»
    kaz: Жамбыл облыстық мәслихатының 2021 жылғы 13 желтоқсандағы №12-5 «2022-2024 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171680/rus
