act_code: '46877'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2009 жылғы 16 маусымдағы № 23-9 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2009 жылғы 16 шілдеде 6-9-80 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2011 жылғы 18 қазандағы № 55-5 шешімімен
title:
  rus: Тіркелген салық ставкаларын белгілеу туралы
  kaz: Тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-16
approved_by:
- '158010000002'
version_date:
  kaz: 2009-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/46877/kaz/16.06.2009
