act_code: '117394'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 21 декабря 2017 года № 26-2. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2017 года № 3648
title:
  rus: О бюджете города и сельских округов Сарысуского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Сарысу ауданының қала және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '158010000002'
version_date:
  kaz: 2018-11-30
  rus: 2018-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/117394/kaz/30.11.2018
  rus: https://zan.gov.kz/client/#!/doc/117394/rus/30.11.2018
caused_by:
  code: '126784'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 30 ноября 2018 года № 41-2. Зарегистрировано Департаментом юстиции Жамбылской области 5 декабря 2018 года № 4006
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 21 декабря 2017 года № 26-2 «О бюджете города и сельских округов Сарысуского района на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Сарысу ауданының қала және ауылдық округтерінің бюджеттері туралы» Сарысу аудандық мәслихатының 2017 жылғы 21 желтоқсандағы №26-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126784/rus
