act_code: '78987'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 18 марта 2014 года № 30-4. Зарегистрировано Департаментом юстиции Жамбылской области 17 апреля 2014 года № 2163. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 19.07.2018 № 28-5
title:
  rus: Об утверждении положения государственного учреждения "Аппарат Жамбылского районного маслихата"
  kaz: '"Жамбыл аудандық мәслихаты аппараты" мемлекеттік мекемесінің ережесін бекіту туралы'
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2014-03-18
approved_by:
- '158004000002'
version_date:
  kaz: 2014-03-18
  rus: 2014-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/78987/kaz/18.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78987/rus/18.03.2014
