act_code: '109227'
requisite: Решение маслихата Жамбылской области от 9 декабря 2016 года № 7-11. Зарегистрировано Департаментом юстиции Жамбылской области 17 января 2017 года № 3284. Утратило силу решением Жамбылского областного маслихата от 11 декабря 2020 года № 52-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в Шуском  районе
  kaz: Шу ауданында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-12-09
approved_by:
- '158000000002'
version_date:
  kaz: 2016-12-09
  rus: 2016-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/109227/kaz/09.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109227/rus/09.12.2016
