act_code: '104812'
requisite: Решение Байзакского районного маслихата Жамбылской области от 22 июня 2016 года № 4-9. Зарегистрировано Департаментом юстиции Жамбылской области 21 июля 2016 года № 3136
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, образования, культуры, спорта являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-22
approved_by:
- '158003000002'
version_date:
  kaz: 2016-06-22
  rus: 2016-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/104812/kaz/22.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104812/rus/22.06.2016
