act_code: '190558'
requisite: Решение Меркенского районного маслихата Жамбылской области от 22 декабря 2023 года № 16-3
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Меркенскому району на 2023 год
  kaz: Меркі ауданы бойынша 2023 жылға кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '158008000002'
version_date:
  kaz: 2023-12-22
  rus: 2023-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/190558/kaz/22.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190558/rus/22.12.2023
