act_code: '44489'
requisite: Решение Кордайского районного маслихата Жамбылской области от 27 января 2009 года № 13-5. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 27 февраля 2009 года № 6-5-74. Утратило силу решением Кордайского районного маслихата Жамбылской области от 4 ноября 2011 года № 42-3
title:
  rus: О ставках фиксированного налога
  kaz: Тіркелген салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-27
approved_by:
- '158006000002'
version_date:
  kaz: 2010-05-18
  rus: 2009-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/44489/kaz/18.05.2010
  rus: https://zan.gov.kz/client/#!/doc/44489/rus/27.01.2009
caused_by:
  code: '53208'
repealed_on: 2011-11-04
repealed_by:
  code: '61621'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 4 ноября 2011 года N 42-3. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 22 ноября 2011 года за номером 6-5-130. Утратило силу решением Кордайского районного маслихата Жамбылской области от 26.03.2018 № 29-8
  title:
    rus: Об установлении единых ставок фиксированного налога
    kaz: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
  link: https://zan.gov.kz/client/#!/doc/61621/rus
