act_code: '44489'
requisite: Решение Кордайского районного маслихата Жамбылской области от 27 января 2009 года № 13-5. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 27 февраля 2009 года № 6-5-74. Утратило силу решением Кордайского районного маслихата Жамбылской области от 4 ноября 2011 года № 42-3
title:
  rus: О ставках фиксированного налога
  kaz: Тіркелген салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-27
approved_by:
- '158006000002'
version_date:
  kaz: 2010-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/44489/kaz/18.05.2010
caused_by:
  code: '53208'
  requisite: Жамбыл облысы Қордай аудандық мәслихатының 2010 жылғы 18 мамырдағы № 27-5 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 18 маусымда 6-5-92 нөмірімен тіркелді
  title:
    rus: '"Тіркелген салық ставкалары туралы" Қордай аудандық мәслихатының 2009 жылғы 27 қаңтардағы № 13-5 шешіміне өзгеріс енгізу туралы'
    kaz: '"Тіркелген салық ставкалары туралы" Қордай аудандық мәслихатының 2009 жылғы 27 қаңтардағы № 13-5 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53208/rus
