act_code: '151177'
requisite: Решение Таразского городского маслихата Жамбылской области от 23 декабря 2020 года № 66-3. Зарегистрировано Департаментом юстиции Жамбылской области 30 декабря 2020 года № 4875
title:
  rus: О городском бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '158002000002'
version_date:
  kaz: 2020-12-23
  rus: 2020-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/151177/kaz/23.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151177/rus/23.12.2020
