act_code: '75271'
requisite: Решение Таразского городского маслихата Жамбылской области от 8 октября 2013 года № 19-7. Зарегистрировано Департаментом юстиции Жамбылской области 8 ноября 2013 года № 2037. Утратило силу решением Таразского городского маслихата Жамбылской области от 18.04.2016 № 2-4
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по городу Тараз
  kaz: Тараз қаласы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-10-08
approved_by:
- '158002000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/75271/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/75271/rus/24.12.2014
caused_by:
  code: '86052'
  requisite: Решение Таразского городского маслихата Жамбылской области от 24 декабря 2014 года № 37-6. Зарегистрировано Департаментом юстиции Жамбылской области 23 января 2015 года № 2477. Утратило силу решением Таразского городского маслихата Жамбылской области от 15.02.2019 № 42-6
  title:
    rus: О внесении изменений и дополнения в решение Таразского городского маслихата от 8 октября 2013 года  №19-7 «Об утверждении Правил  оказания социальной помощи,  установления размеров и определения перечня отдельных категорий  нуждающихся граждан по городу Тараз»
    kaz: «Тараз қаласы бойынша әлеуметтік  көмек көрсетудің, оның мөлшерлерін  белгілеудің және мұқтаж азаматтардың  жекелеген санаттарының тізбесін  айқындаудың Қағидаларын бекіту  туралы» Тараз қаласы мәслихатының  2013 жылғы 8 қазандағы №19-7 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86052/rus
