act_code: '118601'
requisite: Решение акима Биликольского сельского округа Жуалынского района Жамбылской области от 25 января 2018 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 1 февраля 2018 года № 3694
title:
  rus: О переименовании улицы в селе Жылыбулак Биликольского сельского округа
  kaz: Билікөл ауылдық округінің Жылыбұлақ ауылындағы көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-25
approved_by:
- '158005014002'
version_date:
  kaz: 2018-01-25
  rus: 2018-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/118601/kaz/25.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118601/rus/25.01.2018
