act_code: '122780'
requisite: Решение Таласского районного маслихата Жамбылской области от 31 мая 2018 года № 36-3. Зарегистрировано Департаментом юстиции Жамбылской области 13 июня 2018 года № 3859. Утратило силу решением Таласского районного маслихата Жамбылской области от 20 апреля 2020 года № 71-7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального  обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-31
approved_by:
- '158011000002'
version_date:
  kaz: 2018-05-31
  rus: 2018-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/122780/kaz/31.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122780/rus/31.05.2018
