act_code: '96826'
requisite: Решение от 24.12.2015 № 50-3, Маслихат Жуалынского района. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2015 года № 2878
title:
  rus: 'О районном бюджете на 2016 - 2018 годы '
  kaz: '2016 - 2018 жылдарға арналған аудандық бюджет туралы  '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '158005000002'
version_date:
  kaz: 2016-12-06
  rus: 2016-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/96826/kaz/06.12.2016
  rus: https://zan.gov.kz/client/#!/doc/96826/rus/06.12.2016
caused_by:
  code: '108046'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 6 декабря 2016 года № 8-3. Зарегистрировано Департаментом юстиции Жамбылской области 6 декабря 2016 года № 3245
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 24 декабря 2015 года № 50-3 «О районном бюджете на 2016 - 2018 годы»
    kaz: «2016 - 2018 жылдарға арналған аудандық бюджет туралы» Жуалы аудандық мәслихатының 2015 жылғы 24 желтоқсандағы № 50-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108046/rus
