act_code: '90724'
requisite: Решение Таразского городского маслихата Жамбылской области от 30 января 2015 года № 38-5
title:
  rus: О признании утратившим силу решения Таразского городского маслихата №40-5 от 29 июня 2011 года «О льготном проезде»
  kaz: Тараз қалалық мәслихатының 2011 жылғы 29 маусымдағы №40-5  «Жеңілдікпен жол жүру туралы» шешімін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-01-30
approved_by:
- '158002000002'
version_date:
  kaz: 2015-01-30
  rus: 2015-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/90724/kaz/30.01.2015
  rus: https://zan.gov.kz/client/#!/doc/90724/rus/30.01.2015
