act_code: '218327'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 5 декабря 2025 года № 47-3
title:
  rus: Об утверждении Программы по управлению коммунальными отходами в Жамбылском районе Жамбылской области на 2025-2029 гг.
  kaz: 2025-2029 жылдарға арналған Жамбыл облысы Жамбыл ауданындағы коммуналдық қалдықтарды басқару бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-05
approved_by:
- '158004000002'
version_date:
  kaz: 2025-12-05
  rus: 2025-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/218327/kaz/05.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218327/rus/05.12.2025
