act_code: '45657'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2009 жылғы 27 наурыздағы № 19-7 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2009 жылғы 5 мамырда № 6-10-76 тіркелді
title:
  rus: Тіркелген салық ставкалары туралы
  kaz: Тіркелген салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-27
approved_by:
- '158011000002'
version_date:
  kaz: 2009-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/45657/kaz/23.06.2009
caused_by:
  code: '47160'
  requisite: Жамбыл облысы Талас аудандық мәслихатының 2009 жылғы 23 маусымдағы № 21-14 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2009 жылғы 3 тамызда 6-10-82 нөмірімен тіркелді
  title:
    rus: '"Тіркелген салық ставкалары туралы" Талас аудандық мәслихаттың 2009 жылғы 27 наурыздағы № 19-7 шешіміне өзгеріс пен толықтыру енгізу туралы'
    kaz: '"Тіркелген салық ставкалары туралы" Талас аудандық мәслихаттың 2009 жылғы 27 наурыздағы № 19-7 шешіміне өзгеріс пен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47160/rus
