act_code: '50052'
requisite: Жамбыл облысы Шу аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 18-2 шешімі. Жамбыл облысы Шу ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда 6-11-84 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Шу аудандық мәслихатының 2013 жылғы 28 наурыздағы № 13-3 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '158012000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50052/kaz/23.12.2009
