act_code: '50052'
requisite: Жамбыл облысы Шу аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 18-2 шешімі. Жамбыл облысы Шу ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда 6-11-84 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Шу аудандық мәслихатының 2013 жылғы 28 наурыздағы № 13-3 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '158012000002'
version_date:
  kaz: 2010-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/50052/kaz/13.12.2010
caused_by:
  code: '55999'
  requisite: Жамбыл облысы Шу ауданы мәслихатының 2010 жылғы 13 желтоқсандағы № 28-2 шешімі. Жамбыл облысы Шу ауданының Әділет басқармасында 2010 жылғы 15 желтоқсанда 6-11-101 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Шу аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 18-2 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Шу аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 18-2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55999/rus
