act_code: '111882'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 12 апреля 2017 года № 14-5. Зарегистрировано Департаментом юстиции Жамбылской области 28 апреля 2017 года № 3414. Утратило силу решением маслихата района Т.Рыскулова Жамбылской области от 30 октября 2023 года № 10-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по району Т.Рыскулова
  kaz: Т.Рысқұлов ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын  бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-04-12
approved_by:
- '158007000002'
version_date:
  kaz: 2020-04-20
  rus: 2020-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/111882/kaz/20.04.2020
  rus: https://zan.gov.kz/client/#!/doc/111882/rus/20.04.2020
caused_by:
  code: '142293'
  requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 20 апреля 2020 года № 53-11. Зарегистрировано Департаментом юстиции Жамбылской области 28 апреля 2020 года № 4588. Утратило силу решением маслихата района Т.Рыскулова Жамбылской области от 30 октября 2023 года № 10-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение маслихата района Т.Рыскулова от 12 апреля 2017 года № 14-5 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по району Т.Рыскулова»
    kaz: «Т.Рысқұлов ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» Т.Рысқұлов аудандық мәслихатының 2017 жылдың 12 сәуірдегі № 14-5 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142293/rus
