act_code: '43380'
requisite: Жамбыл облысы Т. Рысқұлов ауданы әкімінің 2008 жылғы 11 желтоқсандағы № 78 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда 6-8-72 нөмірімен тіркелді
title:
  rus: 2009 жылы Т. Рысқұлов ауданының аумағында тұратын 1992 жылы туылған еркек жынысты азаматтарды шақыру учаскесіне тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2009 жылы Т. Рысқұлов ауданының аумағында тұратын 1992 жылы туылған еркек жынысты азаматтарды шақыру учаскесіне тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-11
approved_by:
- '158007000003'
version_date:
  kaz: 2008-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/43380/kaz/11.12.2008
