act_code: '101026'
requisite: Решение Таразского городского маслихата Жамбылской области от 11 марта 2016 года №52-8. Зарегистрировано Департаментом юстиции Жамбылской области 7 апреля 2016 года № 3022. Утратило силу решением Таразского городского маслихата Жамбылской области от 14.03.2018 № 29-9
title:
  rus: О повышении ставок единого земельного налога на неиспользуемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге  бірыңғай  жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-11
approved_by:
- '158002000002'
version_date:
  kaz: 2016-03-11
  rus: 2016-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/101026/kaz/11.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101026/rus/11.03.2016
