act_code: '55210'
requisite: Жамбыл облысы Талас ауданы Қасқабұлақ ауылдық округі әкімінің 2010 жылғы 20 қыркүйектегі № 7 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 29 қазанда нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 6-10-110 болып енгізілді
title:
  rus: Талас ауданы Қасқабұлақ ауылының Шығыс жағындағы үшінші көшесіне атауын беру туралы
  kaz: Талас ауданы Қасқабұлақ ауылының Шығыс жағындағы үшінші көшесіне атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-20
approved_by:
- '158011012002'
version_date:
  kaz: 2010-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/55210/kaz/20.09.2010
