act_code: '85002'
requisite: Решение маслихата Жамбылского района Жамбылской области от 3 декабря 2014 года № 37-3. Зарегистрировано Департаментом юстиции Жамбылской области 12 декабря 2014 года № 2426. Утратило силу решением маслихата Жамбылского района Жамбылской области от 19.02.2016 № 50-5
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций на территории Жамбылского района
  kaz: Жамбыл ауданы аумағында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-03
approved_by:
- '158004000002'
version_date:
  kaz: 2014-12-03
  rus: 2014-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/85002/kaz/03.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85002/rus/03.12.2014
