act_code: '204745'
requisite: Решение Кордайского районного маслихата Жамбылской области от 24 декабря 2024 года № 38-4
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '158006000002'
version_date:
  kaz: 2025-12-10
  rus: 2025-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/204745/kaz/10.12.2025
  rus: https://zan.gov.kz/client/#!/doc/204745/rus/10.12.2025
caused_by:
  code: '218669'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 10 декабря 2025 года № 53-2
  title:
    rus: О внесении изменений в решение Кордайского районного маслихата от 24 декабря 2024 года № 38-4 «О районном бюджете на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған аудандық бюджет туралы» Қордай аудандық мәслихатының 2024 жылғы 24 желтоқсандағы № 38-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218669/rus
