act_code: '204745'
requisite: Решение Кордайского районного маслихата Жамбылской области от 24 декабря 2024 года № 38-4
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '158006000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/204745/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204745/rus/24.12.2024
