act_code: '26379'
requisite: Решение Жамбылского областного маслихата от 15 декабря 2005 года № 12-5. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2005 года за № 1631. Утратило силу решением Жамбылского областного маслихата от 15 марта 2011 года № 32-8
title:
  rus: Об утверждении ставки платы за некоторые виды лесных пользований по области
  kaz: Облыс бойынша орман пайдаланудың кейбір түрлері үшін төлем ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-15
approved_by:
- '158000000002'
version_date:
  kaz: 2005-12-15
  rus: 2005-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/26379/kaz/15.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26379/rus/15.12.2005
