act_code: '176314'
requisite: Решение Меркенского районного маслихата Жамбылской области от 28 декабря 2022 года № 40-2
title:
  rus: О бюджете сельских округов Меркенского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Меркі ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '158008000002'
version_date:
  kaz: 2023-07-28
  rus: 2023-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/176314/kaz/28.07.2023
  rus: https://zan.gov.kz/client/#!/doc/176314/rus/28.07.2023
caused_by:
  code: '184572'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 28 июля 2023 года № 6-2
  title:
    rus: О внесении изменений и дополнений в решение Меркенского районного маслихата от 28 декабря 2022 года №40-2 «О бюджете сельских округов Меркенского района на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған Меркі ауданы ауылдық округтерінің бюджеттері туралы» Меркі аудандық мәслихатының 2022 жылғы 28 желтоқсандағы №40-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184572/rus
