act_code: '166233'
requisite: Решение Байзакского районного маслихата Жамбылской области от 30 марта 2022 года № 24-5. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 апреля 2022 года № 27441. Утратило силу решением Байзакского районного маслихата Жамбылской области от 23 августа 2023 года № 7-12 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Байзакском районе
  kaz: Байзақ ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-30
approved_by:
- '158003000002'
version_date:
  kaz: 2022-03-30
  rus: 2022-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/166233/kaz/30.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166233/rus/30.03.2022
