act_code: '93890'
requisite: Решение акима Жанакогамского сельского округа Шуского района Жамбылской области от 4 сентября 2015 года № 35. Зарегистрировано Департаментом юстиции Жамбылской области 18 сентября 2015 года № 2768
title:
  rus: О присвоении наименования новой улице № 5 в селе Коктобе
  kaz: Көктөбе ауылындағы № 5 жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-04
approved_by:
- '158012012001'
version_date:
  kaz: 2015-09-04
  rus: 2015-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/93890/kaz/04.09.2015
  rus: https://zan.gov.kz/client/#!/doc/93890/rus/04.09.2015
