act_code: '183938'
requisite: Решение Кордайского районного маслихата Жамбылской области от 14 июля 2023 года № 6-3
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по Кордайскому району
  kaz: Қордай ауданы бойынша шетелдіктер үшін 2023 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-14
approved_by:
- '158006000002'
version_date:
  kaz: 2023-07-14
  rus: 2023-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/183938/kaz/14.07.2023
  rus: https://zan.gov.kz/client/#!/doc/183938/rus/14.07.2023
