act_code: '172491'
requisite: Решение Кордайского районного маслихата Жамбылской области от 10 декабря 2021 года № 16-9. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2021 года № 25845
title:
  rus: О признании утратившим силу решение Кордайского районного маслихата «Об утверждении Правил управления бесхозяйными  отходами, признанными решением суда поступившими в коммунальную собственность» от 10 ноября 2017 года №22-5
  kaz: Қордай аудандық мәслихатының 2017 жылғы 10 қарашадағы №22-5 "Сот шешімімен коммуналдықменшікке түскен болып танылған иесіз қалдықтарды басқару Қағидаларын бекіту туралы" күші жойылды деп танылған шешімі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-10
approved_by:
- '158006000002'
version_date:
  kaz: 2021-12-10
  rus: 2021-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/172491/kaz/10.12.2021
  rus: https://zan.gov.kz/client/#!/doc/172491/rus/10.12.2021
