act_code: '194982'
requisite: Решение Жамбылского областного маслихата от 28 марта 2024 года № 13-4. Зарегистрированы Департаментом юстиции Жамбылской области 29 марта 2024 года № 5181-08
title:
  rus: О предоставлении бесплатного проезда гражданам Республики Казахстан проживающим в Жамбылской области, за пределы населенного пункта постоянного проживания для получения высокотехнологичных медицинских услуг в рамках гарантированного объема бесплатной медицинской помощи и (или) медицинской помощи в системе обязательного социального медицинского страхования
  kaz: Тегін медициналық көмектің кепілдік берілген көлемі шеңберінде жоғары технологиялық медициналық көрсетілетін қызметтерді және (немесе) міндетті әлеуметтік медициналық сақтандыру жүйесінде медициналық көмекті алу үшін Жамбыл облысында тіркелген Қазақстан Республикасының азаматтарына тұрақты тұратын елді мекеннен тысқары жерлерге тегін жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '158000000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/194982/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194982/rus/28.03.2024
