act_code: '170679'
requisite: Решение Кордайского районного маслихата Жамбылской области от 12 августа 2022 года № 27-7. Отменен решением Кордайского районного маслихата Жамбылской области от 7 сентября 2023 года № 9-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию в разрезе сельских округов по Кордайскому району на 2022-2024 годы
  kaz: Қордай ауданы бойынша ауылдық округтер бөлінісінде жайылымдарды басқару және оларды пайдалану жөніндегі 2022-2024 жылдарға арналған Жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2022-08-12
approved_by:
- '158006000002'
version_date:
  kaz: 2022-08-12
  rus: 2022-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/170679/kaz/12.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170679/rus/12.08.2022
