act_code: '144878'
requisite: Решение Таласского районного маслихата Жамбылской области от 30 июня 2020 года № 75-8. Зарегистрировано Департаментом юстиции Жамбылской области 16 июля 2020 года № 4683. Утратило силу решением Таласского районного маслихата Жамбылской области от 25 февраля 2021 года № 3-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Таласскому району
  kaz: Талас ауданы бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету қағидаларын бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-30
approved_by:
- '158011000002'
version_date:
  kaz: 2020-06-30
  rus: 2020-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/144878/kaz/30.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144878/rus/30.06.2020
