act_code: '124711'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 6 сентября 2018 года № 28-3. Зарегистрировано Департаментом юстиции Жамбылской области 18 сентября 2018 года № 3952. Утратило силу решением Мойынкумского районного маслихата Жамбылской области от 28 августа 2020 года № 64-3 (вводится в действие по истечении десяти календарных дней после дня первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества сельских округов Мойынкумского района
  kaz: Мойынқұм ауданы ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-09-06
approved_by:
- '158009000002'
version_date:
  kaz: 2018-09-06
  rus: 2018-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/124711/kaz/06.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124711/rus/06.09.2018
