act_code: '85088'
requisite: Решение маслихата Жамбылской области от 11 декабря 2014 года № 33-3. Зарегистрировано Департаментом юстиции Жамбылской области 18 декабря 2014 года № 2431
title:
  rus: Об областном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-11
approved_by:
- '158000000002'
version_date:
  kaz: 2015-12-07
  rus: 2015-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/85088/kaz/07.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85088/rus/07.12.2015
caused_by:
  code: '96184'
  requisite: Решение маслихата Жамбылской области от 7 декабря 2015 года № 42-2. Зарегистрировано Департаментом юстиции Жамбылской области 9 декабря 2015 года № 2849
  title:
    rus: О внесении изменений в решение Жамбылского областного маслихата от 11 декабря 2014 года №33-3 «Об областном бюджете на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған облыстық бюджет туралы» Жамбыл облыстық мәслихатының 2014 жылғы 11 желтоқсандағы №33-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96184/rus
