act_code: '195334'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 19 марта 2024 года № 19-4. Зарегистрированы Департаментом юстиции Жамбылской области 5 апреля 2024 года № 5192-08
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Сарысуском районе
  kaz: Сарысу ауданында тұрғын үй көмегін көрсету мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-19
approved_by:
- '158010000002'
version_date:
  kaz: 2024-03-19
  rus: 2024-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/195334/kaz/19.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195334/rus/19.03.2024
