act_code: '52359'
requisite: Жамбыл облысы Т. Рысқұлов ауданы әкімдігі Луговой ауыл аймағы әкімінің 2010 жылғы 9 сәуірдегі № 6 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2010 жылғы 7 мамырда 6-8-101 нөмірімен тіркелді
title:
  rus: Каменка селосындағы Новая көшесінің атауын өзгерту туралы
  kaz: Каменка селосындағы Новая көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-09
approved_by:
- '158007011002'
version_date:
  kaz: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/52359/kaz/09.04.2010
