act_code: '198080'
requisite: Решение акима Жалгизтюбинского сельского округа Байзакского района Жамбылской области от 21 июня 2024 года № 23. Утратило силу решением акима Жалгизтюбинского сельского округа Байзакского района Жамбылской области от 7 октября 2025 года № 49 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О переименовании некоторых составных частей села Жетибай Жалгизтюбинского сельского округа Байзакского района
  kaz: Байзақ ауданы Жалғызтөбе ауылдық округі Жетібай ауылының кейбір құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-21
approved_by:
- '158003005002'
version_date:
  kaz: 2024-06-21
  rus: 2024-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/198080/kaz/21.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198080/rus/21.06.2024
