act_code: '65602'
requisite: Решение акима Карасайского сельского округа Кордайского района от 16 апреля 2012 года № 14. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 15 мая 2012 года за номером 6-5-143
title:
  rus: О присвоении наименования "Кыргау" первой улице расположенной с восточной стороны села Карасай
  kaz: Қарасай ауылының шығыс жағында орналасқан бірінші көшесіне "Қырғау" атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-16
approved_by:
- '158006015002'
version_date:
  kaz: 2012-04-16
  rus: 2012-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/65602/kaz/16.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65602/rus/16.04.2012
