act_code: '107548'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 21 октября 2016 года № 7-4. Зарегистрировано Департаментом юстиции Жамбылской области 16 ноября 2016 года № 3214. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 28 февраля 2022 года № 20-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Жуалынском районе
  kaz: Жуалы ауданында мүгедек қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-21
approved_by:
- '158005000002'
version_date:
  kaz: 2020-11-03
  rus: 2020-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/107548/kaz/03.11.2020
  rus: https://zan.gov.kz/client/#!/doc/107548/rus/03.11.2020
caused_by:
  code: '148205'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 3 ноября 2020 года № 73-4. Зарегистрировано Департаментом юстиции Жамбылской области 5 ноября 2020 года № 4791. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 28 февраля 2022 года № 20-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата Жуалынского района от 21 октября 2016 года № 7-4 «Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Жуалынском районе»
    kaz: Жуалы аудандық мәслихатының 2016 жылғы 21 қазандағы «Жуалы ауданында мүгедек қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы» № 7-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148205/rus
