act_code: '85431'
requisite: Решение от 24.12.2014 №36-3, Маслихат Байзакского района
title:
  rus: О районном бюджете на 2015 – 2017 годы
  kaz: 2015 – 2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '158003000002'
version_date:
  kaz: 2015-03-18
  rus: 2015-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/85431/kaz/18.03.2015
  rus: https://zan.gov.kz/client/#!/doc/85431/rus/18.03.2015
caused_by:
  code: '87826'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 18 марта 2015 года №37-10. Зарегистрировано Департаментом юстиции Жамбылской области 27 марта 2015 года № 2590
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата от 24 декабря 2014 года № 36-3 «О районном бюджете на 2015 – 2017 годы»
    kaz: «2015 – 2017 жылдарға арналған  аудандық бюджет туралы» Байзақ аудандық мәслихатының 2014 жылғы 24 желтоқсандағы №36-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87826/rus
