act_code: '92361'
requisite: Решение от 25.06.2015 № 38-9, Маслихат Жамбылской области. Утратило силу решением маслихата Жамбылской области от 14.12.2015 № 43-38
title:
  rus: 'Об утверждении правил застройки территорий Жамбылской области '
  kaz: 'Жамбыл облысы аумағында құрылыс салу қағидаларын бекіту туралы '
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-06-25
approved_by:
- '158000000002'
version_date:
  kaz: 2015-06-25
  rus: 2015-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/92361/kaz/25.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92361/rus/25.06.2015
