act_code: '83418'
requisite: Решение акима Каратауского селького округа Таласского района Жамбылской области от 4 сентября 2014 года № 13. Зарегистрировано Департаментом юстиции Жамбылской области 2 октября 2014 года № 2329
title:
  rus: Об установлении ветеринарного режима с введением ограничительных мероприятий на территории села Есейхан Каратауского сельского округа Таласского района
  kaz: Талас ауданы Қаратау ауылдық округіндегі Есейхан ауылының аумағына шектеу іс-шараларын енгізе отырып ветеринариялық режим белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-04
approved_by:
- '158011013001'
version_date:
  kaz: 2014-09-04
  rus: 2014-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/83418/kaz/04.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83418/rus/04.09.2014
