act_code: '25685'
requisite: Жамбыл облысы Жамбыл ауданының мәслихатының 2005 жылғы 26 қазандағы № 18-2 шешімі. Жамбыл ауданының Әділет басқармасында 2005 жылғы 28 қазанда № 6-3-15 тіркелді. Күші жойылды - Жамбыл облысы Жамбыл аудандық мәслихатының 02.03.2017 № 9-6 шешімімен
title:
  rus: Ауданның елді мекендерін көріктендіру, жасыл желекті тәртіпте ұстау мен қорғаудың Ережесін бекіту туралы
  kaz: Ауданның елді мекендерін көріктендіру, жасыл желекті тәртіпте ұстау мен қорғаудың Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2005-10-26
approved_by:
- '158004000002'
version_date:
  kaz: 2005-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/25685/kaz/26.10.2005
