act_code: '136109'
requisite: Решение Жамбылского областного маслихата от 12 ноября 2019 года № 40-3. Зарегистрировано Департаментом юстиции Жамбылской области 15 ноября 2019 года № 4401
title:
  rus: Об утверждении Правил присвоения звания «Почетный гражданин Жамбылской области (города, района)»
  kaz: «Жамбыл облысының (қаланың, ауданның) Құрметті азаматы» атағын беру Қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-11-12
approved_by:
- '158000000002'
version_date:
  kaz: 2023-05-31
  rus: 2023-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/136109/kaz/31.05.2023
  rus: https://zan.gov.kz/client/#!/doc/136109/rus/31.05.2023
caused_by:
  code: '182391'
  requisite: Решение Жамбылского областного маслихата от 31 мая 2023 года № 3-3. Зарегистрировано Департаментом юстиции Жамбылской области 1 июня 2023 года № 5033
  title:
    rus: О внесении изменений в решение Жамбылского областного маслихата от 12 ноября 2019 года № 40-3 «Об утверждении Правил присвоения звания «Почетный гражданин Жамбылской области (города, района)»
    kaz: «Жамбыл облысының (қаланың, ауданның) Құрметті азаматы» атағын беру Қағидалары туралы» Жамбыл облыстық мәслихатының 2019 жылғы 12 қарашадағы № 40-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182391/rus
