act_code: '78211'
requisite: Решение Байзакского районного маслихата Жамбылской области от 7 марта 2014 года № 26-2. Зарегистрировано Департаментом юстиции Жамбылской области 26 марта 2014 года № 2137. Утратило силу решением Байзакского районного маслихата Жамбылской области от 24 июня 2020 года № 67-10 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) Байзакского района
  kaz: Байзақ ауданы бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-07
approved_by:
- '158003000002'
version_date:
  kaz: 2014-03-07
  rus: 2014-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/78211/kaz/07.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78211/rus/07.03.2014
