act_code: '63072'
requisite: Решение акимата Меркенского района Жамбылской области от 24 января 2012 года № 1. Зарегистрировано Меркенским Управлением юстиции Жамбылской области 1 февраля 2012 года за № 6-6-102
title:
  rus: Об организации приписки в 2012 году к призывному участку граждан мужского пола 1995 года рождения, проживающие на территории Меркенского района
  kaz: 2012 жылы Меркі ауданының аумағында тұратын 1995 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-24
approved_by:
- '158008000001'
version_date:
  kaz: 2012-01-24
  rus: 2012-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/63072/kaz/24.01.2012
  rus: https://zan.gov.kz/client/#!/doc/63072/rus/24.01.2012
