act_code: '144337'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 30 июня 2020 года № 77-3. Зарегистрировано Департаментом юстиции Жамбылской области 1 июля 2020 года № 4664
title:
  rus: Об установлении порядка использования специальных мест, специальных мест для организации и проведения мирных собраний, норм их предельного наполнения, а также требований к материально-техническому и организационному обеспечению в Сарысуском районе
  kaz: Сарысу ауданында бейбіт жиналыстарды ұйымдастыру және өткізуге арналған арнайы орындар, арнайы орындарды пайдалану тәртібі, олардың шекті толу нормалары, сондай-ақ материалдық-техникалық және ұйымдастырушылықты қамтамасыз етуге қойылатын талаптарды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-30
approved_by:
- '158010000002'
version_date:
  kaz: 2024-02-26
  rus: 2024-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/144337/kaz/26.02.2024
  rus: https://zan.gov.kz/client/#!/doc/144337/rus/26.02.2024
caused_by:
  code: '194240'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 26 февраля 2024 года № 18-7. Зарегистрировано Департаментом юстиции Жамбылской области от 11 марта 2024 года № 5166-08
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 30 июня 2020 года № 77-3 «Об установлении порядка использования специальных мест, специальных мест для организации и проведения мирных собраний, норм их предельного наполнения, а также требований к материально-техническому и организационному обеспечению в Сарысуском районе»
    kaz: «Сарысу ауданында бейбіт жиналыстарды ұйымдастыру және өткізуге арналған арнайы орындар, арнайы орындарды пайдалану тәртібі, олардың шекті толу нормалары, сондай-ақ материалдық-техникалық және ұйымдастырушылықты қамтамасыз етуге қойылатын талаптарды белгілеу туралы» Сарысу аудандық мәслихатының 2020 жылғы 30 маусымдағы №77-3 шешiмiне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194240/rus
