act_code: '122315'
requisite: Решение акима Жамбылского сельского округа Меркенского района Жамбылской области от 21 мая 2018 года № 37. Зарегистрировано Департаментом юстиции Жамбылской области 5 июня 2018 года № 3850
title:
  rus: О переименований улицы МТФ села Жамбыл Жамбылского сельского округа
  kaz: Жамбыл ауылдық округі Жамбыл ауылындағы МТФ көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-21
approved_by:
- '158008002002'
version_date:
  kaz: 2018-05-21
  rus: 2018-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/122315/kaz/21.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122315/rus/21.05.2018
