act_code: '47084'
requisite: Жамбыл облысы Жамбыл ауданы Қаратөбе ауылдық округі әкімінің 2009 жылғы 29 маусымдағы № 10 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 30 шілдеде 6-3-85 нөмірімен тіркелді
title:
  rus: Бектөбе ауылындағы Жаңа-2 көшесінің атауын өзгерту туралы
  kaz: Бектөбе ауылындағы Жаңа-2 көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-29
approved_by:
- '158004013002'
version_date:
  kaz: 2009-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/47084/kaz/29.06.2009
