act_code: '220443'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 26 декабря 2025 года № 59-2
title:
  rus: О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '158005000002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/220443/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220443/rus/26.12.2025
