act_code: '220443'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 26 декабря 2025 года № 59-2
title:
  rus: О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '158005000002'
version_date:
  kaz: 2026-06-04
  rus: 2026-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/220443/kaz/04.06.2026
  rus: https://zan.gov.kz/client/#!/doc/220443/rus/04.06.2026
caused_by:
  code: '226256'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 4 июня 2026 года № 68-2
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 26 декабря 2025 года № 59-2 «О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2026-2028 годы»
    kaz: Жуалы аудандық мәслихатының 2025 жылғы 26 желтоқсандағы № 59-2 «2026-2028 жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/226256/rus
