act_code: '168157'
requisite: Решение Жамбылского областного маслихата от 12 мая 2022 года № 17-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 мая 2022 года № 28233
title:
  rus: Об установлении специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта,  ветеринарии, лесного хозяйства и особо охраняемых природных территорий, являющимся гражданскими служащими и работающим в сельских населенных пунктах, а также указанным специалистам, работающим в государственных организациях, финансируемых из областного бюджета, повышенных на двадцать пять процентов окладов и тарифных ставок по сравнению со ставками специалистов, занимающимися этими видами деятельности в городских условиях
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық елді мекендерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт, ветеринария, орман шаруашылығы және ерекше қорғалатын табиғи аумақтар саласындағы мамандарға, сондай-ақ облыстық бюджеттен қаржыландырылатын мемлекеттік ұйымдарда жұмыс істейтін аталған мамандарға қызметтің осы түрлерімен қалалық жағдайда айналысатын мамандардың мөлшерлемелерімен салыстырғанда жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-12
approved_by:
- '158000000002'
version_date:
  kaz: 2022-05-12
  rus: 2022-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/168157/kaz/12.05.2022
  rus: https://zan.gov.kz/client/#!/doc/168157/rus/12.05.2022
