act_code: '204969'
requisite: Решение Таласского районного маслихата Жамбылской области от 6 декабря 2024 года № 31-3. Зарегистрировано Департаментом юстиции Жамбылской области 18 декабря 2024 года № 5250-08
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Таласскому району
  kaz: Талас ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-06
approved_by:
- '158011000002'
version_date:
  kaz: 2024-12-06
  rus: 2024-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/204969/kaz/06.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204969/rus/06.12.2024
