act_code: '138379'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 30 декабря 2019 года № 58-2. Зарегистрировано Департаментом юстиции Жамбылской области 13 января 2020 года № 4494
title:
  rus: О бюджетах сельских округов и села Б. Момышулы Жуалынского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Жуалы ауданы Б. Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '158005000002'
version_date:
  kaz: 2020-07-07
  rus: 2020-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/138379/kaz/07.07.2020
  rus: https://zan.gov.kz/client/#!/doc/138379/rus/07.07.2020
caused_by:
  code: '144662'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 7 июля 2020 года № 68-2. Зарегистрировано Департаментом юстиции Жамбылской области 10 июля 2020 года № 4679
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 30 декабря 2019 года № 58-2 «О бюджетах сельских округов и села Б. Момышулы Жуалынского района на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Жуалы ауданы Б. Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы» Жуалы аудандық мәслихатының 2019 жылғы 30 желтоқсандағы № 58-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144662/rus
