act_code: '50189'
requisite: Жамбыл облысы Байзақ ауданы Жаңатұрмыс ауылдық округі әкімінің 2009 жылғы 15 желтоқсандағы № 55 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 22 қаңтарда 6-2-104 нөмірімен тіркелді
title:
  rus: Ақшолақ ауылындағы жаңа көшеге атау беру туралы
  kaz: Ақшолақ ауылындағы жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-15
approved_by:
- '158003006002'
version_date:
  kaz: 2009-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/50189/kaz/15.12.2009
