act_code: '122159'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 18 мая 2018 года № 26-14. Зарегистрировано Департаментом юстиции Жамбылской области 25 мая 2018 года № 3837. Утратило силу решением маслихата района Т. Рыскулова Жамбылской области от 21 июля 2023 года № 5-5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата района Т. Рыскулова
  kaz: Т. Рысқұлов аудандық мәслихат аппараты «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-18
approved_by:
- '158007000002'
version_date:
  kaz: 2018-05-18
  rus: 2018-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/122159/kaz/18.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122159/rus/18.05.2018
