act_code: '56682'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 24 декабря 2010 года № 35-3. Зарегистрировано Департаментом юстиции Жамбылской области 11 января 2011 года за № 6-4-97. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 15 мая 2012 года № 5-6
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158005000002'
version_date:
  kaz: 2010-12-24
  rus: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56682/kaz/24.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56682/rus/24.12.2010
