act_code: '52579'
requisite: Жамбыл облысы Жамбыл ауданы Қаракемер ауылдық округі әкімінің 2010 жылғы 20 сәуірдегі № 6 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 19 мамырда 6-3-117 нөмірімен тіркелді
title:
  rus: Қаракемер ауылындағы Жеңіс көшесінің атауын өзгерту туралы
  kaz: Қаракемер ауылындағы Жеңіс көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-20
approved_by:
- '158004011002'
version_date:
  kaz: 2010-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/52579/kaz/20.04.2010
