act_code: '43505'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 16-7 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2009 жылғы 15 қаңтарда 6-10-71 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '158011000002'
version_date:
  kaz: 2009-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/43505/kaz/03.12.2009
caused_by:
  code: '49400'
  requisite: Жамбыл облысы Талас аудандық мәслихатының 2009 жылғы 3 желтоқсандағы № 26-2 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2009 жылғы 22 желтоқсанда 6-10-90 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Талас аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 16-7 шешіміне өзгерістер енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Талас аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 16-7 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/49400/rus
