act_code: '137665'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 20 декабря 2019 года № 66-2. Зарегистрировано Департаментом юстиции Жамбылской области 27 декабря 2019 года № 4475
title:
  rus: О районном бюджете на 2020 - 2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-20
approved_by:
- '158010000002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/137665/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/137665/rus/24.06.2020
caused_by:
  code: '144128'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 24 июня 2020 года № 76-8. Зарегистрировано Департаментом юстиции Жамбылской области 25 июня 2020 года № 4638
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 20 декабря 2019 года № 66-2 «О районном бюджете на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған аудандық бюджет туралы» Сарысу аудандық мәслихатының 2019 жылғы 20 желтоқсандағы № 66-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144128/rus
