act_code: '62379'
requisite: Решение акима Жетитобинского сельского округа Жуалынского района Жамбылской области от 23 ноября 2011 года № 21. Зарегистрировано Управлением юстиции Жуалынского района Жамбылской области 30 декабря 2011 года № 6-4-118
title:
  rus: О наименовании улиц по Жетитобинскому сельскому округу Жуалынского района
  kaz: Жуалы ауданы Жетітөбе ауылдық округі бойынша көшелеріне ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-23
approved_by:
- '158005004002'
version_date:
  kaz: 2011-11-23
  rus: 2011-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/62379/kaz/23.11.2011
  rus: https://zan.gov.kz/client/#!/doc/62379/rus/23.11.2011
