act_code: '96432'
requisite: Решение от 23.11.2015 №39-3, Маслихат Мойынкумского района. Зарегистрировано Департаментом юстиции Жамбылской области 14 декабря 2015 года № 2863. Утратило силу решением маслихата Мойынкумского района Жамбылской области от 01.03.2016 № 45-3
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының  мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарлату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-23
approved_by:
- '158009000002'
version_date:
  kaz: 2015-11-23
  rus: 2015-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/96432/kaz/23.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96432/rus/23.11.2015
