act_code: '53974'
requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2010 жылғы 14 шілдедегі № 30-20 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2010 жылғы 12 тамызда 6-4-93 нөмірімен тіркелді
title:
  rus: Жуалы ауданы елді мекендерінің аумақтарын көріктендіру ережесін бекіту туралы
  kaz: Жуалы ауданы елді мекендерінің аумақтарын көріктендіру ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-14
approved_by:
- '158005000002'
version_date:
  kaz: 2010-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/53974/kaz/14.07.2010
