act_code: '228540'
requisite: Решение маслихата Жамбылской области от 30 июля 2026 года № 35-3
title:
  rus: Об определении размеров и перечня категорий получателей жилищных сертификатов по Жамбылской области
  kaz: Жамбыл облысы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санатының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-30
approved_by:
- '158000000002'
version_date:
  kaz: 2026-07-30
  rus: 2026-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/228540/kaz/30.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228540/rus/30.07.2026
