act_code: '115844'
requisite: Решение Байзакского районного маслихата Жамбылской области от 23 октября 2017 года № 19-12. Зарегистрировано Департаментом юстиции Жамбылской области 3 ноября 2017 года № 3572. Утратило силу решением Байзакского районного маслихата Жамбылской области от 23 декабря 2020 года № 77-11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Байзакскому району
  kaz: «Байзақ ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-10-23
approved_by:
- '158003000002'
version_date:
  kaz: 2019-06-14
  rus: 2019-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/115844/kaz/14.06.2019
  rus: https://zan.gov.kz/client/#!/doc/115844/rus/14.06.2019
caused_by:
  code: '132676'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 14 июня 2019 года № 48-3. Зарегистрировано Департаментом юстиции Жамбылской области 19 июня 2019 года № 4265. Утратило силу решением Байзакского районного маслихата Жамбылской области от 23 декабря 2020 года № 77-11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата от 23 октября 2017 года № 19-12 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Байзакскому району»
    kaz: «Байзақ ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекеленген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» Байзақ аудандық мәслихатының 2017 жылғы 23 қазандағы № 19-12 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132676/rus
