act_code: '48075'
requisite: Жамбыл облысы Жамбыл ауданы Полатқосшы селолық округі әкімінің 2009 жылғы 1 қазандағы № 30 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 5 қазанда 6-3-98 нөмірімен тіркелді
title:
  rus: Жалпақтөбе ауылындағы Новостройка-2 көшесінің атауын өзгерту туралы
  kaz: Жалпақтөбе ауылындағы Новостройка-2 көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-01
approved_by:
- '158004017001'
version_date:
  kaz: 2009-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/48075/kaz/01.10.2009
