act_code: '56101'
requisite: Решение Жамбылского областного маслихата от 13 декабря 2010 года № 30-3. Зарегистрировано Департаментом юстиции Жамбылской области 22 декабря 2010 года № 1766
title:
  rus: Об областном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '158000000002'
version_date:
  kaz: 2011-04-14
  rus: 2011-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56101/kaz/14.04.2011
  rus: https://zan.gov.kz/client/#!/doc/56101/rus/14.04.2011
caused_by:
  code: '58333'
  requisite: Решение Жамбылского областного маслихата от 14 апреля 2011 года № 34-2. Зарегистрировано Департаментом юстиции Жамбылской области 18 апреля 2011 года за номером 1773. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
  title:
    rus: О внесении изменений в решение Жамбылского областного маслихата "Об областном бюджете на 2011-2013 годы" от 13 декабря 2010 года № 30-3
    kaz: '"2011-2013 жылдарға арналған облыстық бюджет туралы" Жамбыл облыстық мәслихатының 2010 жылғы 13 желтоқсандағы № 30-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58333/rus
