act_code: '228544'
requisite: Решение маслихата Жамбылской области от 30 июля 2026 года № 35-10
title:
  rus: Об утверждении Регламента Жамбылского областного маслихата
  kaz: Жамбыл облыстық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-30
approved_by:
- '158000000002'
version_date:
  kaz: 2026-07-30
  rus: 2026-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/228544/kaz/30.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228544/rus/30.07.2026
