act_code: '85087'
requisite: Решение акима Какпатасского сельского округа Жамбылской области от 2 декабря 2014 года № 15. Зарегистрировано Департаментом юстиции Жамбылской области 18 декабря 2014 года № 2433
title:
  rus: О присвоении наименования новой улице
  kaz: О присвоении наименования новой улице
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-02
approved_by:
- '158006006001'
version_date:
  kaz: 2014-12-02
  rus: 2014-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/85087/kaz/02.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85087/rus/02.12.2014
