act_code: '154489'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 30 марта 2021 года № 3-3. Зарегистрировано Департаментом юстиции Жамбылской области 9 апреля 2021 года № 4933. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 6 декабря 2023 года № 11-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Жамбылскому району
  kaz: Жамбыл ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2021-03-30
approved_by:
- '158004000002'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/154489/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/154489/rus/25.11.2022
caused_by:
  code: '174963'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 25 ноября 2022 года № 25-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 декабря 2022 года № 31003. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 6 декабря 2023 года № 11-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 30 марта 2021 года №3-3 «Об утверждении Правил оказания социальной помощи, установления  размеров и определения перечня отдельных категорий нуждающихся граждан по Жамбылскому району»
    kaz: Жамбыл аудандық мәслихатының 2021 жылғы 30 наурыздағы №3-3 «Жамбыл ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174963/rus
