act_code: '84429'
requisite: Решение акима Сарыбулакского сельского округа Кордайского района Жамбылской области от 3 ноября 2014 года № 29. Зарегистрировано Департаментом юстиции Жамбылской области 17 ноября 2014 года № 2372
title:
  rus: О присвоении наименования новой улице № 3 в селе Сарыбулак
  kaz: Сарыбұлақ ауылындағы № 3 жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-03
approved_by:
- '158006007001'
version_date:
  kaz: 2014-11-03
  rus: 2014-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/84429/kaz/03.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84429/rus/03.11.2014
