act_code: '79080'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 28 марта 2014 года № 23-6. Зарегистрировано Департаментом юстиции Жамбылской области 21 апреля 2014 года № 2171. Утратило силу решением маслихата района Т.Рыскулова Жамбылской области от 21 июля 2023 года № 5-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента маслихата района Т.Рыскулова
  kaz: Т.Рысқұлов аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-28
approved_by:
- '158007000002'
version_date:
  kaz: 2014-03-28
  rus: 2014-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/79080/kaz/28.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79080/rus/28.03.2014
