act_code: '118205'
requisite: Решение акима Актюбинского сельского округа Жуалынского района Жамбылской области от 3 января 2018 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 16 января 2018 года № 3677
title:
  rus: О переименовании улицы в селе Куркуреусу Актюбинского сельского округа
  kaz: Ақтөбе ауылдық округінің Күркүреусу ауылындағы көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-03
approved_by:
- '158005013002'
version_date:
  kaz: 2018-01-03
  rus: 2018-01-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/118205/kaz/03.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118205/rus/03.01.2018
