act_code: '162559'
requisite: Решение Таразского городского маслихата Жамбылской области от 24 декабря 2021 года № 10-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26217
title:
  rus: О городском бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '158002000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162559/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162559/rus/24.12.2021
