act_code: '44488'
requisite: Решение Кордайского районного маслихата Жамбылской области от 27 января 2009 года № 13-4. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 26 февраля 2009 года № 6-5-73. Утратило силу решением Кордайского районного маслихата Жамбылской области от 24 декабря 2010 года № 34-18
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Кордайскому району
  kaz: Қордай ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-27
approved_by:
- '158006000002'
version_date:
  kaz: 2010-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/44488/kaz/05.08.2010
caused_by:
  code: '54251'
  requisite: Жамбыл облысы Қордай аудандық мәслихатының 2010 жылғы 5 тамыздағы № 29-4 шешімі. Жамбыл облысы Қордай ауданының әділет басқармасында 2010 жылғы 1 қыркүйекте 6-5-101 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Қордай аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 34-18 шешімімен
  title:
    rus: '"Қордай ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Ережелерін бекіту туралы" Қордай аудандық мәслихатының 2009 жылғы 27 қаңтардағы № 13-4 шешіміне өзгерістер енгізу туралы'
    kaz: '"Қордай ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Ережелерін бекіту туралы" Қордай аудандық мәслихатының 2009 жылғы 27 қаңтардағы № 13-4 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54251/rus
