act_code: '53551'
requisite: Жамбыл облысы Жамбыл аудандық мәслихатының 2010 жылғы 18 маусымдағы № 31-2 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 16 шілдеде № 6-3-121 тіркелді. Күші жойылды - Жамбыл облысы Жамбыл аудандық мәслихатының 2012 жылғы 15 маусымдағы № 7-3 шешімімен
title:
  rus: Жамбыл ауданы елді мекендерінің аумақтарын көріктендіру және жасыл желектерді күтіп ұстау мен қорғау Ережелерін бекіту туралы
  kaz: Жамбыл ауданы елді мекендерінің аумақтарын көріктендіру және жасыл желектерді күтіп ұстау мен қорғау Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-18
approved_by:
- '158004000002'
version_date:
  kaz: 2010-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/53551/kaz/18.06.2010
