act_code: '117135'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 14 декабря 2017 года № 21-4. Зарегистрировано Департаментом юстиции Жамбылской области 20 декабря 2017 года № 3632
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-14
approved_by:
- '158007000002'
version_date:
  kaz: 2018-05-18
  rus: 2018-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/117135/kaz/18.05.2018
  rus: https://zan.gov.kz/client/#!/doc/117135/rus/18.05.2018
caused_by:
  code: '122009'
  requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 18 мая 2018 года № 26-6. Зарегистрировано Департаментом юстиции Жамбылской области 22 мая 2018 года № 3822
  title:
    rus: О внесении изменений в решение маслихата района Т. Рыскулова от 14 декабря 2017 года № 21-4 «О районном бюджете на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған аудандық бюджет туралы» Т. Рысқұлов аудандық мәслихатының 2017 жылдың 14 желтоқсандағы № 21-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122009/rus
