act_code: '187932'
requisite: Решение Байзакского районного маслихата Жамбылской области от 27 октября 2023 года № 10-3. Зарегистрировано Департаментом юстиции Жамбылской области от 3 ноября 2023 года № 5109. Утратило силу решением Байзакского районного маслихата Жамбылской области от 26 декабря 2025 года № 58-5 (вводится в действие с 01.01.2026).
title:
  rus: О понижении размера ставки специального налогового режима розничного налога по Байзакскому району
  kaz: Байзақ ауданы бойынша бөлшек салықтың арнаулы салық режимінің мөлшерлемесін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-27
approved_by:
- '158003000002'
version_date:
  kaz: 2023-10-27
  rus: 2023-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/187932/kaz/27.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187932/rus/27.10.2023
