act_code: '58840'
requisite: Решение акима аула Бауыржан Момышулы Жуалынского района Жамбылской области от 28 апреля 2011 года № 51. Зарегистрировано Управлением юстиции Жуалынского района Жамбылской области 12 мая 2011 года за № 6-4-103
title:
  rus: О переименовании улиц аула Б.Момышулы Жуалынского района
  kaz: Жуалы ауданы Б.Момышұлы ауылыны қарасты көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-28
approved_by:
- '158005009002'
version_date:
  kaz: 2011-04-28
  rus: 2011-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/58840/kaz/28.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58840/rus/28.04.2011
