act_code: '122857'
requisite: Решение акима Жамбылского сельского округа Кордайского района Жамбылской области от 29 мая 2018 года № 38. Зарегистрировано Департаментом юстиции Жамбылской области 14 июня 2018 года № 3865
title:
  rus: О переименовании улиц села Жамбыл Жамбылского сельского округа
  kaz: Жамбыл ауылдық округінің Жамбыл ауылындағы көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-29
approved_by:
- '158006004002'
version_date:
  kaz: 2018-05-29
  rus: 2018-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/122857/kaz/29.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122857/rus/29.05.2018
