act_code: '83979'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 29 сентября 2014 года № 35-7. Зарегистрировано Департаментом юстиции Жамбылской области 30 октября 2014 года № 2354.  Утратило силу решением маслихата Сарысуского района Жамбылской области от 18.02.2016 № 58-5
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций на территории Сарысуского района
  kaz: Сарысу ауданы аумағында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-29
approved_by:
- '158010000002'
version_date:
  kaz: 2014-09-29
  rus: 2014-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/83979/kaz/29.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83979/rus/29.09.2014
