act_code: '96181'
requisite: Решение Шуского районного маслихата Жамбылской области от 4 ноября 2015 года № 45-2. Зарегистрировано Департаментом юстиции Жамбылской области 8 декабря 2015 года № 2845. Утратило силу решением Шуского районного маслихата Жамбылской области от 14.08.2017 № 16-3
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-04
approved_by:
- '158012000002'
version_date:
  kaz: 2016-02-18
  rus: 2016-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/96181/kaz/18.02.2016
  rus: https://zan.gov.kz/client/#!/doc/96181/rus/18.02.2016
caused_by:
  code: '100390'
  requisite: Решение Шуского районного маслихата Жамбылской области от 18 февраля 2016 года № 50-5. Зарегистрировано Департаментом юстиции Жамбылской области 17 марта 2016 года № 2993. Утратило силу решением Шуского районного маслихата Жамбылской области от 14.08.2017 № 16-3
  title:
    rus: О внесении изменений в решение Шуского районного маслихата от 4 ноября 2015 года «О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения»
    kaz: «Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы» Шу аудандық  мәслихатының 2015 жылғы 4 қарашадағы № 45-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100390/rus
