act_code: '190018'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 6 декабря 2023 года № 11-3. Зарегистрировано Департаментом юстиции Жамбылской области 12 декабря 2023 года № 5128. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 27 мая 2026 года № 57-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Жамбылскому району
  kaz: Жамбыл ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-06
approved_by:
- '158004000002'
version_date:
  kaz: 2024-09-13
  rus: 2024-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/190018/kaz/13.09.2024
  rus: https://zan.gov.kz/client/#!/doc/190018/rus/13.09.2024
caused_by:
  code: '201925'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 13 сентября 2024 года № 27-3. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 27 мая 2026 года № 57-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 6 декабря 2023 года № 11-3 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Жамбылскому району»
    kaz: Жамбыл аудандық мәслихатының 2023 жылғы 6 желтоқсандағы № 11-3 «Жамбыл ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201925/rus
