act_code: '190018'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 6 декабря 2023 года № 11-3. Зарегистрировано Департаментом юстиции Жамбылской области 12 декабря 2023 года № 5128. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 27 мая 2026 года № 57-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Жамбылскому району
  kaz: Жамбыл ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-06
approved_by:
- '158004000002'
version_date:
  kaz: 2023-12-06
  rus: 2023-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/190018/kaz/06.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190018/rus/06.12.2023
