act_code: '56099'
requisite: Жамбыл облысы Т.Рысқұлов аудандық мәслихатының 2010 жылғы 15 қарашадағы № 29-10 шешімі. Жамбыл облысы Т.Рысқұлов ауданының Әділет басқармасында 2010 жылғы 15 желтоқсанда 6-8-114 нөмірімен тіркелді
title:
  rus: Т.Рысқұлов ауданы бойынша жер салығының базалық салық ставкаларының мөлшерін бекіту туралы
  kaz: Т.Рысқұлов ауданы бойынша жер салығының базалық салық ставкаларының мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-15
approved_by:
- '158007000002'
version_date:
  kaz: 2010-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/56099/kaz/15.11.2010
