act_code: '53087'
requisite: Решение Таразского городского маслихата Жамбылской области от 14 мая 2010 года № 29-5. Зарегистрировано Управлением юстиции города Тараз Жамбылской области 16 июня 2010 года за номером 6-1-106. Утратило силу решением Таразского городского маслихата Жамбылской области от 14 декабря 2011 года № 45-5
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по городу Тараз
  kaz: Тараз қаласы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегiн көрсету Ережелерiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-14
approved_by:
- '158002000002'
version_date:
  kaz: 2010-05-14
  rus: 2010-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/53087/kaz/14.05.2010
  rus: https://zan.gov.kz/client/#!/doc/53087/rus/14.05.2010
