act_code: '56857'
requisite: Решение акима Отарского сельского округа Кордайского района Жамбылской области от 9 декабря 2010 года № 44. Зарегистрировано Кордайским Управлением юстиции 14 января 2011 года за № 6-5-118
title:
  rus: О присвоении безымянной улице села Отар наименования Береке
  kaz: Отар ауылындағы атауы жоқ көшеге Береке атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-09
approved_by:
- '158006011002'
version_date:
  kaz: 2010-12-09
  rus: 2010-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56857/kaz/09.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56857/rus/09.12.2010
