act_code: '61860'
requisite: Решение акима Аксайского сельского округа Жуалынского района Жамбылской области от 7 ноября 2011 года № 26. Зарегистрировано Управлением юстиции Жуалынского района Жамбылской области 7 декабря 2011 года за № 6-4-114
title:
  rus: О наименовании улиц по Аксайскому сельскому округу Жуалынского района
  kaz: Жуалы ауданы Ақсай ауылдық округі бойынша көшелеріне ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-07
approved_by:
- '158005008002'
version_date:
  kaz: 2011-11-07
  rus: 2011-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/61860/kaz/07.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61860/rus/07.11.2011
