act_code: '96000'
requisite: Решение маслихата Кордайского района Жамбылской области от 28 октября 2015 года № 45-3. Зарегистрировано Департаментом юстиции Жамбылской области 20 ноября 2015 года № 2823. Утратило силу решением Кордайского районного маслихата Жамбылской области от 25 декабря 2020 года № 80-5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарлату  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-28
approved_by:
- '158006000002'
version_date:
  kaz: 2015-10-28
  rus: 2015-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/96000/kaz/28.10.2015
  rus: https://zan.gov.kz/client/#!/doc/96000/rus/28.10.2015
