act_code: '53649'
requisite: Жамбыл облысы Қордай ауданы Қақпатас ауылдық округі әкімінің 2010 жылғы 15 маусымдағы № 18 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 21 шілдеде 6-5-96 нөмірімен тіркелді
title:
  rus: Қақпатас ауылындағы көше атын өзгерту туралы
  kaz: Қақпатас ауылындағы көше атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-15
approved_by:
- '158006006002'
version_date:
  kaz: 2010-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/53649/kaz/15.06.2010
