act_code: '117528'
requisite: Решение Кордайского районного маслихата Жамбылской области от 26 декабря 2017 года № 26-2. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2017 года № 3661
title:
  rus: О бюджете сельских округов на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-26
approved_by:
- '158006000002'
version_date:
  kaz: 2018-12-10
  rus: 2018-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/117528/kaz/10.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117528/rus/10.12.2018
caused_by:
  code: '127030'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 10 декабря 2018 года № 40-2. Зарегистрировано Департаментом юстиции Жамбылской области 10 декабря 2018 года № 4017
  title:
    rus: О внесении изменений в решение Кордайского районного маслихата от 26 декабря 2017 года № 26-2 «О бюджете сельских округов на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған ауылдық округтердің бюджеттері туралы» Қордай аудандық мәслихатының 2017 жылғы 26 желтоқсандағы № 26-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127030/rus
