act_code: '75698'
requisite: Решение Кордайского районного маслихата Жамбылской области от 13 ноября 2013 года № 23-5. Зарегистрировано Департаментом юстиции Жамбылской области 5 декабря 2013 года № 2059. Утратило силу решением Кордайского районного маслихата Жамбылской области от 27 января 2014 года № 26-4
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Кордайскому району
  kaz: Қордай ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-11-13
approved_by:
- '158006000002'
version_date:
  kaz: 2013-11-13
  rus: 2013-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/75698/kaz/13.11.2013
  rus: https://zan.gov.kz/client/#!/doc/75698/rus/13.11.2013
