act_code: '123605'
requisite: Решение Шуского районного маслихата Жамбылской области от 21 июня 2018 года № 29-4. Зарегистрировано Департаментом юстиции Жамбылской области 11 июля 2018 года № 3898. Утратило силу решением Шуского районного маслихата Жамбылской области от 17 ноября 2021 года № 16-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества города Шу и сельских округов Шуского района
  kaz: Шу ауданының Шу қаласы және ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-06-21
approved_by:
- '158012000002'
version_date:
  kaz: 2018-06-21
  rus: 2018-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/123605/kaz/21.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123605/rus/21.06.2018
