act_code: '198082'
requisite: Решение акима Туймекентского сельского округа Байзакского района Жамбылской области от 21 июня 2024 года № 26
title:
  rus: О переименовании улицы села Туймекент Туймекентского сельского округа Байзакского района
  kaz: Байзақ ауданы Түймекент ауылдық округінің Түймекент ауылының көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-21
approved_by:
- '158003015002'
version_date:
  kaz: 2024-06-21
  rus: 2024-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/198082/kaz/21.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198082/rus/21.06.2024
