act_code: '118908'
requisite: Решение Жамбылского областного маслихата от 25 января 2018 года № 20-8. Зарегистрировано Департаментом юстиции Жамбылской области 15 февраля 2018 года № 3704. Утратило силу решением Жамбылского областного маслихата от 11 декабря 2020 года № 52-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в Мойынкумском районе
  kaz: Мойынкум ауданында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-25
approved_by:
- '158000000002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/118908/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/118908/rus/12.12.2019
caused_by:
  code: '137099'
  requisite: Решение Жамбылского областного маслихата от 12 декабря 2019 года № 41-14. Зарегистрировано Департаментом юстиции Жамбылской области 18 декабря 2019 года № 4447. Утратило силу решением Жамбылского областного маслихата от 11 декабря 2020 года № 52-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Жамбылского областного маслихата от 25 января 2018 года № 20-8 «Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в Мойынкумском районе»
    kaz: «Мойынқұм ауданында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту туралы» Жамбыл облыстық маслихатының 2018 жылғы 25 қаңтардағы № 20-8 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137099/rus
