act_code: '76228'
requisite: Решение Таразского городского маслихата Жамбылской области от 25 декабря 2013 года № 22-3. Зарегистрировано Департаментом юстиции Жамбылской области 27 декабря 2013 года № 2083
title:
  rus: О городском бюджете на 2014 - 2016 годы
  kaz: 2014-2016 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '158002000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/76228/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76228/rus/25.12.2013
