act_code: '186361'
requisite: Решение Таразского городского маслихата Жамбылской области от 15 сентября 2023 года № 7-5. Зарегистрировано Департаментом юстиции Жамбылской области от 21 сентября 2023 года № 5083
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в городе Тараз
  kaz: Тараз қаласында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-15
approved_by:
- '158002000002'
version_date:
  kaz: 2023-09-15
  rus: 2023-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/186361/kaz/15.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186361/rus/15.09.2023
