act_code: '129971'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 20 февраля 2019 года № 38-3. Зарегистрировано Департаментом юстиции Жамбылской области 25 февраля 2019 года № 4122. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 30 марта 2021 года № 3-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Жамбылскому району
  kaz: Жамбыл ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-02-20
approved_by:
- '158004000002'
version_date:
  kaz: 2019-07-03
  rus: 2019-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/129971/kaz/03.07.2019
  rus: https://zan.gov.kz/client/#!/doc/129971/rus/03.07.2019
caused_by:
  code: '133798'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 3 июля 2019 года № 45-2. Зарегистрировано Департаментом юстиции Жамбылской области 10 июля 2019 года № 4272
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 20 февраля 2019 года №38-3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Жамбылскому району
    kaz: «Жамбыл ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген  санаттарының тізбесін айқындаудың Қағидаларын бекiту туралы» Жамбыл аудандық мәслихатының 2019 жылғы 20 ақпандағы №38-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133798/rus
