act_code: '195115'
requisite: Решение Байзакского районного маслихата Жамбылской области от 29 марта 2024 года № 29-4. Зарегистрированы Департаментом юстиции Жамбылской области 2 апреля 2024 года № 5184-08
title:
  rus: О понижении размера ставки специального налогового режима розничного налога по Байзакскому району на 2024 год
  kaz: 2024 жылға Байзақ ауданы бойынша бөлшек салықтың арнаулы салық режимінің мөлшерлемесін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '158003000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195115/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195115/rus/29.03.2024
