act_code: '27361'
requisite: Решение Таразского городского маслихата Жамбылской области от 30 марта 2006 года № 20-7. Зарегистрировано Управлением юстиции г.Тараз Жамбылской области 18 апреля 2006 года за № 6-1-27. Утратило силу решением Таразского городского маслихата Жамбылской области от 30 сентября 2010 года № 33-20
title:
  rus: Об установлении ставок стоимости разовых талонов
  kaz: Бір жолғы талондар құнының ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-30
approved_by:
- '158002000002'
version_date:
  kaz: 2010-06-25
  rus: 2010-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/27361/kaz/25.06.2010
  rus: https://zan.gov.kz/client/#!/doc/27361/rus/25.06.2010
