act_code: '38658'
requisite: Решение Жамбылского областного маслихата от 8 февраля 2008 года № 4-3. Зарегистрировано Департаментом юстиции Жамбылской области 6 марта 2008 года за номером 1675. Утратило силу решением маслихата Жамбылской области от 29 октября 2009 года № 16-19
title:
  rus: О ставках платы за эмиссии в окружающую среду на 2008 год по Жамбылской области
  kaz: Жамбыл облысы бойынша 2008 жылға арналған қоршаған ортаға эмиссиялар үшін төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-08
approved_by:
- '158000000002'
version_date:
  kaz: 2008-02-08
  rus: 2008-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/38658/kaz/08.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38658/rus/08.02.2008
