act_code: '49987'
requisite: Решение Кордайского районного маслихата Жамбылской области от 25 декабря 2009 года № 23-3. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 15 января 2010 года за № 6-5-85. Утратило силу решением Кордайского районного маслихата Жамбылской области от 28 марта 2013 года № 14-13
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158006000002'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49987/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49987/rus/25.12.2009
