act_code: '49987'
requisite: Решение Кордайского районного маслихата Жамбылской области от 25 декабря 2009 года № 23-3. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 15 января 2010 года за № 6-5-85. Утратило силу решением Кордайского районного маслихата Жамбылской области от 28 марта 2013 года № 14-13
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158006000002'
version_date:
  kaz: 2010-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/49987/kaz/18.05.2010
caused_by:
  code: '52720'
  requisite: Жамбыл облысы Қордай аудандық мәслихатының 2010 жылғы 18 мамырдағы № 27-3 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 25 мамырда 6-5-90 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қордай аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 23-3 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қордай аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 23-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/52720/rus
