act_code: '128424'
requisite: Решение Байзакского районного маслихата Жамбылской области от 28 декабря 2018 года № 39-2. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2018 года № 4079
title:
  rus: О бюджете сельских округов Байзакского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Байзақ ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '158003000002'
version_date:
  kaz: 2019-06-26
  rus: 2019-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128424/kaz/26.06.2019
  rus: https://zan.gov.kz/client/#!/doc/128424/rus/26.06.2019
caused_by:
  code: '133180'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 26 июня 2019 года № 49-6. Зарегистрировано Департаментом юстиции Жамбылской области 12 июля 2019 года № 4273
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата от 28 декабря 2018 года № 39-2 «О бюджете сельских округов Байзакского района на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған Байзақ ауданы ауылдық округтерінің бюджеттері туралы» Байзақ аудандық мәслихатының 2018 жылғы 28 желтоқсандағы № 39-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133180/rus
