act_code: '128312'
requisite: Решение акима Темирбекского сельского округа Байзакского района Жамбылской области от 7 декабря 2018 года № 20. Зарегистрировано Департаментом юстиции Жамбылской области 19 декабря 2018 года № 4041
title:
  rus: О переименовании улиц в селах Тегистик и Сарыбарак Темирбекского сельского округа
  kaz: Темірбек ауылдық округінің Тегістік және Сарыбарақ ауылдарындағы көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-07
approved_by:
- '158003014002'
version_date:
  kaz: 2018-12-07
  rus: 2018-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/128312/kaz/07.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128312/rus/07.12.2018
