act_code: '11460'
requisite: Решение Жамбылского областного маслихата 8 февраля 2002 года № 12-14. Зарегистрировано управлением юстиции Жамбылской области 25 февраля 2002 года за № 522. Утратило силу решением Жамбылского областного маслихата от 29 октября 2009 года № 16-20
title:
  rus: Об утверждении ставок платы за размещение наружной (визуальной) рекламы
  kaz: Сыртқы (көрнекі) жарнамаларды орналастырғаны үшін төлемақылардың ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-02-08
approved_by:
- '158000000002'
version_date:
  kaz: 2002-02-08
  rus: 2002-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/11460/kaz/08.02.2002
  rus: https://zan.gov.kz/client/#!/doc/11460/rus/08.02.2002
