act_code: '121003'
requisite: Решение Кордайского районного маслихата Жамбылской области от 26 марта 2018 года № 29-9. Зарегистрировано Департаментом юстиции Жамбылской области 12 апреля 2018 года № 3787. Утратило силу решением Кордайского районного маслихата Жамбылской области от 25 декабря 2020 года № 80-5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Кордайскому району
  kaz: Қордай ауданы бойынша әлеуметтiк көмек  көрсетудің, оның мөлшерлерiн белгiлеудің және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-26
approved_by:
- '158006000002'
version_date:
  kaz: 2019-04-05
  rus: 2019-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/121003/kaz/05.04.2019
  rus: https://zan.gov.kz/client/#!/doc/121003/rus/05.04.2019
caused_by:
  code: '130838'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 5 апреля 2019 года № 48-3. Зарегистрировано Департаментом юстиции Жамбылской области 9 апреля 2019 года № 4190. Утратило силу решением Кордайского районного маслихата Жамбылской области от 25 декабря 2020 года № 80-5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнения и изменения в решение Кордайского районного маслихата от 26 марта 2018 года № 29-9 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Кордайскому району»
    kaz: «Қордай ауданы бойынша әлеуметтiк көмек көрсетудің, оның мөлшерлерiн белгiлеудің және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың Қағидаларын бекіту туралы» Қордай аудандық мәслихатының 2018 жылғы 26 наурыздағы № 29-9 шешіміне толықтыру мен өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130838/rus
