act_code: '123598'
requisite: Решение акима Жалгызтюбинского сельского округа Байзакского района Жамбылской области от 27 июня 2018 года № 9. Зарегистрировано Департаментом юстиции Жамбылской области 11 июля 2018 года № 3892
title:
  rus: О переименовании улицы села Торткул
  kaz: Төрткүл ауылындағы көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-27
approved_by:
- '158003005002'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/123598/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123598/rus/27.06.2018
