act_code: '76321'
requisite: Решение Шуского районного маслихата Жамбылской области от 25 декабря 2013 года № 24-2. Зарегистрировано Департаментом юстиции Жамбылской области 27 декабря 2013 года № 2088
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '158012000002'
version_date:
  kaz: 2014-12-04
  rus: 2014-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/76321/kaz/04.12.2014
  rus: https://zan.gov.kz/client/#!/doc/76321/rus/04.12.2014
caused_by:
  code: '84786'
  requisite: Решение маслихата Шуского района Жамбылской области от 4 декабря 2014 года № 34-2. Зарегистрировано Департаментом юстиции Жамбылской области 5 декабря 2014 года № 2410
  title:
    rus: О внесении изменений в решение Шуского районного маслихата от 25 декабря 2013 года № 24-2 "О районном бюджете на 2014-2016 годы"
    kaz: О внесении изменений в решение Шуского районного маслихата от 25 декабря 2013 года № 24-2 "О районном бюджете на 2014-2016 годы"
  link: https://zan.gov.kz/client/#!/doc/84786/rus
