act_code: '134273'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 26 июля 2019 года № 49-3. Зарегистрировано Департаментом юстиции Жамбылской области 29 июля 2019 года № 4301. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 11 декабря 2023 года № 12-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правила проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы, многоквартирного жилого дома  для участия в сходе местного сообщества в Жуалынском районе
  kaz: Жуалы ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-07-26
approved_by:
- '158005000002'
version_date:
  kaz: 2022-03-31
  rus: 2022-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/134273/kaz/31.03.2022
  rus: https://zan.gov.kz/client/#!/doc/134273/rus/31.03.2022
caused_by:
  code: '178073'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 31 марта 2022 года № 21-7. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 28 декабря 2023 года № 15-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 26 июля 2019 года № 49-3 «Об утверждении Правила проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Жуалынском районе»
    kaz: «Жуалы ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің сандық құрамын бекіту туралы» Жуалы аудандық мәслихатының 2019 жылғы 26 шілдедегі №49-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178073/rus
