act_code: '128341'
requisite: Решение акима Жайылминского сельского округа Сарысуского района Жамбылской области от 26 декабря 2018 года № 41. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2018 года № 4086
title:
  rus: О переименовании улиц «Гараж» села Жайылма и «Коминтерн» села Маятас Жайылминского сельского округа
  kaz: Жайылма ауылдық округінің Жайылма ауылындағы «Гараж» және Маятас ауылындағы «Коминтерн» көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '158010009002'
version_date:
  kaz: 2018-12-26
  rus: 2018-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128341/kaz/26.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128341/rus/26.12.2018
