act_code: '194837'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 18 марта 2024 года № 18-7. Зарегистрированы Департаментом юстиции Жамбылской области 27 марта 2024 года № 5179-08
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по Жуалынскому району
  kaz: Жуалы ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-18
approved_by:
- '158005000002'
version_date:
  kaz: 2026-05-08
  rus: 2026-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/194837/kaz/08.05.2026
  rus: https://zan.gov.kz/client/#!/doc/194837/rus/08.05.2026
caused_by:
  code: '226788'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 8 мая 2026 года № 66-4. Зарегистрировано в Министерстве юстиции Республики Казахстан от 19 июня 2026 года № 39014
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 18 марта 2024 года № 18-7 «Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по Жуалынскому району»
    kaz: «Жуалы ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» Жуалы аудандық мәслихатының 2024 жылғы 18 наурыздағы № 18-7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/226788/rus
