act_code: '52552'
requisite: Жамбыл облысы Меркі ауданы Ақтоған ауылдық округі әкімінің 2010 жылғы 24 сәуірдегі № 1-03/6 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 17 мамырда № 6-6-79 тіркелді
title:
  rus: Ақтоған ауылдық округі Қазақ-Дихан ауылындағы Ленин көшесінің атын өзгерту туралы
  kaz: Ақтоған ауылдық округі Қазақ-Дихан ауылындағы Ленин көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-24
approved_by:
- '158008005002'
version_date:
  kaz: 2010-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/52552/kaz/24.04.2010
