act_code: '125507'
requisite: Решение Таразского городского маслихата Жамбылской области от 8 октября 2018 года № 36-6. Зарегистрировано Департаментом юстиции Жамбылской области 29 октября 2018 года № 3974. Утратило силу решением Таразского городского маслихата Жамбылской области от 23 февраля 2024 года № 13-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-08
approved_by:
- '158002000002'
version_date:
  kaz: 2018-10-08
  rus: 2018-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/125507/kaz/08.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125507/rus/08.10.2018
