act_code: '52517'
requisite: Жамбыл облысы Меркі ауданы Жамбыл ауылдық округі әкімінің 2010 жылғы 23 сәуірдегі № 32 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 17 мамырда 6-6-78 нөмірімен тіркелді
title:
  rus: Жамбыл ауылдық округі Жеміс-жидек ауылындағы Мира көшесінің атын өзгерту туралы
  kaz: Жамбыл ауылдық округі Жеміс-жидек ауылындағы Мира көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-23
approved_by:
- '158008002002'
version_date:
  kaz: 2010-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/52517/kaz/23.04.2010
