act_code: '86861'
requisite: Решение акима Алгинского сельского округа Шуского района Жамбылской области от 19 января 2015 года №4. Зарегистрировано Департаментом юстиции Жамбылской области 17 февраля 2015 года № 2530
title:
  rus: О  наименовании новых улиц сел Алга и Кайрата Рыскулбекова  Алгинского сельского округа
  kaz: Алға селолық округіне қарасты Алға және Қайрат Рысқұлбеков ауылдарының жаңа көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-01-19
approved_by:
- '158012004001'
version_date:
  kaz: 2015-01-19
  rus: 2015-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/86861/kaz/19.01.2015
  rus: https://zan.gov.kz/client/#!/doc/86861/rus/19.01.2015
