act_code: '118647'
requisite: Решение Жамбылского областного маслихата от 25 января 2018 года № 20-6. Зарегистрировано Департаментом юстиции Жамбылской области 6 февраля 2018 года № 3696. Утратило силу решением Жамбылского областного маслихата от 14 декабря 2022 года № 23-9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении перечня социально значимых сообщений по Сарысускому району
  kaz: Сарысу ауданы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2018-01-25
approved_by:
- '158000000002'
version_date:
  kaz: 2018-01-25
  rus: 2018-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/118647/kaz/25.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118647/rus/25.01.2018
