act_code: '66779'
requisite: Решение Меркенского районного маслихата Жамбылской области от 9 июля 2012 года № 6-3. Зарегистрировано Меркенским Управлением юстиции от 23 июля 2012 года № 6-6-112
title:
  rus: О предоставлении социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии прибывшим для работы и проживания в сельские населенные пункты Меркенского района на 2012 год
  kaz: 2012 жылға арналған Меркі ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-09
approved_by:
- '158008000002'
version_date:
  kaz: 2012-07-09
  rus: 2012-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/66779/kaz/09.07.2012
  rus: https://zan.gov.kz/client/#!/doc/66779/rus/09.07.2012
