act_code: '117389'
requisite: Решение Таласского районного маслихата Жамбылской области от 20 декабря 2017 года № 27-2. Зарегистрировано Департаментом юстиции Жамбылской области 21 декабря 2017 года № 3638
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018 – 2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '158011000002'
version_date:
  kaz: 2018-08-07
  rus: 2018-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/117389/kaz/07.08.2018
  rus: https://zan.gov.kz/client/#!/doc/117389/rus/07.08.2018
caused_by:
  code: '124153'
  requisite: Решение Таласского районного маслихата Жамбылской области от 7 августа 2018 года № 39-2. Зарегистрировано Департаментом юстиции Жамбылской области 9 августа 2018 года № 3927
  title:
    rus: О внесений изменений в решение Таласского районного маслихата от 20 декабря 2017 года №27-2 «О районном бюджете на 2018-2020 годы»
    kaz: «2018 -2020 жылдарға арналған аудандық бюджет туралы» Талас аудандық мәслихатының 2017 жылғы 20 желтоқсандағы №27-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124153/rus
