act_code: '52419'
requisite: Жамбыл облысы Қордай ауданы Ноғайбай ауылдық округі әкімінің 2010 жылғы 9 сәуірдегі № 5 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 12 мамырда 6-5-89 нөмірімен тіркелді
title:
  rus: Ноғайбай ауылындағы көше атын өзгерту туралы
  kaz: Ноғайбай ауылындағы көше атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-09
approved_by:
- '158006008002'
version_date:
  kaz: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/52419/kaz/09.04.2010
