act_code: '38550'
requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2008 жылғы 26 ақпандағы № 4-5 шешімі. Жамбыл облысы Т. Рысқұлов ауданының әділет басқармасында 2008 жылғы 27 наурызда 6-8-56 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Т.Рысқұлов аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 30-15 шешімімен
title:
  rus: Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Тәртібін бекіту туралы
  kaz: Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-26
approved_by:
- '158007000002'
version_date:
  kaz: 2010-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/38550/kaz/15.11.2010
caused_by:
  code: '56069'
  requisite: Жамбыл облысы Т.Рысқұлов аудандық мәслихатының 2010 жылғы 15 қарашадағы № 29-5 шешімі. Жамбыл облысы Т.Рысқұлов ауданының Әділет басқармасында 2010 жылғы 15 желтоқсанда 6-8-112 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Т.Рысқұлов аудандық мәслихатының 2023 жылғы 21 шілдедегі № 5-6 (алғашқы ресми жарияланған күнінен кейін күнтізбелік  он күн өткен соң қолданысқа енгізіледі) шешімімен
  title:
    rus: '"Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Тәртібін бекіту туралы" Т.Рысқұлов аудандық мәслихаттың 2008 жылдың 26 ақпандағы № 4-5 шешіміне өзгерістер енгізу туралы'
    kaz: '"Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Тәртібін бекіту туралы" Т.Рысқұлов аудандық мәслихаттың 2008 жылдың 26 ақпандағы № 4-5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56069/rus
