act_code: '14663'
requisite: Решение Акима Жамбылской области от 24 декабря 2002 года N 220. Зарегистрировано Управлением юстиции Жамбылской области 25 февраля 2003 года за N 851. Утратило силу решением акима Жамбылской области от 23 октября 2015 года № 2
title:
  rus: О нормах потребления природного газа на приготовление пищи и подогрев воды для хозяйственно-бытовых нужд
  kaz: Тамақ дайындауға және шаруашылық-тұрмыстық қажеттілік үшін су жылытуға табиғи газды тұтыну мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-24
approved_by:
- '158000000001'
version_date:
  kaz: 2002-12-24
  rus: 2002-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/14663/kaz/24.12.2002
  rus: https://zan.gov.kz/client/#!/doc/14663/rus/24.12.2002
