act_code: '60912'
requisite: Решение Жамбылского областного маслихата от 22 сентября 2011 года № 39-9. Зарегистрировано Департаментом юстиции Жамбылской области 21 октября 2011 года № 1796. Утратило силу решением Жамбылского областного маслихата от 06.10.2017 № 15-8
title:
  rus: Об утверждении Правил забора воды из поверхностных и подземных водных объектов при нецентрализованном питьевом и хозяйственно-бытовом водоснабжении населения Жамбылской области
  kaz: Жамбыл облысының халқын орталықтандырылмаған ауыз сумен және шаруашылық-тұрмыстық сумен жабдықтау кезінде жер үсті және жер асты су объектілерінен су алу Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-22
approved_by:
- '158000000002'
version_date:
  kaz: 2011-09-22
  rus: 2011-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/60912/kaz/22.09.2011
  rus: https://zan.gov.kz/client/#!/doc/60912/rus/22.09.2011
