act_code: '43350'
requisite: Жамбыл облысы Байзақ аудандық мәслихатының 2008 жылғы 29 желтоқсандағы № 14-4 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда 6-2-86 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-29
approved_by:
- '158003000002'
version_date:
  kaz: 2009-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/43350/kaz/30.07.2009
caused_by:
  code: '47410'
  requisite: Жамбыл облысы Байзақ аудандық мәслихатының 2009 жылғы 30 шілдедегі № 20-2 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2009 жылғы 20 тамызда 6-2-95 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Байзақ аудандық Мәслихатының 2008 жылғы 29 желтоқсандағы № 14-4 шешіміне өзгерістер енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Байзақ аудандық Мәслихатының 2008 жылғы 29 желтоқсандағы № 14-4 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47410/rus
