act_code: '127583'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 19 декабря 2018 года № 34-3. Зарегистрировано Департаментом юстиции Жамбылской области 21 декабря 2018 года № 4049
title:
  rus: О районном бюджете на 2019 - 2021 годы
  kaz: «2019 – 2021 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-19
approved_by:
- '158009000002'
version_date:
  kaz: 2019-03-28
  rus: 2019-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/127583/kaz/28.03.2019
  rus: https://zan.gov.kz/client/#!/doc/127583/rus/28.03.2019
caused_by:
  code: '130709'
  requisite: Решение Мойынкумского районного маслихата Жамбылской области от 28 марта 2019 года № 38-3. Зарегистрировано Департаментом юстиции Жамбылской области 1 апреля 2019 года № 4168
  title:
    rus: О внесении изменений и дополнение в решение Мойынкумского районного маслихата от 19 декабря 2018 года №34-3 «О районном бюджете на 2019 - 2021 годы»
    kaz: «2019 – 2021 жылдарға арналған аудандық бюджет туралы» Мойынқұм аудандық мәслихатының 2018 жылғы 19 желтоқсандағы №34-3 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130709/rus
