act_code: '78795'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 12 марта 2014 года № 26-10. Зарегистрировано Департаментом юстиции Жамбылской области 11 апреля 2014 года № 2155. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 15 июня 2020 года № 75-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Сарысускому району
  kaz: Сарысу ауданы бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын ұй көмегін көрсету Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-12
approved_by:
- '158010000002'
version_date:
  kaz: 2017-04-05
  rus: 2017-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/78795/kaz/05.04.2017
  rus: https://zan.gov.kz/client/#!/doc/78795/rus/05.04.2017
caused_by:
  code: '111330'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 5 апреля 2017 года № 14-10. Зарегистрировано Департаментом юстиции Жамбылской области 13 апреля 2017 года № 3382. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 6 апреля 2022 года № 20-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 12 марта 2014 года № 26-10 «Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Сарысускому району»
    kaz: «Сарысу ауданы бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Қағидаларын бекіту туралы» Сарысу аудандық мәслихатының 2014 жылғы 12 наурыздағы № 26-10 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111330/rus
