act_code: '43249'
requisite: Жамбыл облысы Жамбыл ауданы мәслихатының 2008 жылғы 26 желтоқсандағы № 16/5 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 5 қаңтарда 6-3-75 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '158004000002'
version_date:
  kaz: 2009-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43249/kaz/24.02.2009
caused_by:
  code: '44752'
  requisite: Жамбыл облысы Жамбыл аудандық мәслихатының 2009 жылғы 24 ақпандағы № 18/3 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 11 наурызда 6-3-78 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Жамбыл аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 16/5 шешіміне өзгерістер енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Жамбыл аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 16/5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/44752/rus
