act_code: '43249'
requisite: Жамбыл облысы Жамбыл ауданы мәслихатының 2008 жылғы 26 желтоқсандағы № 16/5 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 5 қаңтарда 6-3-75 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '158004000002'
version_date:
  kaz: 2009-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/43249/kaz/29.04.2009
caused_by:
  code: '45934'
  requisite: Жамбыл облысы Жамбыл ауданы мәслихатының 2009 жылғы 29 сәуірдегі № 20/2 шешімі. Жамбыл облысы Жамбыл ауданының әділет басқармасында 2009 жылғы 15 мамырда 6-3-82 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Жамбыл аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 16/5 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Жамбыл аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 16/5 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45934/rus
