act_code: '216796'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 3 ноября 2025 года № 42-13
title:
  rus: Об утверждении программы управления коммунальными отходами Мойынкумского района на 2025 – 2029 годы
  kaz: Мойынқұм ауданының коммуналдық қалдықтарды басқарудың 2025 – 2029 жылдарға арналған бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-03
approved_by:
- '158009000002'
version_date:
  kaz: 2025-11-03
  rus: 2025-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/216796/kaz/03.11.2025
  rus: https://zan.gov.kz/client/#!/doc/216796/rus/03.11.2025
