act_code: '203449'
requisite: Решение Таразского городского маслихата Жамбылской области от 22 ноября 2024 года № 22-2. Зарегистрировано Департаментом юстиции Жамбылской области 28 ноября 2024 года № 5246-08
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в городе Тараз
  kaz: Тараз қаласында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-22
approved_by:
- '158002000002'
version_date:
  kaz: 2024-11-22
  rus: 2024-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/203449/kaz/22.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203449/rus/22.11.2024
