act_code: '79691'
requisite: Решение маслихата Сарысуского района Жамбылской области от 17 апреля 2014 года № 27-2. Зарегистрировано Департаментом юстиции Жамбылской области 12 мая 2014 года № 2216. Утратило силу решением маслихата Сарысуского района Жамбылской области от 29 октября 2014 года № 36-4
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии прибывшим для работы и проживания в сельские населенные пункты района в 2014 году
  kaz: 2014 жылы ауданның ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-17
approved_by:
- '158010000002'
version_date:
  kaz: 2014-04-17
  rus: 2014-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/79691/kaz/17.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79691/rus/17.04.2014
