act_code: '50003'
requisite: Решение маслихата Жамбылского района Жамбылской области от 24 декабря 2009 года №26-3. Зарегистрировано Управлением юстиции Жамбылского района Жамбылской области от 14 января 2010 года № 6-3-105
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '158004000002'
version_date:
  kaz: 2010-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/50003/kaz/30.03.2010
caused_by:
  code: '51680'
  requisite: Жамбыл облысы Жамбыл аудандық мәслихатының 2010 жылғы 30 наурыздағы № 28-2 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 9 сәуірде 6-3-110 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Жамбыл аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 26-3 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Жамбыл аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 26-3 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/51680/rus
