act_code: '103599'
requisite: Решение Байзакского районного маслихата Жамбылской области от 17 мая 2016 года №2-3. Зарегистрировано Департаментом юстиции Жамбылской области 16 июня 2016 года № 3110. Утратило силу решением Байзакского районного маслихата Жамбылской области от 26 февраля 2024 года № 18-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және біріңғай жер салығының мөлшерлемелерін жоғарлату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-17
approved_by:
- '158003000002'
version_date:
  kaz: 2016-05-17
  rus: 2016-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/103599/kaz/17.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103599/rus/17.05.2016
