act_code: '205304'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 25 декабря 2024 года № 35-3
title:
  rus: «О районном бюджете на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '158005000002'
version_date:
  kaz: 2025-09-15
  rus: 2025-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/205304/kaz/15.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205304/rus/15.09.2025
caused_by:
  code: '214405'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 15 сентября 2025 года № 50-2
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 25 декабря 2024 года № 35-3 «О районном бюджете на 2025-2027 годы"
    kaz: Жуалы аудандық мәслихатының 2024 жылғы 25 желтоқсандағы «2025-2027 жылдарға арналған аудандық бюджет туралы» № 35-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214405/rus
