act_code: '97583'
requisite: Решение Таразского городского маслихата Жамбылской области от 23 декабря 2015 года № 48-7. Зарегистрировано Департаментом юстиции Жамбылской области 15 января 2016 года № 2900. Отменено решением Таразского городского маслихата Жамбылской области от 17.02.2016 № 50-6
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: 'Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '158002000002'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/97583/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97583/rus/23.12.2015
