act_code: '137673'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 27 декабря 2019 года № 58-2. Зарегистрировано Департаментом юстиции Жамбылской области 30 декабря 2019 года № 4481
title:
  rus: О бюджете сельских округов Жамбылского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Жамбыл ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '158004000002'
version_date:
  kaz: 2020-10-30
  rus: 2020-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/137673/kaz/30.10.2020
  rus: https://zan.gov.kz/client/#!/doc/137673/rus/30.10.2020
caused_by:
  code: '148296'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 30 октября 2020 года № 71-2. Зарегистрировано Департаментом юстиции Жамбылской области 9 ноября 2020 года № 4794
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 27 декабря 2019 года №58-2 «О бюджете сельских округов Жамбылского района на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Жамбыл ауданы ауылдық округтерінің бюджеттері туралы» Жамбыл аудандық мәслихатының 2019 жылғы 27 желтоқсандағы №58-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148296/rus
