act_code: '219270'
requisite: Решение маслихата Жамбылской области от 25 сентября 2025 года № 26-7
title:
  rus: Об утверждении Правил общего водопользования в Жамбылской области
  kaz: Жамбыл облысында ортақ су пайдалану қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-25
approved_by:
- '158000000002'
version_date:
  kaz: 2025-09-25
  rus: 2025-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/219270/kaz/25.09.2025
  rus: https://zan.gov.kz/client/#!/doc/219270/rus/25.09.2025
