act_code: '127200'
requisite: Решение акима Таласского района Жамбылской области от 13 декабря 2018 года № 22. Зарегистрировано Департаментом юстиции Жамбылской области 14 декабря 2018 года № 4030. Утратило силу решением акима Таласского района Жамбылской области от 15 июля 2024 года № 02-03 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін кұру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-13
approved_by:
- '158011000003'
version_date:
  kaz: 2018-12-13
  rus: 2018-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/127200/kaz/13.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127200/rus/13.12.2018
