act_code: '195333'
requisite: Решение Байзакского районного маслихата Жамбылской области от 29 марта 2024 года № 22-5. Зарегистрированы Департаментом юстиции Жамбылской области 5 апреля 2024 года № 5193-08
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Байзакском районе
  kaz: Байзақ ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '158003000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195333/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195333/rus/29.03.2024
