act_code: '67140'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 23 июля 2012 года № 6-8. Зарегистрировано Мойынкумским управлением юстиции 16 августа 2012 года за № 6-7-85. Утратило силу решением Мойынкумского районного маслихата Жамбылской области от 26 мая 2020 года № 59-5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Мойынкумскому району
  kaz: Мойынқұм ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-07-23
approved_by:
- '158009000002'
version_date:
  kaz: 2012-07-23
  rus: 2012-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/67140/kaz/23.07.2012
  rus: https://zan.gov.kz/client/#!/doc/67140/rus/23.07.2012
