act_code: '128191'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 21 декабря 2018 года № 43-2. Зарегистрировано Департаментом юстиции Жамбылской области 28 декабря 2018 года № 4072
title:
  rus: О районном бюджете на 2019 - 2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '158010000002'
version_date:
  kaz: 2019-05-06
  rus: 2019-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/128191/kaz/06.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128191/rus/06.05.2019
caused_by:
  code: '131819'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 6 мая 2019 года № 52-2. Зарегистрировано Департаментом юстиции Жамбылской области 8 мая 2019 года № 4223
  title:
    rus: О внесении изменений в решением Сарысуского районного маслихата от 21 декабря 2018 года № 43-2 «О районном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған аудандық бюджет туралы» Сарысу аудандық мәслихатының 2018 жылғы 21 желтоқсандағы №43-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131819/rus
