act_code: '127947'
requisite: Решение акима Акбулымского сельского округа Жамбылского района Жамбылской области от 14 декабря 2018 года № 41. Зарегистрировано Департаментом юстиции Жамбылской области 26 декабря 2018 года № 4068
title:
  rus: О переименования улиц в селе Акбулым Акбулымского сельского округа и уточнение транскрипции улиц в селе Акбулым Акбулымского сельского округа
  kaz: Ақбұлым ауылдық округінің Ақбұлым ауылындағы көшелер атауларын қайта атау және Ақбұлым ауылдық округінің Ақбұлым ауылындағы көшелер атауларының транскрипциясын  нақтылау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '158004004002'
version_date:
  kaz: 2018-12-14
  rus: 2018-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/127947/kaz/14.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127947/rus/14.12.2018
