act_code: '81339'
requisite: Решение Кордайского районного маслихата Жамбылской области от 25 июня 2014 года № 32-3. Зарегистрировано Департаментом юстиции Жамбылской области 16 июля 2014 года № 2277. Утратило силу решением Кордайского районного маслихата Жамбылской области от 17 ноября 2014 года № 35-5
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Кордайского района на 2014 год
  kaz: 2014 жылы Қордай ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-25
approved_by:
- '158006000002'
version_date:
  kaz: 2014-06-25
  rus: 2014-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/81339/kaz/25.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81339/rus/25.06.2014
