act_code: '226012'
requisite: Решение акима Кордайского района Жамбылской области от 3 июня 2026 года № 27
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-03
approved_by:
- '158006000003'
version_date:
  kaz: 2026-06-03
  rus: 2026-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/226012/kaz/03.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226012/rus/03.06.2026
