act_code: '109196'
requisite: Решение акима Корагатинского сельского округа Шуского района Жамбылской области от 5 января 2017 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 19 января 2017 года № 3288
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением карантинного режима на территории села Енбек Корагатинского сельского округа
  kaz: Қорағаты ауылдық округіне қарасты Еңбек ауылына карантин режимін енгізе отырып карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-01-05
approved_by:
- '158007009001'
version_date:
  kaz: 2017-01-05
  rus: 2017-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/109196/kaz/05.01.2017
  rus: https://zan.gov.kz/client/#!/doc/109196/rus/05.01.2017
