act_code: '56943'
requisite: Решение акима Сарыкемерского сельского округа Байзакского района Жамбылской области от 9 декабря 2010 года № 66. Зарегистрировано Управлением юстиции Байзакского района 21 января 2011 года за № 6-2-124
title:
  rus: О переименовании улицы Выгонная в селе Сарыкемер
  kaz: Сарыкемер ауылындағы Выгонная көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-09
approved_by:
- '158003001002'
version_date:
  kaz: 2010-12-09
  rus: 2010-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56943/kaz/09.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56943/rus/09.12.2010
