act_code: '213326'
requisite: Решение акимата Байзакского района Жамбылской области от 27 июня 2025 года № 1
title:
  rus: Об образовании избирательных участков в Байзакском районе
  kaz: Байзақ ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-06-27
approved_by:
- '158003000001'
version_date:
  kaz: 2026-05-05
  rus: 2026-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/213326/kaz/05.05.2026
  rus: https://zan.gov.kz/client/#!/doc/213326/rus/05.05.2026
caused_by:
  code: '225032'
  requisite: Постановление акимата Байзакского района Жамбылской области от 5 мая 2026 года № 3
  title:
    rus: О внесении изменений и дополнений в решение  акима Байзакского района от 27 июня 2025 года № 1 «Об образовании избирательных участков в Байзакском районе»
    kaz: «Байзақ ауданында сайлау учаскелерін құру туралы» Байзақ ауданы әкімінің 2025 жылғы 27 маусымдағы № 1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225032/rus
