act_code: '213326'
requisite: Решение акимата Байзакского района Жамбылской области от 27 июня 2025 года № 1
title:
  rus: Об образовании избирательных участков в Байзакском районе
  kaz: Байзақ ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-06-27
approved_by:
- '158003000001'
version_date:
  kaz: 2025-06-27
  rus: 2025-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/213326/kaz/27.06.2025
  rus: https://zan.gov.kz/client/#!/doc/213326/rus/27.06.2025
