act_code: '78134'
requisite: Решение акима Сарысуского района Жамбылской области от 20 февраля 2014 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 19 марта 2014 года № 2134. Утратило силу решением акима Сарысуского района Жамбылской области от 18 мая 2026 года № 9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-20
approved_by:
- '158010000001'
version_date:
  kaz: 2023-11-30
  rus: 2023-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/78134/kaz/30.11.2023
  rus: https://zan.gov.kz/client/#!/doc/78134/rus/30.11.2023
caused_by:
  code: '189633'
  requisite: Решение акима Сарысуского района Жамбылской области от 30 ноября 2023 года № 7. Зарегистрировано Департаментом юстиции Жамбылской области 6 декабря 2023 года № 5124. Утратило силу решением акима Сарысуского района Жамбылской области от 18 мая 2026 года № 9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение акима Сарысуского района от 20 февраля 2014 года № 1 «Об образовании избирательных участков»
    kaz: «Сайлау учаскелерін құру туралы» Сарысу ауданы әкімінің 2014 жылғы 20 ақпандағы № 1 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189633/rus
