act_code: '109502'
requisite: Решение маслихата Жуалынского района Жамбылской области от 23 декабря 2016 года № 9-10. Зарегистрировано Департаментом юстиции Жамбылской области 25 января 2017 года № 3291. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 25 июня 2020 года № 67-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз и захоронение твердых бытовых отходов по Жуалынскому району
  kaz: Жуалы ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын және тұрмыстық қатты қалдықтарды жинауға, әкетуге және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2016-12-23
approved_by:
- '158005000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109502/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109502/rus/23.12.2016
