act_code: '137368'
requisite: Решение акима Мойынкумского района Жамбылской области от 19 декабря 2019 года № 4. Зарегистрировано Департаментом юстиции Жамбылской области 24 декабря 2019 года № 4460
title:
  rus: Об образовании избирательных участков на территории Мойынкумского района
  kaz: Мойынқұм ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-19
approved_by:
- '158009000003'
version_date:
  kaz: 2020-09-10
  rus: 2020-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/137368/kaz/10.09.2020
  rus: https://zan.gov.kz/client/#!/doc/137368/rus/10.09.2020
caused_by:
  code: '146250'
  requisite: Решение акима Мойынкумского района Жамбылской области от 10 сентября 2020 года № 4. Зарегистрировано Департаментом юстиции Жамбылской области 11 сентября 2020 года № 4734
  title:
    rus: О внесений изменения в решение акима Мойынкумского района № 4 от 19 декабря 2019 года «Об образовании избирательных участков на территории Мойынкумского района»
    kaz: «Мойынқұм ауданы аумағында сайлау учаскелерін құру туралы» Мойынқұм ауданы әкімінің 2019 жылғы 19 желтоқсандағы № 4 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146250/rus
