act_code: '123761'
requisite: Решение акима Ойталского сельского округа Меркенского района Жамбылской области от 29 июня 2018 года № 49. Зарегистрировано Департаментом юстиции Жамбылской области 16 июля 2018 года № 3913
title:
  rus: О переименовании улиц станции Мерке и села Ойтал Ойталского сельского округа
  kaz: Ойтал ауылдық округі Меркі стансасының және Ойтал ауылының көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-29
approved_by:
- '158008004002'
version_date:
  kaz: 2018-06-29
  rus: 2018-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/123761/kaz/29.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123761/rus/29.06.2018
