act_code: '16452'
requisite: Жамбыл облыстық мәслихатының шешімі 2003 жылғы 13 маусымдағы № 18-12. Жамбыл облыстық әділет басқармасында 2003 жылғы 18 шілдеде 1026 нөмерімен тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облысы Әділет департаментінің 2007 жылғы 24 сәуірдегі № 4-1874 хатымен
title:
  rus: Жамбыл облысы бойынша 2003-2010 жылдарға арналған "Ауыз су" кешенді Бағдарламасы туралы
  kaz: Жамбыл облысы бойынша 2003-2010 жылдарға арналған "Ауыз су" кешенді Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-12
approved_by:
- '158000000002'
version_date:
  kaz: 2003-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/16452/kaz/12.06.2003
