act_code: '19184'
requisite: Жамбыл облысы Жамбыл ауданды әкімиятының 2004 жылғы 2 наурыздағы № 53 қаулысы. Жамбыл облыстық Әділет Департаментінде 2004 жылғы 30 наурызда № 1281 тіркелді. Күші жойылды - Жамбыл облысы Жамбыл ауданы әкімдігінің 2012 жылғы 26 маусымдағы № 258 қаулысымен
title:
  rus: 2004 жылдың көктемгі егіс және егін жинау жұмыстарын жүргізуге берілген кредитті таратуды ұйымдастыру туралы
  kaz: 2004 жылдың көктемгі егіс және егін жинау жұмыстарын жүргізуге берілген кредитті таратуды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-03-02
approved_by:
- '158004000001'
version_date:
  kaz: 2012-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/19184/kaz/26.06.2012
