act_code: '205294'
requisite: Решение Кордайского районного маслихата Жамбылской области от 30 декабря 2024 года № 39-2
title:
  rus: О бюджете сельских округов Кордайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қордай ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '158006000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/205294/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205294/rus/30.12.2024
