act_code: '45544'
requisite: Жамбыл облысы Байзақ аудандық мәслихатының 2009 жылғы 20 наурыздағы № 17-6 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2009 жылғы 30 сәуірде 6-2-91 нөмірімен тіркелді
title:
  rus: Жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттері туралы
  kaz: Жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-20
approved_by:
- '158003000002'
version_date:
  kaz: 2009-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/45544/kaz/20.03.2009
