act_code: '216353'
requisite: Решение акима Сарыкемерского сельского округа Байзакского района Жамбылской области от 29 октября 2025 года № 174
title:
  rus: О присвоении наименования составной части села Сарыкемер Сарыкемерского сельского округа Байзакского района
  kaz: Байзақ ауданы Сарыкемер ауылдық округінің  Сарыкемер ауылының құрамдас бөлігіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-29
approved_by:
- '158003001001'
version_date:
  kaz: 2025-10-29
  rus: 2025-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/216353/kaz/29.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216353/rus/29.10.2025
