act_code: '81772'
requisite: Решение Таласского районного маслихата Жамбылской области от 24 июля 2014 года № 35-10. Зарегистрировано Департаментом юстиции Жамбылской области 6 августа 2014 года № 2288. Утратило силу решением Таласского районного маслихата Жамбылской области от 13 марта 2024 года № 17-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликование)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Таласском районе
  kaz: Талас ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше көппәтерлі тұрғын үй тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-24
approved_by:
- '158011000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/81772/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/81772/rus/24.12.2014
caused_by:
  code: '85756'
  requisite: Решение Таласского районного маслихата Жамбылской области от 24 декабря 2014 года № 40-10. Зарегистрировано Департаментом юстиции Жамбылской области 15 января 2015 года № 2462. Утратило силу решением Таласского районного маслихата Жамбылской области от 13 марта 2024 года № 17-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликование)
  title:
    rus: О внесении дополнения в решение Таласского районного маслихата от 24 июля 2014 года № 35 – 10 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Таласском районе»
    kaz: «Талас ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің сандық құрамын бекіту туралы» Талас аудандық мәслихатының 2014 жылғы 24 шілдедегі № 35 - 10 шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85756/rus
