act_code: '64497'
requisite: Решение Жамбылского областного маслихата от 29 марта 2012 года № 3-5. Зарегистрировано Департаментом юстиции Жамбылской области 10 апреля 2012 года № 1808
title:
  rus: О повышении ставок платы за эмиссию в окружающую среду на 2012 год
  kaz: 2012 жылға арналған қоршаған ортаға эмиссиялар үшін төлемақылар ставкаларын арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-03-29
approved_by:
- '158000000002'
version_date:
  kaz: 2012-03-29
  rus: 2012-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/64497/kaz/29.03.2012
  rus: https://zan.gov.kz/client/#!/doc/64497/rus/29.03.2012
