act_code: '108640'
requisite: Решение Байзакского районного маслихата Жамбылской области от 21 декабря 2016 года № 10-3. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2016 года № 3271
title:
  rus: О районном бюджете на 2017 – 2019 годы
  kaz: 2017 – 2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-21
approved_by:
- '158003000002'
version_date:
  kaz: 2016-12-21
  rus: 2016-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/108640/kaz/21.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108640/rus/21.12.2016
