act_code: '85365'
requisite: Решение Таласского районного маслихата Жамбылской области от 24 декабря 2014 года № 40-3. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2014 года № 2453
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015 - 2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '158011000002'
version_date:
  kaz: 2015-12-10
  rus: 2015-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/85365/kaz/10.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85365/rus/10.12.2015
caused_by:
  code: '96602'
  requisite: Решение Таласского районного маслихата Жамбылской области от 10 декабря 2015 года № 48-2. Зарегистрировано Департаментом юстиции Жамбылской области 11 декабря 2015 года № 2852
  title:
    rus: О внесении изменений в решение Таласского  районного маслихата от 24 декабря 2014 года № 40 – 3 «О районном бюджете на 2015 – 2017  годы»
    kaz: «2015 – 2017 жылдарға арналған аудандық бюджет туралы»  Талас аудандық мәслихатының 2014 жылғы 24 желтоқсандағы  № 40 – 3 шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96602/rus
