act_code: '122866'
requisite: Решение Меркенского районного маслихата Жамбылской области от 28 мая 2018 года № 29-5. Зарегистрировано Департаментом юстиции Жамбылской области 18 июня 2018 года № 3870
title:
  rus: Об утверждении регламента собрания местного сообщества сельских округов Меркенского района
  kaz: Меркі ауданы ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-28
approved_by:
- '158008000002'
version_date:
  kaz: 2018-05-28
  rus: 2018-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/122866/kaz/28.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122866/rus/28.05.2018
