act_code: '172670'
requisite: Решение Жамбылского областного маслихата от 5 октября 2022 года № 21-7. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 октября 2022 года № 30090. Утратило силу решением Жамбылского областного маслихата от 28 марта 2024 года № 13-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении бесплатного проезда гражданам Республики Казахстан проживающим в Жамбылской области, за пределы населенного пункта постоянного проживания для получения высокотехнологичных медицинских услуг в рамках гарантированного объема бесплатной медицинской помощи и (или) медицинской помощи в системе обязательного социального медицинского страхования
  kaz: Тегін медициналық көмектің кепілдік берілген көлемі шеңберінде жоғары технологиялық медициналық көрсетілетін қызметтерді және (немесе) міндетті әлеуметтік медициналық сақтандыру жүйесінде медициналық көмекті алу үшін Жамбыл облысында тіркелген Қазақстан Республикасының азаматтарына тұрақты тұратын елді мекеннен тысқары жерлерге тегін жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-10-05
approved_by:
- '158000000002'
version_date:
  kaz: 2022-10-05
  rus: 2022-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/172670/kaz/05.10.2022
  rus: https://zan.gov.kz/client/#!/doc/172670/rus/05.10.2022
