act_code: '63182'
requisite: Решение акима Жуалынского района Жамбылской области от 26 января 2012 года № 1. Зарегистрировано Управлением юстиции Жуалынского района Жамбылской области 7 февраля 2012 года за № 6-4-119
title:
  rus: Об организации приписки в 2012 году к призывному участку граждан мужского пола 1995 года рождения, проживающие на территории Жуалынского района
  kaz: 2012 жылы Жуалы ауданының аумағында тұратын 1995 жылы туылған еркек жынысты  азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-26
approved_by:
- '158005000003'
version_date:
  kaz: 2012-01-26
  rus: 2012-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/63182/kaz/26.01.2012
  rus: https://zan.gov.kz/client/#!/doc/63182/rus/26.01.2012
