act_code: '176182'
requisite: Решение Таласского районного маслихата Жамбылской области от 28 декабря 2022 года № 38-2
title:
  rus: О бюджете города и сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қала және ауылдық округ бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '158011000002'
version_date:
  kaz: 2023-08-18
  rus: 2023-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/176182/kaz/18.08.2023
  rus: https://zan.gov.kz/client/#!/doc/176182/rus/18.08.2023
caused_by:
  code: '185231'
  requisite: Решение Таласского районного маслихата Жамбылской области от 18 августа 2023 года № 7-2
  title:
    rus: О внесении изменений в  решение Таласского районного маслихата от 28 декабря 2022 года № 38–2 «О бюджете города и сельских округов на 2023-2025 годы»
    kaz: Талас аудандық мәслихатының 2022 жылғы 28 желтоқсандағы № 38-2 «2023-2025 жылдарға арналған қала және ауылдық округ бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185231/rus
