act_code: '173968'
requisite: Решение акима Карасуского сельского округа Кордайского района Жамбылской области от 21 ноября 2022 года № 70. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 ноября 2022 года № 30664
title:
  rus: О присвоении наименования безымянному переулку в селе Өтеген батыра Карасуского сельского округа Кордайского района Жамбылской области
  kaz: Жамбыл облысы Қордай ауданы Қарасу ауылдық округінің Өтеген батыр ауылындағы атауы жоқ тұйық көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-21
approved_by:
- '158006014002'
version_date:
  kaz: 2022-11-21
  rus: 2022-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/173968/kaz/21.11.2022
  rus: https://zan.gov.kz/client/#!/doc/173968/rus/21.11.2022
