act_code: '53441'
requisite: Жамбыл облысы Шу аудандық мәслихатының 2010 жылғы 18 мамырдағы № 23-19 шешімі. Жамбыл облысы Шу ауданының Әділет басқармасында 2010 жылғы 29 маусымда 6-11-93 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Шу аудандық мәслихатының 2012 жылғы 16 мамырдағы № 6-4 шешімімен
title:
  rus: Шу ауданы елді мекендерінің аумақтарын көріктендіру және жасыл өсімдіктерді қорғау және күзету Ережелерін бекіту туралы
  kaz: Шу ауданы елді мекендерінің аумақтарын көріктендіру және жасыл өсімдіктерді қорғау және күзету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-18
approved_by:
- '158012000002'
version_date:
  kaz: 2010-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/53441/kaz/18.05.2010
