act_code: '40942'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2008 жылы 30 маусымдағы № 11-13 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2008 жылғы 30 шілдеде № 6-10-62 тіркелді. Күші жойылды - Жамбыл облысы Талас аудандық мәслихатының 2010 жылғы 28 қыркүйектегі № 36-6 шешімімен
title:
  rus: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
  kaz: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-30
approved_by:
- '158011000002'
version_date:
  kaz: 2008-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/40942/kaz/30.06.2008
