act_code: '40942'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2008 жылы 30 маусымдағы № 11-13 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2008 жылғы 30 шілдеде № 6-10-62 тіркелді. Күші жойылды - Жамбыл облысы Талас аудандық мәслихатының 2010 жылғы 28 қыркүйектегі № 36-6 шешімімен
title:
  rus: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
  kaz: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-30
approved_by:
- '158011000002'
version_date:
  kaz: 2009-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/40942/kaz/29.09.2009
caused_by:
  code: '48465'
  requisite: Жамбыл облысы Талас аудандық мәслихатының 2009 жылы 29 қыркүйектегі № 24-10 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2009 жылғы 4 қарашада 6-10-86 нөмірімен тіркелді
  title:
    rus: '"Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы" Талас аудандық мәслихаттың 2008 жылғы 30 маусымдағы № 11-13 шешіміне өзгеріс енгізу туралы'
    kaz: '"Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы" Талас аудандық мәслихаттың 2008 жылғы 30 маусымдағы № 11-13 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/48465/rus
