act_code: '198911'
requisite: Решение Акима Таласского района Жамбылской области от 15 июля 2024 года № 02-03. Зарегистрировано Департаментом юстиции Жамбылской области 19 июля 2024 года № 5219-08
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін кұру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-15
approved_by:
- '158011000001'
version_date:
  kaz: 2024-07-15
  rus: 2024-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/198911/kaz/15.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198911/rus/15.07.2024
