act_code: '49398'
requisite: Жамбыл облысы Т. Рысқұлов ауданы Құлан ауылдық округі әкімінің 2009 жылғы 10 желтоқсандағы № 157 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2009 жылғы 22 желтоқсанда 6-8-89 нөмірімен тіркелді
title:
  rus: Құлан ауылындағы Некрасов көшесінің атауын халыққа еңбегі сіңген қайраткер Өзібек Ақжолұлы атына өзгерту туралы
  kaz: Құлан ауылындағы Некрасов көшесінің атауын халыққа еңбегі сіңген қайраткер Өзібек Ақжолұлы атына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-10
approved_by:
- '158007001001'
version_date:
  kaz: 2009-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/49398/kaz/10.12.2009
