act_code: '173002'
requisite: Решение Жамбылского областного маслихата от 5 октября 2022 года № 21-8
title:
  rus: Об утверждении Правил отлова, временного содержания и умерщвления животных в Жамбылской области
  kaz: Жамбыл облысында жануарларды аулаудың, уақытша ұстаудың және жансыздандырудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-10-05
approved_by:
- '158000000002'
version_date:
  kaz: 2022-10-05
  rus: 2022-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/173002/kaz/05.10.2022
  rus: https://zan.gov.kz/client/#!/doc/173002/rus/05.10.2022
