act_code: '50001'
requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 20-4 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда 6-8-90 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '158007000002'
version_date:
  kaz: 2010-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/50001/kaz/14.07.2010
caused_by:
  code: '53754'
  requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2010 жылғы 14 шілдедегі № 26-6 шешімі. Жамбыл облысы Т.Рысқұлов ауданының Әділет басқармасында 2010 жылғы 29 шілдеде 6-8-106 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Т.Рысқұлов аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 20-4 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Т.Рысқұлов аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 20-4 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53754/rus
