act_code: '50001'
requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 20-4 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда 6-8-90 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '158007000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50001/kaz/23.12.2009
