act_code: '85360'
requisite: Решение Меркенского районного маслихата Жамбылской области от 24 декабря 2014 года № 36-4. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2014 года № 2450
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдырға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '158008000002'
version_date:
  kaz: 2015-11-25
  rus: 2015-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85360/kaz/25.11.2015
  rus: https://zan.gov.kz/client/#!/doc/85360/rus/25.11.2015
caused_by:
  code: '96581'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 25 ноября 2015 года № 44-2. Зарегистрировано Департаментом юстиции Жамбылской области 25 ноября 2015 года № 2830
  title:
    rus: О внесении изменений в решение Меркенского районного маслихата от 24 декабря 2014 года №36-4 «О районном бюджете на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған аудандық бюджет туралы» Меркі аудандық мәслихатының 2014 жылғы 24 желтоқсандағы №36-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96581/rus
