act_code: '86421'
requisite: Решение акима Масанчинского сельского округа Кордайского района Жамбылской области от 14 января 2015 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 4 февраля 2015 года № 2490
title:
  rus: О присвоении наименовании новым улицам в селе Масанчи
  kaz: Масаншы ауылындағы жаңа көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-01-14
approved_by:
- '158006019001'
version_date:
  kaz: 2015-01-14
  rus: 2015-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/86421/kaz/14.01.2015
  rus: https://zan.gov.kz/client/#!/doc/86421/rus/14.01.2015
