act_code: '177122'
requisite: Решение Байзакского районного маслихата Жамбылской области от 26 декабря 2022 года № 37-2
title:
  rus: О районном бюджете на 2023 – 2025 годы
  kaz: 2023 – 2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '158003000002'
version_date:
  kaz: 2023-08-15
  rus: 2023-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/177122/kaz/15.08.2023
  rus: https://zan.gov.kz/client/#!/doc/177122/rus/15.08.2023
caused_by:
  code: '185345'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 15 августа 2023 года № 6-2
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата от 26 декабря 2022 года №37-2 «О районном бюджете на 2023–2025 годы»
    kaz: Байзақ аудандық мәслихатының 2022 жылғы 26 желтоқсандағы № 37-2 «2023 – 2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185345/rus
