act_code: '205458'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 25 декабря 2024 года № 30-5
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '158007000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205458/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205458/rus/25.12.2024
