act_code: '177004'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 29 декабря 2022 года № 38-2
title:
  rus: О бюджете города и сельских округов Сарысуского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Сарысу ауданының қала және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '158010000002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177004/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177004/rus/29.12.2022
