act_code: '95059'
requisite: Решение акима района Т.Рыскулова Жамбылской области от 20 октября 2015 года № 03. Зарегистрировано Департаментом юстиции Жамбылской области 26 октября 2015 года № 2812. Утратило силу решением акимата района Т. Рыскулова Жамбылской области от 14.12.2018 № 01
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-20
approved_by:
- '158007000003'
version_date:
  kaz: 2015-10-20
  rus: 2015-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/95059/kaz/20.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95059/rus/20.10.2015
