act_code: '36345'
requisite: Решение Жамбылского областного маслихата от 12 декабря 2007 года № 3-9. Зарегистрировано Департаментом юстиции Жамбылской области 26 декабря 2007 года за № 1671. Утратило силу решением Жамбылского областного маслихата от 29 октября 2009 года № 16-19
title:
  rus: Об областном бюджете на 2008 год
  kaz: 2008 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '158000000002'
version_date:
  kaz: 2008-11-14
  rus: 2008-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/36345/kaz/14.11.2008
  rus: https://zan.gov.kz/client/#!/doc/36345/rus/14.11.2008
caused_by:
  code: '42530'
  requisite: Решение Жамбылского областного маслихата от 14 ноября 2008 года № 9-2. Зарегистрировано Департаментом юстиции Жамбылской области 28 ноября 2008 года за номером 1715. Утратило силу решением маслихата Жамбылской области от 29 октября 2009 года № 16-19
  title:
    rus: О внесении изменений и дополнения в решение Жамбылского областного маслихата от 12 декабря 2007 года N 3-9 "Об областном бюджете на 2008 год"
    kaz: '"2008 жылға арналған облыстық бюджет туралы" Жамбыл облыстық мәслихатының 2007 жылғы 12 желтоқсандағы N 3-9 шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/42530/rus
