act_code: '51844'
requisite: амбыл облысы Байзақ ауданы Ботамойнақ ауылдық округі әкімінің 2010 жылғы 31 наурыздағы № 7 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 21 сәуірде 6-2-109 нөмірімен тіркелді
title:
  rus: Байзақ ауылындағы жаңа көшеге ат беру туралы
  kaz: Байзақ ауылындағы жаңа көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-31
approved_by:
- '158003002002'
version_date:
  kaz: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/51844/kaz/31.03.2010
