act_code: '55522'
requisite: Жамбыл облысы Қордай ауданы Қарасу ауылдық округі әкімінің 2010 жылғы 15 қазандағы № 37 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 16 қарашада 6-5-109 нөмірімен тіркелді
title:
  rus: Өтеген ауылындағы Пионер және Комсомол көшелерінің атауларын өзгерту туралы
  kaz: Өтеген ауылындағы Пионер және Комсомол көшелерінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-15
approved_by:
- '158006014002'
version_date:
  kaz: 2010-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/55522/kaz/15.10.2010
