act_code: '208850'
requisite: Решение акима Толебийского сельского округа Шуского района Жамбылской области от 2 апреля 2025 года № 69
title:
  rus: О переименовании составной части села Төле би
  kaz: Төле би ауылының құрамдас бөлігін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-02
approved_by:
- '158012002002'
version_date:
  kaz: 2025-04-02
  rus: 2025-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/208850/kaz/02.04.2025
  rus: https://zan.gov.kz/client/#!/doc/208850/rus/02.04.2025
