act_code: '190196'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 7 декабря 2023 года № 12-3. Зарегистрировано Департаментом юстиции Жамбылской области от 15 декабря 2023 года № 5133. Утратило силу решением Мойынкумского районного маслихата Жамбылской области от 1 апреля 2025 года № 36-13 (вводится   в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Мойынкумскому району
  kaz: Мойынқұм ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-07
approved_by:
- '158009000002'
version_date:
  kaz: 2024-08-15
  rus: 2024-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190196/kaz/15.08.2024
  rus: https://zan.gov.kz/client/#!/doc/190196/rus/15.08.2024
caused_by:
  code: '200055'
  requisite: Решение Мойынкумского районного маслихата Жамбылской области от 15 августа 2024 года № 25-3. Зарегистрировано Департаментом юстиции Жамбылской области от 26 августа 2024 года № 5227-08. Утратило силу решением Мойынкумского районного маслихата Жамбылской области от 1 апреля 2025 года № 36-13 (вводится   в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Мойынкумского районного маслихата от 7 декабря 2023 года № 12-3 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Мойынкумскому району»
    kaz: «Мойынқұм ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» Мойынқұм аудандық мәслихатының 2023 жылғы 7 желтоқсандағы № 12-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200055/rus
