act_code: '47441'
requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2009 жылғы 4 тамыздағы № 18-3 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2009 жылғы 24 тамызда 6-4-76 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Жуалы аудандық мәслихатының 2010 жылғы 4 ақпандағы № 24-5 шешімімен
title:
  rus: '"2009 жылға арналған аудандық бюджет туралы" Жуалы аудандық мәслихаттың 2008 жылғы 26 желтоқсандағы № 12-4 шешіміне өзерістер енгізу туралы'
  kaz: '"2009 жылға арналған аудандық бюджет туралы" Жуалы аудандық мәслихаттың 2008 жылғы 26 желтоқсандағы № 12-4 шешіміне өзерістер енгізу туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-04
approved_by:
- '158005000002'
version_date:
  kaz: 2009-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/47441/kaz/04.08.2009
