act_code: '194077'
requisite: Решение Байзакского районного маслихата Жамбылской области от 26 февраля 2024 года № 18-4. Зарегистрировано Департаментом юстиции Жамбылской области от 6 марта 2024 года № 5165-08
title:
  rus: Об утверждении ставки туристского взноса для иностранцев по Байзакскому району на 2024 год
  kaz: Байзақ ауданы бойынша шетелдіктер үшін 2024 жылға арналған туристік жарнаның мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-26
approved_by:
- '158003000002'
version_date:
  kaz: 2024-02-26
  rus: 2024-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/194077/kaz/26.02.2024
  rus: https://zan.gov.kz/client/#!/doc/194077/rus/26.02.2024
