act_code: '56486'
requisite: Жамбыл облысы Т.Рысқұлов ауданы Өрнек ауылы округі әкімінің 2010 жылғы 9 желтоқсандағы № 27 шешімі. Жамбыл облысы Т.Рысқұлов ауданының Әділет басқармасында 2010 жылғы 30 желтоқсанда 6-8-116 нөмірімен тіркелді
title:
  rus: Жарлысу ауылындағы С.Сейфуллин көшесінің батыстан оңтүстікке қараған бұрылысының атауын өзгерту туралы
  kaz: Жарлысу ауылындағы С.Сейфуллин көшесінің батыстан оңтүстікке қараған бұрылысының атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-09
approved_by:
- '158007006002'
version_date:
  kaz: 2010-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56486/kaz/09.12.2010
