act_code: '55306'
requisite: Жамбыл облыстық мәслихатының 2010 жылғы 5 қарашадағы № 28-5 шешімі. Жамбыл облысы Әділет департаментінде 2010 жылғы 9 қарашада 1757 нөмірімен болып тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
title:
  rus: '"2010-2012 жылдарға арналған облыстық бюджет туралы" Жамбыл облыстық мәслихатының 2009 жылғы 11 желтоқсандағы № 19-3 шешіміне өзгерістер  енгізу туралы'
  kaz: '"2010-2012 жылдарға арналған облыстық бюджет туралы" Жамбыл облыстық мәслихатының 2009 жылғы 11 желтоқсандағы № 19-3 шешіміне өзгерістер  енгізу туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-05
approved_by:
- '158000000002'
version_date:
  kaz: 2010-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/55306/kaz/05.11.2010
