act_code: '51420'
requisite: Жамбыл облысы Байзақ ауданы Мырзатай ауылдық округі әкімінің 2010 жылғы 25 ақпандағы № 5 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 25 наурызда 6-2-106 нөмірімен тіркелді
title:
  rus: Сеңкібай ауылындағы жаңа көшеге ат беру туралы
  kaz: Сеңкібай ауылындағы жаңа көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-25
approved_by:
- '158003011002'
version_date:
  kaz: 2010-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/51420/kaz/25.02.2010
