act_code: '183347'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 19 июня 2023 года № 5-3. Зарегистрировано Департаментом юстиции Жамбылской области 23 июня 2023 года № 5047
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по Сарысускому району
  kaz: Сарысу ауданы бойынша шетелдіктер үшін 2023 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-19
approved_by:
- '158010000002'
version_date:
  kaz: 2023-06-19
  rus: 2023-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/183347/kaz/19.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183347/rus/19.06.2023
