act_code: '56850'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 24 декабря 2010 года № 46-16. Зарегистрировано Управлением юстиции Сарысуского района 19 января 2011 года за № 6-9-109. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 23 мая 2011 года № 50-7
title:
  rus: О предоставлении бюджетного кредита специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты
  kaz: Ауылдық елді мекендерде жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына бюджеттік кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158010000002'
version_date:
  kaz: 2010-12-24
  rus: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56850/kaz/24.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56850/rus/24.12.2010
