act_code: '219798'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 23 декабря 2025 года № 48-3
title:
  rus: О бюджете сел, сельских округов Мойынкумского района на 2026–2028 годы
  kaz: 2026-2028 жылдарға арналған Мойынқұм ауданының ауыл, ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '158009000002'
version_date:
  kaz: 2026-05-21
  rus: 2026-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/219798/kaz/21.05.2026
  rus: https://zan.gov.kz/client/#!/doc/219798/rus/21.05.2026
caused_by:
  code: '225656'
  requisite: Решение Мойынкумского районного маслихата Жамбылской области от 21 мая 2026 года № 57-2
  title:
    rus: О внесении изменений в решение Мойынкумского районного маслихата «О бюджете сел, сельских округов Мойынкумского района на 2026–2028 годы» от 23 декабря 2025 года № 48-3
    kaz: Мойынқұм аудандық мәслихатының 2025 жылғы 23 желтоқсандағы «2026-2028 жылдарға арналған Мойынқұм ауданының ауыл, ауылдық округтерінің бюджеттері туралы» № 48-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225656/rus
