act_code: '128298'
requisite: Решение акима Туркестанского сельского округа Сарысуского района Жамбылской области от 24 декабря 2018 года № 18. Зарегистрировано Департаментом юстиции Жамбылской области 27 декабря 2018 года № 4071
title:
  rus: О переименовании улиц «50-лет Октября» села Ашира Буркитбаева Туркестанского сельского округа
  kaz: Түркістан ауылдық округінің Әшір Бүркітбаев ауылындағы «Октябрьдың 50-жылдығы» көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '158010005002'
version_date:
  kaz: 2018-12-24
  rus: 2018-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128298/kaz/24.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128298/rus/24.12.2018
