act_code: '85763'
requisite: Решение маслихата Таласского района Жамбылской области от 24 декабря 2014 года № 40-12. Зарегистрировано Департаментом юстиции Жамбылской области 15 января 2015 года № 2463. Утратило силу решением маслихата Таласского района Жамбылской области от 17.02.2016 № 51-3
title:
  rus: О дополнительном регламентировании  порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций на территории Таласского района
  kaz: Талас ауданы аумағында бейбіт  жиналыстар, митингілер, шерулер,  пикеттер және демонстрациялар өткізу  тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '158011000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/85763/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85763/rus/24.12.2014
