act_code: '2067'
requisite: Решение Акима Жамбылской области от 5 марта 1998 года № 70. Зарегистрировано Управлением юстиции Жамбылской области 13 апреля 1998 года № 20. Утратил силу решением Акима Жамбылской области от 28 марта 2001 года
title:
  rus: О подготовке специалистов для Вооруженных Сил Республики Казахстан в 1998 учебном году
  kaz: О подготовке специалистов для Вооруженных Сил Республики Казахстан в 1998 учебном году
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-03-05
approved_by:
- '158000000003'
version_date:
  rus: 1998-03-05
source:
  rus: https://zan.gov.kz/client/#!/doc/2067/rus/05.03.1998
