act_code: '205451'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 27 декабря 2024 года № 35-2
title:
  rus: О бюджете сел, сельских округов Мойынкумского района на 2025 – 2027 годы
  kaz: 2025-2027 жылдарға арналған Мойынқұм ауданының ауыл, ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '158009000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205451/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205451/rus/27.12.2024
