act_code: '74153'
requisite: Решение акима Аксайского сельского округа Жуалынского района Жамбылской области от 8 августа 2013 года № 21. Зарегистрировано Департаментом юстиции Жамбылской области 2 сентября 2013 года № 1999
title:
  rus: Об установлении ветеринарного режима с введением ограничительных мероприятий на территории сел Кайрат и Дихан Аксайского сельского округа
  kaz: Ақсай ауылдық округінің Қайрат және Дихан ауылдары аумағына шектеу іс - шараларын енгізе отырып, ветеринариялық режим белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-08
approved_by:
- '158005008002'
version_date:
  kaz: 2013-08-08
  rus: 2013-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/74153/kaz/08.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74153/rus/08.08.2013
