act_code: '50002'
requisite: Жамбыл облысы Талас ауданы әкімінің 2009 жылғы 10 желтоқсандағы № 16 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 12 қаңтарда Нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 6-10-91 болып енгізілді
title:
  rus: 2010 жылы Талас ауданының аумағында тұратын 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2010 жылы Талас ауданының аумағында тұратын 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-10
approved_by:
- '158011000003'
version_date:
  kaz: 2009-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/50002/kaz/10.12.2009
