act_code: '50154'
requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 23-3 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2010 жылғы 21 қаңтарда 6-4-82 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158005000002'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50154/kaz/25.12.2009
