act_code: '50154'
requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 23-3 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2010 жылғы 21 қаңтарда 6-4-82 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158005000002'
version_date:
  kaz: 2010-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/50154/kaz/14.05.2010
caused_by:
  code: '52603'
  requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2010 жылғы 14 мамырдағы № 29-3 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2010 жылғы 21 мамырда 6-4-90 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Жуалы аудандық мәслихаттың 2009 жылғы 25 желтоқсандағы № 23-3 шешіміне өзгерістер мен толықтыру енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Жуалы аудандық мәслихаттың 2009 жылғы 25 желтоқсандағы № 23-3 шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/52603/rus
