act_code: '193902'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 26 февраля 2024 года № 16-3. Зарегистрировано Департаментом юстиции Жамбылской области от 26 февраля 2024 года № 5153-08
title:
  rus: О признании утратившим силу решение Мойынкумского районного маслихата от 24 июня 2014 года №26-3 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Мойынкумском районе»
  kaz: «Мойынқұм ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің сандық құрамын бекіту туралы» Мойынқұм аудандық мәслихатының 2014 жылғы 26 маусымдағы №26-3 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-26
approved_by:
- '158009000002'
version_date:
  kaz: 2024-02-26
  rus: 2024-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/193902/kaz/26.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193902/rus/26.02.2024
