act_code: '137553'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 20 декабря 2019 года № 57-3. Зарегистрировано Департаментом юстиции Жамбылской области 27 декабря 2019 года № 4471
title:
  rus: О районном бюджете на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-20
approved_by:
- '158005000002'
version_date:
  kaz: 2020-03-11
  rus: 2020-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/137553/kaz/11.03.2020
  rus: https://zan.gov.kz/client/#!/doc/137553/rus/11.03.2020
caused_by:
  code: '140319'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 11 марта 2020 года № 60-2. Зарегистрировано Департаментом юстиции Жамбылской области 18 марта 2020 года № 4524
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 20 декабря 2019 года № 57-3 «О районном бюджете на 2020 - 2022 годы»
    kaz: «2020-2022 жылдарға арналған аудандық бюджет туралы» Жуалы аудандық мәслихатының 2019 жылғы 20 желтоқсандағы № 57-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140319/rus
