act_code: '47998'
requisite: Жамбыл облысы Жамбыл ауданы Бесағаш селолық округі әкімінің 2009 жылғы 28 тамыздағы № 37 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 1 қазанда 6-3-92 нөмірімен тіркелді
title:
  rus: Түрксіб селосындағы Седовка-2 көшесінің атауын өзгерту туралы
  kaz: Түрксіб селосындағы Седовка-2 көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-28
approved_by:
- '158004005001'
version_date:
  kaz: 2009-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/47998/kaz/28.08.2009
