act_code: '78131'
requisite: Решение Байзакского районного маслихата Жамбылской области от 18 февраля 2014 года № 25-4. Зарегистрировано Департаментом юстиции Жамбылской области 18 марта 2014 года № 2131
title:
  rus: Об утверждении регламента Байзакского районного маслихата
  kaz: Байзақ аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-02-18
approved_by:
- '158003000002'
version_date:
  kaz: 2014-02-18
  rus: 2014-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/78131/kaz/18.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78131/rus/18.02.2014
