act_code: '166236'
requisite: Решение Кордайского районного маслихата Жамбылской области от 30 марта 2022 года № 21-4. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 апреля 2022 года № 27469
title:
  rus: Об установлении специалистам Кордайского района в области социального обеспечения, культуры и спорта, являющимся гражданскими служащими и работающим в сельских населенных пунктах повышенных на двадцать пять процентов окладов и тарифных ставок
  kaz: Қордай ауданы бойынша азаматтық қызметші болып табылатын және ауылдық елді мекендерде жұмыс істейтін әлеуметтік қамсыздандыру, мәдениет және спорт саласының мамандарына жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-30
approved_by:
- '158006000002'
version_date:
  kaz: 2022-03-30
  rus: 2022-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/166236/kaz/30.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166236/rus/30.03.2022
