act_code: '166812'
requisite: Решение Меркенского районного маслихата Жамбылской области от 19 апреля 2022 года № 23-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 апреля 2022 года № 27644
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения, культуры и спорта, являющимся гражданскими служащими и работающим в сельской местности, финансируемых из районного бюджета
  kaz: Аудандық бюджеттен қаржыландырылатын, азаматтық қызметші болып табылатын және ауылдық елді мекендерде жұмыс істейтін әлеуметтік қамсыздандыру, мәдениет және спорт саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-19
approved_by:
- '158008000002'
version_date:
  kaz: 2022-04-19
  rus: 2022-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/166812/kaz/19.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166812/rus/19.04.2022
