act_code: '117945'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 20 декабря 2017 года № 25-6. Зарегистрировано Департаментом юстиции Жамбылской области 5 января 2018 года № 3669. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 7 апреля 2021 года № 4-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечния отделных категорий нуждающихся граждан по Сарысускому району
  kaz: Сарысу ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-20
approved_by:
- '158010000002'
version_date:
  kaz: 2020-04-14
  rus: 2020-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/117945/kaz/14.04.2020
  rus: https://zan.gov.kz/client/#!/doc/117945/rus/14.04.2020
caused_by:
  code: '142122'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 14 апреля 2020 года № 71-3. Зарегистрировано Департаментом юстиции Жамбылской области 21 апреля 2020 года № 4569. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 7 апреля 2021 года № 4-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в решение Сарысуского районного маслихата от 20 декабря 2017 года № 25-6 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Сарысускому району»
    kaz: «Сарысу ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айкындаудың Қағидаларын бекіту туралы» Сарысу аудандық мәслихатының 2017 жылғы 20 желтоқсандағы № 25-6 шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142122/rus
