act_code: '53148'
requisite: Жамбыл облысы Мойынқұм аудандық мәслихатының 2010 жылғы 7 маусымдағы № 28-2 шешімі. Жамбыл облысы Мойынқұм ауданының Әділет басқармасында 2010 жылғы 18 маусымда 6-7-58 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Мойынқұм ауданы мәслихатының 2012 жылғы 23 шілдедегі № 6-5 шешімімен
title:
  rus: Мойынқұм ауданы елді мекендерінің аумақтарын көріктендіру ережесін бекіту туралы
  kaz: Мойынқұм ауданы елді мекендерінің аумақтарын көріктендіру ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-07
approved_by:
- '158009000002'
version_date:
  kaz: 2010-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/53148/kaz/07.06.2010
