act_code: '142180'
requisite: Решение Таласского районного маслихата Жамбылской области от 20 апреля 2020 года № 71-6. Зарегистрировано Департаментом юстиции Жамбылской области 22 апреля 2020 года № 4572. Утратило силу решением Таласского районного маслихата Жамбылской области от 25 февраля 2021 года № 3-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Таласскому району
  kaz: Талас ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-04-20
approved_by:
- '158011000002'
version_date:
  kaz: 2020-04-20
  rus: 2020-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/142180/kaz/20.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142180/rus/20.04.2020
