act_code: '217573'
requisite: Решение Меркенского районного маслихата Жамбылской области от 27 ноября 2025 года № 49-2
title:
  rus: О понижении размера ставок налогов при применении специального налогового режима на основе упрощенной декларации в Меркенском районе
  kaz: Меркі ауданында оңайлатылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-27
approved_by:
- '158008000002'
version_date:
  kaz: 2025-11-27
  rus: 2025-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/217573/kaz/27.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217573/rus/27.11.2025
