act_code: '79186'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 21 апреля 2014 года № 24-5. Зарегистрировано Департаментом юстиции Жамбылской области 25 апреля 2014 года № 2192. Утратило силу решением Мойынкумского районного маслихата Жамбылской области от 26 сентября 2023 года № 9-7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента Мойынкумского районного маслихата
  kaz: Мойынқұм аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-21
approved_by:
- '158009000002'
version_date:
  kaz: 2014-04-21
  rus: 2014-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/79186/kaz/21.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79186/rus/21.04.2014
