act_code: '139260'
requisite: Решение Таласского районного маслихата Жамбылской области от 23 января 2020 года № 70-3. Зарегистрировано Департаментом юстиции Жамбылской области 31 января 2020 года № 4496
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Таласскому району на 2020-2021 годы
  kaz: Талас ауданы бойынша 2020-2021 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-23
approved_by:
- '158011000002'
version_date:
  kaz: 2020-01-23
  rus: 2020-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/139260/kaz/23.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139260/rus/23.01.2020
