act_code: '16228'
requisite: Жамбыл облысы Меркі аудандық мәслихатының 2003 жылғы 4 маусымдағы № 24-4 шешімі. Жамбыл облыстық Әділет басқармасында 2003 жылғы 4 шілдеде № 1005 тіркелді. Күші жойылды - Жамбыл облысы Меркі ауданы мәслихатының 2013 жылғы 22 тамыздағы № 18-7 шешімімен
title:
  rus: Азаматтардың жекелеген санаттарына Заңға сәйкес тұрғын үйді ұстауға және коммуналдық қызметтерді төлеу үшін тұрғын үй жәрдемақысын беру Қағидаларын бекіту туралы
  kaz: Азаматтардың жекелеген санаттарына Заңға сәйкес тұрғын үйді ұстауға және коммуналдық қызметтерді төлеу үшін тұрғын үй жәрдемақысын беру Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-03
approved_by:
- '158008000002'
version_date:
  kaz: 2003-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/16228/kaz/03.06.2003
