act_code: '19278'
requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихат сессиясының 2004 жылға 20 ақпандағы № 4-14 шешімі. Жамбыл облыстық Әділет Департаментінде 2004 жылғы 1 сәуірде № 1290 тіркелді. Күші жойылды - Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2008 жылғы 26 ақпандағы № 4-5 шешімімен
title:
  rus: Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Ережесін бекіту туралы
  kaz: Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-02-20
approved_by:
- '158007000002'
version_date:
  kaz: 2008-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/19278/kaz/26.02.2008
caused_by:
  code: '38550'
  requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2008 жылғы 26 ақпандағы № 4-5 шешімі. Жамбыл облысы Т. Рысқұлов ауданының әділет басқармасында 2008 жылғы 27 наурызда 6-8-56 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Т.Рысқұлов аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 30-15 шешімімен
  title:
    rus: Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Тәртібін бекіту туралы
    kaz: Табысы аз отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Тәртібін бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/38550/rus
