act_code: '15655'
requisite: Жамбыл облысы әкімінің 2003 жылғы 29 сәуірдегі № 97 шешімі. Жамбыл облыстық Әділет басқармасында 2003 жылғы 29 мамырда № 974 тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облысы Әділет департаментінің 2007 жылғы 24 сәуірдегі № 4-1874 хатымен
title:
  rus: Қазақстан халықтары кiшi Ассамблеясының мүшелерiне ұлттық-мәдени орталықтар қоғамдар мен қауымдастықтар басшыларына облыс Әкiмiнiң гранттарын беру туралы Ереженi бекiту туралы
  kaz: Қазақстан халықтары кiшi Ассамблеясының мүшелерiне ұлттық-мәдени орталықтар қоғамдар мен қауымдастықтар басшыларына облыс Әкiмiнiң гранттарын беру туралы Ереженi бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-04-28
approved_by:
- '158000000001'
version_date:
  kaz: 2003-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/15655/kaz/28.04.2003
