act_code: '117903'
requisite: Решение акима Рыскуловского ауыльного округа Меркенского района Жамбылской области от 20 декабря 2017 года № 2-09/36. Зарегистрировано Департаментом юстиции Жамбылской области 5 января 2018 года № 3670
title:
  rus: О переименовании улиц Стахановская, Садовая, Зеленая, Школьная, Н.Щорса, Папанина села Интернациональный Рыскуловского аульного округа
  kaz: Рысқұлов ауылдық округіндегі Интернациональный ауылындағы Стахановская, Садовая, Зеленая, Школьная, Н.Щорс, Папанин көшелерінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '158008006002'
version_date:
  kaz: 2017-12-20
  rus: 2017-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117903/kaz/20.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117903/rus/20.12.2017
