act_code: '192946'
requisite: Решение Кордайского районного маслихата Жамбылской области от 23 января 2024 года № 18-2. Зарегистрировано Департаментом юстиции Жамбылской области от 29 января 2024 года № 5146. Утратило силу решением Кордайского районного маслихата Жамбылской области от 28 ноября 2025 года № 52-7 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога по Кордайскому району
  kaz: Қордай ауданы бойынша бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-23
approved_by:
- '158006000002'
version_date:
  kaz: 2024-01-23
  rus: 2024-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/192946/kaz/23.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192946/rus/23.01.2024
