act_code: '52722'
requisite: Жамбыл облысы Байзақ ауданы Жаңатұрмыс ауылдық округі әкімінің 2010 жылғы 28 сәуірдегі № 18 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 26 мамырда 6-2-117 нөмірімен тіркелді
title:
  rus: Ақшолақ ауылындағы жаңа көшеге ат қою туралы
  kaz: Ақшолақ ауылындағы жаңа көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-28
approved_by:
- '158003006002'
version_date:
  kaz: 2010-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/52722/kaz/28.04.2010
