act_code: '214255'
requisite: Решение Меркенского районного маслихата Жамбылской области от 15 сентября 2025 года № 45-4
title:
  rus: Об утверждении назначения стимулирующих надбавок к месячной заработной плате работников коммунального государственного учреждения" Медиа центр Мерке" отдела внутренней политики акимата Меркенского района финансируемого из бюджета Меркенского района
  kaz: «Меркі ауданы бюджетінен қаржыландырылатын Меркі ауданы әкімдігінің ішкі саясат бөлімінің «Меркі медиа орталығы» КММ-нің қызметкерлерінің лауазымдық айлықақыларына ынталандыру үстемеақыларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-15
approved_by:
- '158008000002'
version_date:
  kaz: 2025-09-15
  rus: 2025-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/214255/kaz/15.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214255/rus/15.09.2025
