act_code: '60102'
requisite: Решение Кордайского районного маслихата Жамбылской области от 28 июля 2011 года № 39-7. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 15 августа 2011 года за номером 6-5-126. Утратило силу решением Кордайского районного маслихата Жамбылской области от 30 мая 2012 года № 6-4
title:
  rus: Об утверждении Правил содержания собак и кошек в Кордайском районе
  kaz: Қордай ауданында иттер мен мысықтарды ұстау Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-28
approved_by:
- '158006000002'
version_date:
  kaz: 2011-07-28
  rus: 2011-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/60102/kaz/28.07.2011
  rus: https://zan.gov.kz/client/#!/doc/60102/rus/28.07.2011
