act_code: '150646'
requisite: Решение Шуского районного маслихата Жамбылской области от 25 декабря 2020 года № 78-2. Зарегистрировано Департаментом юстиции Жамбылской области 28 декабря 2020 года № 4865
title:
  rus: О бюджете города Шу и сельских округов на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Шу қаласы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '158012000002'
version_date:
  kaz: 2021-10-13
  rus: 2021-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/150646/kaz/13.10.2021
  rus: https://zan.gov.kz/client/#!/doc/150646/rus/13.10.2021
caused_by:
  code: '159573'
  requisite: Решение Шуского районного маслихата Жамбылской области от 13 октября 2021 года № 15-2
  title:
    rus: О внесении изменений в решение Шуского районного маслихата Жамбылской области «О бюджете города Шу и сельских округов на 2021-2023 годы» от 25 декабря 2020 года № 78-2
    kaz: «2021-2023 жылдарға арналған Шу қаласы және ауылдық округтерінің бюджеттері туралы» Жамбыл облысы Шу аудандық мәслихатының 2020 жылғы 25 желтоқсандағы № 78-2 шешіміне өзерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159573/rus
