act_code: '53442'
requisite: Жамбыл облысы Сарысу ауданы Байқадам ауылдық аймағы әкімінің 2010 жылғы 7 маусымдағы № 26 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2010 жылғы 7 шілдеде № 6-9-96 тіркелді
title:
  rus: С. Жұмабековтің есімін көше атына беру туралы
  kaz: С. Жұмабековтің есімін көше атына беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-07
approved_by:
- '158010002002'
version_date:
  kaz: 2010-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/53442/kaz/07.06.2010
