act_code: '153105'
requisite: Решение Таласского районного маслихата Жамбылской области от 25 февраля 2021 года № 3-3. Зарегистрировано Департаментом юстиции Жамбылской области 26 февраля 2021 года № 4903. Утратило силу решением Таласского районного маслихата Жамбылской области от 2 ноября 2023 года № 9-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Таласскому району
  kaz: Талас ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2021-02-25
approved_by:
- '158011000002'
version_date:
  kaz: 2023-06-06
  rus: 2023-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/153105/kaz/06.06.2023
  rus: https://zan.gov.kz/client/#!/doc/153105/rus/06.06.2023
caused_by:
  code: '182658'
  requisite: Решение Таласского районного маслихата Жамбылской области от 6 июня 2023 года № 4-2. Зарегистрировано Департаментом юстиции Жамбылской области 8 июня 2023 года № 5036. Утратило силу решением Таласского районного маслихата Жамбылской области от 2 ноября 2023 года № 9-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Таласского районного маслихата от 25 февраля 2021 года №3-3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Таласскому району»
    kaz: «Талас ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» Талас аудандық мәслихатының 2021 жылғы 25 ақпандағы №3-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182658/rus
