act_code: '183349'
requisite: Решение Жамбылкого районного маслихата Жамбылской области от 16 июня 2023 года № 4-4. Зарегистрировано Департаментом юстиции Жамбылской области 23 июня 2023 года № 5048
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по Жамбылскому району
  kaz: Жамбыл ауданы бойынша шетелдіктер үшін 2023 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-16
approved_by:
- '158004000002'
version_date:
  kaz: 2023-06-16
  rus: 2023-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/183349/kaz/16.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183349/rus/16.06.2023
