act_code: '96828'
requisite: Решение акима Отарского сельского округа Кордайского района Жамбылской области от 13 ноября 2015 года № 58. Зарегистрировано Департаментом юстиции Жамбылской области 8 декабря 2015 года № 2846
title:
  rus: О переименовании улицы села Отар Отарского сельского округа
  kaz: Отар ауылдық округінің Отар ауылындағы көше атауы өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-13
approved_by:
- '158006011001'
version_date:
  kaz: 2015-11-13
  rus: 2015-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/96828/kaz/13.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96828/rus/13.11.2015
