act_code: '177331'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 23 декабря 2022 года № 25-2
title:
  rus: О бюджете сельских округов Мойынкумского района на 2023 – 2025 годы
  kaz: 2023-2025 жылдарға арналған Мойынқұм ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '158009000002'
version_date:
  kaz: 2023-07-05
  rus: 2023-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/177331/kaz/05.07.2023
  rus: https://zan.gov.kz/client/#!/doc/177331/rus/05.07.2023
caused_by:
  code: '184584'
  requisite: Решение Мойынкумского районного маслихата Жамбылской области от 5 июля 2023 года № 6-2
  title:
    rus: О внесении изменений в решение Мойынкумского районного маслихата Жамбылской области «О бюджете сельских округов Мойынкумского района на 2023–2025 годы» от 23 декабря 2022 года №25-2
    kaz: Жамбыл облысы Мойынқұм аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № 25-2 «2023-2025 жылдарға арналған Мойынқұм ауданы ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184584/rus
