act_code: '53975'
requisite: Жамбыл облысы Қордай аудандық мәслихатының 2010 жылғы 8 шілдедегі № 28-5 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 11 тамызда 6-5-98 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Қордай аудандық мәслихатының 2012 жылғы 30 мамырдағы № 6-4 шешімімен
title:
  rus: Қордай ауданы елді мекендерінің аумақтарын көріктендіру және жасыл желіктерді күтіп ұстау мен қорғау Ережелерін бекіту туралы
  kaz: Қордай ауданы елді мекендерінің аумақтарын көріктендіру және жасыл желіктерді күтіп ұстау мен қорғау Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-08
approved_by:
- '158006000002'
version_date:
  kaz: 2010-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/53975/kaz/08.07.2010
