act_code: '53595'
requisite: Жамбыл облысы Меркі ауданы Ақарал ауылдық округі әкімінің 2010 жылғы 8 маусымдағы № 1-01/15 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 16 шілдеде 6-6-81 нөмірімен тіркелді
title:
  rus: Ақарал ауылдық округі, Ақарал ауылындағы Октябрь көшесінің атын өзгерту туралы
  kaz: Ақарал ауылдық округі, Ақарал ауылындағы Октябрь көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-08
approved_by:
- '158008007002'
version_date:
  kaz: 2010-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/53595/kaz/08.06.2010
