act_code: '54454'
requisite: Жамбыл облысы Шу аудандық мәслихатының 2010 жылғы 12 тамыздағы № 25-3 шешімі. Жамбыл облысы Шу ауданының Әділет басқармасында 2010 жылғы 9 қыркүйектегі № 6-11-95 тіркелді. Күші жойылды - Жамбыл облысы Шу аудандық мәслихатының 2011.04.06 № 32-6 шешімімен
title:
  rus: Бір жолғы әлеуметтік көмек туралы
  kaz: Бір жолғы әлеуметтік көмек туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-12
approved_by:
- '158012000002'
version_date:
  kaz: 2010-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/54454/kaz/12.08.2010
