act_code: '117197'
requisite: Решение акима Кокталского сельского округа Таласского района Жамбылской области от 7 декабря 2017 года № 11. Зарегистрировано Департаментом юстиции Жамбылской области 21 декабря 2017 года № 3635
title:
  rus: О переименовании улицы Валентина Терешкова села Коктал Кокталского сельского округа
  kaz: Көктал ауылдық округінің Көктал ауылындағы Валентина Терешкова көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-07
approved_by:
- '158011014002'
version_date:
  kaz: 2017-12-07
  rus: 2017-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/117197/kaz/07.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117197/rus/07.12.2017
