act_code: '144336'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 25 июня 2020 года № 64-4. Зарегистрировано Департаментом юстиции Жамбылской области 1 июля 2020 года № 4662
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Жамбылского района
  kaz: Жамбыл ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '158004000002'
version_date:
  kaz: 2021-04-16
  rus: 2021-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/144336/kaz/16.04.2021
  rus: https://zan.gov.kz/client/#!/doc/144336/rus/16.04.2021
caused_by:
  code: '155239'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 16 апреля 2021 года № 4-3. Зарегистрировано Департаментом юстиции Жамбылской области 26 апреля 2021 года № 4954
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 25 июня 2020 года № 64-4 «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Жамбылского района»
    kaz: «Жамбыл ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі және мөлшерін бекіту туралы» Жамбыл аудандық мәслихатының 2020 жылғы 25 маусымдағы № 64-4 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155239/rus
