act_code: '194833'
requisite: Решение Меркенского районного маслихата Жамбылской области от 18 марта 2024 года № 21-3. Зарегистрированы Департаментом юстиции Жамбылской области 27 марта 2024 года № 5178-08. Утратило силу решением Меркенского районного маслихата Жамбылской области от 31 марта 2026 года № 56-5 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки специального налогового режима розничного налога по Меркенскому району
  kaz: Меркі ауданы бойынша бөлшек салықтың арнаулы салық режимінің мөлшерлемесін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-18
approved_by:
- '158008000002'
version_date:
  kaz: 2024-03-18
  rus: 2024-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/194833/kaz/18.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194833/rus/18.03.2024
