act_code: '19112'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2004 жылға 17 ақпандағы № 4-17 шешімі. Жамбыл облыстық Әділет Департаментінде 2004 жылғы 15 наурызда № 1255 тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2009 жылғы 29 қыркүйктегі № 26-9 шешімімен
title:
  rus: Жаңатас қаласы мен елді мекендерді аумақтарын көріктендіру, сондай-ақ қалалық инфрақұрылым объектілерін бұзылудан сақтау Ережесін бекіту туралы
  kaz: Жаңатас қаласы мен елді мекендерді аумақтарын көріктендіру, сондай-ақ қалалық инфрақұрылым объектілерін бұзылудан сақтау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-04-11
approved_by:
- '158010000002'
version_date:
  kaz: 2004-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/19112/kaz/17.02.2004
