act_code: '189707'
requisite: Решение Меркенского районного маслихата Жамбылской области от 1 декабря 2023 года № 13-2. Зарегистрировано Департаментом юстиции Жамбылской области 7 декабря 2023 года № 5125. Утратило силу решением маслихата Меркенского района Жамбылской области от 14 мая 2025 года № 42-7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Меркенскому району
  kaz: Меркі ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-01
approved_by:
- '158008000002'
version_date:
  kaz: 2023-12-01
  rus: 2023-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/189707/kaz/01.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189707/rus/01.12.2023
