act_code: '54524'
requisite: Жамбыл облысы Меркі ауданы Ойтал ауылдық округі әкімінің 2010 жылғы 23 тамыздағы № 112 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2010 жылғы 17 қыркүйекте № 6-6-85 тіркелді
title:
  rus: Ойтал ауылдық округі, Ойтал ауылындағы Совхозная көшесінің атын өзгерту туралы
  kaz: Ойтал ауылдық округі, Ойтал ауылындағы Совхозная көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-23
approved_by:
- '158008004002'
version_date:
  kaz: 2010-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/54524/kaz/23.08.2010
