act_code: '127965'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 24 декабря 2018 года № 35-2. Зарегистрировано Департаментом юстиции Жамбылской области 25 декабря 2018 года № 4061
title:
  rus: О бюджете сельских округов Мойынкумского района на 2019 – 2021 годы
  kaz: 2019-2021 жылдарға арналған Мойынқұм ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '158009000002'
version_date:
  kaz: 2018-12-24
  rus: 2018-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/127965/kaz/24.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127965/rus/24.12.2018
