act_code: '50520'
requisite: Жамбыл облысы Мойынқұм ауданы әкімінің 2009 жылғы 28 желтоқсандағы № 34 шешімі. Жамбыл облысы Мойынқұм ауданының Әділет басқармасында 2010 жылғы 8 ақпанда 6-7-51 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Мойынқұм ауданы әкімінің 2015 жылғы 19 қарашадағы № 5 шешімімен
title:
  rus: 2010 жылы Мойынқұм ауданының аумағында 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесіне тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2010 жылы Мойынқұм ауданының аумағында 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесіне тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '158009000003'
version_date:
  kaz: 2009-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/50520/kaz/28.12.2009
