act_code: '162330'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 25 декабря 2021 года № 18-7. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26038
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-25
approved_by:
- '158005000002'
version_date:
  kaz: 2022-07-15
  rus: 2022-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/162330/kaz/15.07.2022
  rus: https://zan.gov.kz/client/#!/doc/162330/rus/15.07.2022
caused_by:
  code: '169975'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 15 июля 2022 года № 28-2
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 25 декабря 2021 года № 18-7 «О районном бюджете на 2022-2024 годы»
    kaz: Жуалы аудандық мәслихатының 2021 жылғы 25 желтоқсандағы № 18-7 «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169975/rus
