act_code: '150028'
requisite: Решение Жамбылского областного маслихата от 11 декабря 2020 года № 52-8. Зарегистрировано Департаментом юстиции Жамбылской области 20 декабря 2020 года № 4843. Утратило силу решением Жамбылского областного маслихата от 5 октября 2022 года № 21-22
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в Жамбылской области
  kaz: Жамбыл облысы аумағында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-11
approved_by:
- '158000000002'
version_date:
  kaz: 2020-12-11
  rus: 2020-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/150028/kaz/11.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150028/rus/11.12.2020
