act_code: '190591'
requisite: Решение Меркенского районного маслихата Жамбылской области от 22 декабря 2023 года № 16-2
title:
  rus: О районном бюджете на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '158008000002'
version_date:
  kaz: 2023-12-22
  rus: 2023-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/190591/kaz/22.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190591/rus/22.12.2023
