act_code: '216350'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 21 октября 2025 года № 52-2
title:
  rus: Об установлении границ сел Аксайского сельского округа Жуалынского района Жамбылской области
  kaz: Жамбыл облысы Жуалы ауданы Ақсай ауылдық округінің ауылдарының шекараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-21
approved_by:
- '158005000002'
version_date:
  kaz: 2025-10-21
  rus: 2025-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/216350/kaz/21.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216350/rus/21.10.2025
