act_code: '78136'
requisite: Решение акима Меркенского района Жамбылской области от 13 февраля 2014 года № 02. Зарегистрировано Департаментом юстиции Жамбылской области 19 марта 2014 года № 2136. Утратило силу решением акима Меркенского района Жамбылской области от 12.12.2018 № 03
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-13
approved_by:
- '158008000003'
version_date:
  kaz: 2014-02-13
  rus: 2014-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/78136/kaz/13.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78136/rus/13.02.2014
