act_code: '117797'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 25 декабря 2017 года № 20-3. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2017 года № 3663
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Мойынкумскому району на 2018-2019 годы
  kaz: Мойынқұм ауданы бойынша 2018-2019 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2017-12-25
approved_by:
- '158009000002'
version_date:
  kaz: 2017-12-25
  rus: 2017-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/117797/kaz/25.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117797/rus/25.12.2017
