act_code: '74515'
requisite: Решение Жамбылского областного маслихата от 23 августа 2013 года № 16-4. Зарегистрировано Департаментом юстиции Жамбылской области 25 сентября 2013 года № 2016. Утратило силу решением маслихата Жамбылской области от 16 ноября 2015 года № 41-5
title:
  rus: Об утверждении Правил общего водопользования на водных объектах Жамбылской области
  kaz: Жамбыл облысының су объектілерінде ортақ су пайдалану Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-23
approved_by:
- '158000000002'
version_date:
  kaz: 2013-08-23
  rus: 2013-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/74515/kaz/23.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74515/rus/23.08.2013
