act_code: '94481'
requisite: Решение маслихата Жамбылской области от 25 сентября 2015 года № 40-13. Зарегистрировано Департаментом юстиции Жамбылской области 16 октября 2015 года № 2808
title:
  rus: Об определении перечня социально значимых сообщений Жамбылской области
  kaz: Жамбыл облысының әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2015-09-25
approved_by:
- '158000000002'
version_date:
  kaz: 2023-11-28
  rus: 2023-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/94481/kaz/28.11.2023
  rus: https://zan.gov.kz/client/#!/doc/94481/rus/28.11.2023
caused_by:
  code: '189508'
  requisite: Решение Жамбылского областного маслихата от 28 ноября 2023 года № 9-9. Зарегистрировано Департаментом юстиции Жамбылской области от 4 декабря 2023 года № 5122
  title:
    rus: О внесении изменения в решение Жамбылского областного маслихата от 25 сентября 2015 года № 40-13 «Об определении перечня социально значимых сообщений Жамбылской области»
    kaz: «Жамбыл облысының әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы» Жамбыл облыстық мәслихатының 2015 жылғы 25 қыркүйектегі № 40-13 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189508/rus
