act_code: '49560'
requisite: Жамбыл облысы Байзақ ауданы әкімінің 2009 жылғы 11 желтоқсандағы № 21 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2009 жылғы 31 желтоқсанда 6-2-102 нөмірімен тіркелді
title:
  rus: 2010 жылы Байзақ ауданының аумағында тұратын 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2010 жылы Байзақ ауданының аумағында тұратын 1993 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-11
approved_by:
- '158003000003'
version_date:
  kaz: 2009-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/49560/kaz/11.12.2009
