act_code: '96590'
requisite: Решение Таласского районного маслихата Жамбылской области от 25 ноября 2015 года № 47-4. Зарегистрировано Департаментом юстиции Жамбылской области 11 декабря 2015 года № 2853. Утратило силу решением Таласского районного маслихата Жамбылской области от 24.05.2018 № 35-3
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарлату  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-25
approved_by:
- '158011000002'
version_date:
  kaz: 2015-11-25
  rus: 2015-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/96590/kaz/25.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96590/rus/25.11.2015
