act_code: '57065'
requisite: Решение Таразского городского маслихата Жамбылской области от 23 декабря 2010 года № 36-6. Зарегистрировано Управлением юстиции города Тараз Жамбылской области 21 января 2011 года за номером 6-1-120. Утратило силу решением Таразского городского маслихата Жамбылской области от 14.03.2018 № 29-9
title:
  rus: О ставках земельного налога
  kaz: Жер салығының ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '158002000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/57065/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/57065/rus/23.12.2010
