act_code: '69279'
requisite: Решение Жамбылского областного маслихата от 7 декабря 2012 года № 10-3. Зарегистрировано Департаментом юстиции Жамбылской области от 12 декабря 2012 года № 1859
title:
  rus: Об областном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-07
approved_by:
- '158000000002'
version_date:
  rus: 2012-12-07
source:
  rus: https://zan.gov.kz/client/#!/doc/69279/rus/07.12.2012
