act_code: '210233'
requisite: Решение маслихата Меркенского района Жамбылской области от 14 мая 2025 года № 42-7. Зарегистрировано Департаментом юстиции Жамбылской области от 15 мая 2025 года № 5279-08
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Меркенскому району
  kaz: Меркі ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-14
approved_by:
- '158008000002'
version_date:
  kaz: 2026-05-25
  rus: 2026-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/210233/kaz/25.05.2026
  rus: https://zan.gov.kz/client/#!/doc/210233/rus/25.05.2026
caused_by:
  code: '225796'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 25 мая 2026 года № 59-4
  title:
    rus: О внесении изменений в решение Меркенского районного маслихата от 14 мая 2025 года № 42-7 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан по Меркенскому району»
    kaz: Меркі аудандық мәслихатының 2025 жылдың 14 мамырындағы «Меркі  ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» № 42-7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225796/rus
