act_code: '207579'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 30 декабря 2024 года № 37-3
title:
  rus: О бюджете города и сельских округов Сарысуского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Сарысу ауданының қала және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '158010000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/207579/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/207579/rus/30.12.2024
