act_code: '207579'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 30 декабря 2024 года № 37-3
title:
  rus: О бюджете города и сельских округов Сарысуского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Сарысу ауданының қала және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '158010000002'
version_date:
  kaz: 2025-04-09
  rus: 2025-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/207579/kaz/09.04.2025
  rus: https://zan.gov.kz/client/#!/doc/207579/rus/09.04.2025
caused_by:
  code: '209353'
  requisite: Решение Сарысуского районного маслихата Жамбылской области от 9 апреля 2025 года № 39-4
  title:
    rus: О внесении изменений в решение Сарысуского районного маслихата от 30 декабря 2024 года № 37-3 «О бюджете города и сельских округов Сарысуского района на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған Сарысу ауданының қала және ауылдық округтерінің бюджеттері туралы» Сарысу аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 37-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209353/rus
