act_code: '165664'
requisite: Решение Байзакского районного маслихата Жамбылской области от 30 декабря 2021 года № 21-2
title:
  rus: О бюджете сельских округов Байзакского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Байзақ ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '158003000002'
version_date:
  kaz: 2021-12-30
  rus: 2021-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/165664/kaz/30.12.2021
  rus: https://zan.gov.kz/client/#!/doc/165664/rus/30.12.2021
