act_code: '197006'
requisite: Решение акима Шуского района Жамбылской области от 23 мая 2024 года № 3. Зарегистрировано Департаментом юстиции Жамбылской области 24 мая 2024 года № 5208-08
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-05-23
approved_by:
- '158012000003'
version_date:
  kaz: 2025-09-11
  rus: 2025-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/197006/kaz/11.09.2025
  rus: https://zan.gov.kz/client/#!/doc/197006/rus/11.09.2025
caused_by:
  code: '214143'
  requisite: Решение акима Шуского района Жамбылской области от 11 сентября 2025 года № 2
  title:
    rus: О внесении изменений в решение акима Шуского района от 23 мая 2024 года № 3 «Об образовании избирательных участков»
    kaz: «Сайлау учаскелерін құру туралы» Шу ауданы әкімінің 2024 жылғы 23 мамырдағы № 3 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214143/rus
