act_code: '87614'
requisite: Решение от 13.02.2015 №6, Акимат Нурлыкентского сельского округа
title:
  rus: 'О переименовании улиц, переулка и тупика села Нурлыкент  Нурлыкентского сельского округа '
  kaz: 'Нұрлыкент ауылдық округінің  Нұрылкент ауылының көшелерінің, бұрылысының және тұйығының  атауларын өзгерту туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-13
approved_by:
- '158005011001'
version_date:
  kaz: 2015-02-13
  rus: 2015-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/87614/kaz/13.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87614/rus/13.02.2015
