act_code: '43381'
requisite: Жамбыл облысы Т. Рысқұлов аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 12-3 шешімі. Жамбыл облысы Т. Рысқұлов ауданының Әділет басқармасында 2009 жылғы 10 қаңтарда 6-8-73 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '158007000002'
version_date:
  kaz: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43381/kaz/24.12.2008
