act_code: '52957'
requisite: Жамбыл облысы Жамбыл ауданы Жамбыл селолық округі әкімінің 2010 жылғы 7 мамырдағы № 52 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 4 маусымда 6-3-119 нөмірімен тіркелді
title:
  rus: Жамбыл селолық округіне қарасты Қапал ауылындағы Бурыл көшесінің атын өзгерту туралы
  kaz: Жамбыл селолық округіне қарасты Қапал ауылындағы Бурыл көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-07
approved_by:
- '158004008002'
version_date:
  kaz: 2010-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/52957/kaz/07.05.2010
