act_code: '170612'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 9 августа 2022 года № 22-8. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 августа 2022 года № 29119
title:
  rus: Об утверждении ставок туристского взноса для иностранцев в районе Турара Рыскулова Жамбылской области
  kaz: Жамбыл облысы Тұрар Рысқұлов ауданында шетелдіктер үшін туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-09
approved_by:
- '158007000002'
version_date:
  kaz: 2022-08-09
  rus: 2022-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/170612/kaz/09.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170612/rus/09.08.2022
