act_code: '218042'
requisite: Решение маслихата Жамбылской области от 27 ноября 2025 года № 28-3
title:
  rus: Об утверждении ставок платы за некоторые виды лесных пользований на участках государственного лесного фонда области
  kaz: Облыстың мемлекеттік орман қоры учаскелерінде ормандарды пайдаланудың кейбір түрлері үшін төлемақы мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-27
approved_by:
- '158000000002'
version_date:
  kaz: 2025-11-27
  rus: 2025-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/218042/kaz/27.11.2025
  rus: https://zan.gov.kz/client/#!/doc/218042/rus/27.11.2025
