act_code: '53059'
requisite: Жамбыл облысы Байзақ ауданы Мырзатай ауылдық округі әкімінің 2010 жылғы 15 мамырдағы № 35 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 11 маусымда 6-2-118 нөмірімен тіркелді
title:
  rus: Дихан ауылындағы Киров көшесінің атын өзгерту туралы
  kaz: Дихан ауылындағы Киров көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-15
approved_by:
- '158003011002'
version_date:
  kaz: 2010-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/53059/kaz/15.05.2010
