act_code: '193397'
requisite: Решение Таласского районного маслихата Жамбылской области от 14 февраля 2024 года № 15-3
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума на 2024 год по Таласскому району Жамбылской области
  kaz: Жамбыл облысы Талас ауданы бойынша 2024 жылға арналған кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп – ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-14
approved_by:
- '158011000002'
version_date:
  kaz: 2024-02-14
  rus: 2024-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/193397/kaz/14.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193397/rus/14.02.2024
