act_code: '51889'
requisite: Жамбыл облысы Байзақ ауданы Мырзатай ауылдық округі әкімінің 2010 жылғы 31 наурыздағы № 20 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2010 жылғы 21 сәуірінде 6-2-111 нөмірімен тіркелді
title:
  rus: Дихан ауылындағы Завод көшесінің атын өзгерту туралы
  kaz: Дихан ауылындағы Завод көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-31
approved_by:
- '158003011002'
version_date:
  kaz: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/51889/kaz/31.03.2010
