act_code: '107432'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 24 октября 2016 года № 9-3. Зарегистрировано Департаментом юстиции Жамбылской области 4 ноября 2016 года № 3207
title:
  rus: Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в  Сарысусском районе
  kaz: Сарысу ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-24
approved_by:
- '158010000002'
version_date:
  kaz: 2016-10-24
  rus: 2016-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/107432/kaz/24.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107432/rus/24.10.2016
