act_code: '49999'
requisite: Жамбыл облысы Мойынқұм аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 22-2 шешімі. Жамбыл облысы Мойынқұм ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда 6-7-50 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158009000002'
version_date:
  kaz: 2010-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/49999/kaz/20.04.2010
caused_by:
  code: '52197'
  requisite: Жамбыл облысы Мойынқұм аудандық мәслихатының 2010 жылғы 20 сәуірдегі № 26-6 шешімі. Жамбыл облысы Мойынқұм ауданының Әділет басқармасында 2010 жылғы 27 сәуірде 6-7-55 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" 2009 жылғы 25 желтоқсандағы № 22-2 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" 2009 жылғы 25 желтоқсандағы № 22-2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/52197/rus
