act_code: '174028'
requisite: Решение Байзакского районного маслихата Жамбылской области от 21 ноября 2022 года № 34-4. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 ноября 2022 года № 30679
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Байзакскому району
  kaz: Байзақ ауданы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-21
approved_by:
- '158003000002'
version_date:
  kaz: 2022-11-21
  rus: 2022-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/174028/kaz/21.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174028/rus/21.11.2022
