act_code: '21769'
requisite: Жамбыл облыстық әкімінің 2004 жылғы 23 қыркүйектегі № 27 шешімі. Жамбыл облыстық әділет департаментінде 2004 жылғы 1 қарашада 1481 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы әкімінің 2012 жылғы 18 қаңтардағы № 1 шешімімен
title:
  rus: 2004-2005 оқу жылына Қазақстан Республикасының Қарулы Күштерi үшiн әскери-техникалық мамандар дайындау туралы
  kaz: 2004-2005 оқу жылына Қазақстан Республикасының Қарулы Күштерi үшiн әскери-техникалық мамандар дайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-09-22
approved_by:
- '158000000001'
version_date:
  kaz: 2004-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/21769/kaz/22.09.2004
