act_code: '56583'
requisite: Решение Кордайского районного маслихата от 24 декабря 2010 года № 34-4. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 6 января 2011 года за номером 6-5-114. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158006000002'
version_date:
  kaz: 2011-03-28
  rus: 2011-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56583/kaz/28.03.2011
  rus: https://zan.gov.kz/client/#!/doc/56583/rus/28.03.2011
caused_by:
  code: '58086'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 28 марта 2011 года № 35-4. Зарегистрировано Управлением юстиции Кордайского района Жамбылской области 7 апреля 2011 года за номером 6-5-122. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
  title:
    rus: О внесении изменений в решение Кордайского районного маслихата от 24 декабря 2010 года № 34-4 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Қордай аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 34-4 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58086/rus
