act_code: '56685'
requisite: Решение Байзакского районного маслихата Жамбылской области от 24 декабря 2010 года № 36-4. Зарегистрировано Департаментом юстиции Жамбылской области 13 января 2011 года за № 6-2-123. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158003000002'
version_date:
  kaz: 2011-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/56685/kaz/07.04.2011
caused_by:
  code: '58222'
  requisite: Решение Байзакского районного маслихата Жамбылской области от 7 апреля 2011 года № 39-2. Зарегистрировано Управлением юстиции Байзакского района Жамбылской области 14 апреля 2011 года за № 6-2-127. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
  title:
    rus: О внесении изменений в решение Байзакского районного маслихата "О районном бюджете на 2011-2013 годы" от 24 декабря 2010 года № 36-4
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Байзақ аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 36-4 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58222/rus
