act_code: '78045'
requisite: Решение акима Жуалынского района Жамбылской области от 25 февраля 2014 года № 1. Зарегистрировано Департаментом юстиции Жамбылской области 13 марта 2014 года № 2124. Утратило силу решением акимата Жуалынского района Жамбылской области от 10.12.2018 № 1
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-25
approved_by:
- '158005000003'
version_date:
  kaz: 2014-02-25
  rus: 2014-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/78045/kaz/25.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78045/rus/25.02.2014
