act_code: '175411'
requisite: Решение акима Ботамойнакского сельского округа Байзакского района Жамбылской области от 13 декабря 2022 года № 78. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 декабря 2022 года № 31111
title:
  rus: О переименовании некоторых составных частей села Байзак Ботамойнакского сельского округа Байзакского района
  kaz: Байзақ ауданы Ботамойнақ ауылдық округінің Байзақ ауылының кейбір құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-13
approved_by:
- '158003002002'
version_date:
  kaz: 2022-12-13
  rus: 2022-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/175411/kaz/13.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175411/rus/13.12.2022
