act_code: '49988'
requisite: Решение Таразского городского маслихата Жамбылской области от 25 декабря 2009 года № 25-3. Зарегистрировано Управлением юстиции города Тараз Жамбылской области 15 января 2010 года за № 6-1-96
title:
  rus: О городском бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158002000002'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49988/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49988/rus/25.12.2009
