act_code: '181726'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 16 мая 2023 года № 3-5. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 25 февраля 2024 года № 17-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Жуалынского районного маслихата»
  kaz: «Жуалы аудандық мәслихаты аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-05-16
approved_by:
- '158005000002'
version_date:
  kaz: 2023-10-13
  rus: 2023-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/181726/kaz/13.10.2023
  rus: https://zan.gov.kz/client/#!/doc/181726/rus/13.10.2023
caused_by:
  code: '187380'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 13 октября 2023 года № 9-8. Утратило силу решением Жуалынского районного маслихата Жамбылской области от 25 февраля 2024 года № 17-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 16 мая 2023 года №3-5 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Жуалынского районного маслихата»
    kaz: Жуалы аудандық мәслихатының 2023 жылғы 16 мамырдағы №3-5 «Жуалы аудандық мәслихаты аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187380/rus
