act_code: '207723'
requisite: Решение Шуского районного маслихата Жамбылской области от 25 декабря 2024 года № 33-3
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '158012000002'
version_date:
  kaz: 2025-08-18
  rus: 2025-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/207723/kaz/18.08.2025
  rus: https://zan.gov.kz/client/#!/doc/207723/rus/18.08.2025
caused_by:
  code: '213595'
  requisite: Решение Шуского районного маслихата Жамбылской области от 18 августа 2025 года № 41-2
  title:
    rus: О внесении изменений в решение Шуского районного маслихата от 25 декабря 2024 года № 33-3 «О районном бюджете на 2025-2027 годы»
    kaz: Шу аудандық мәслихатының «2025-2027 жылдарға арналған аудандық бюджет туралы» 2024 жылғы 25 желтоқсандағы № 33-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213595/rus
