act_code: '189084'
requisite: Решение акима Шыганакского сельского округа Мойынкумского района Жамбылской области от 26 октября 2023 года № 48
title:
  rus: О переименовании некоторых составной части села Шыганак Шыганакского сельского округа
  kaz: Шығанақ ауылдық округінің Шығанақ ауылының құрамдас бөлігін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-26
approved_by:
- '158009015002'
version_date:
  kaz: 2023-10-26
  rus: 2023-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/189084/kaz/26.10.2023
  rus: https://zan.gov.kz/client/#!/doc/189084/rus/26.10.2023
