act_code: '176270'
requisite: Решение Таразского городского маслихата Жамбылской области от 23 декабря 2022 года № 21-2
title:
  rus: О городском бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '158002000002'
version_date:
  kaz: 2023-10-23
  rus: 2023-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/176270/kaz/23.10.2023
  rus: https://zan.gov.kz/client/#!/doc/176270/rus/23.10.2023
caused_by:
  code: '187661'
  requisite: Решение Таразского городского маслихата Жамбслой области от 23 октября 2023 года № 8-2
  title:
    rus: О внесении изменений в решение Таразского городского маслихата от 23 декабря 2022 года №21-2 «О городском бюджете на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған қалалық бюджет туралы» Тараз қалалық мәслихатының 2022 жылғы 23 желтоқсандағы №21-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187661/rus
