act_code: '43441'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 17-3 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2009 жылғы 14 қаңтарда № 6-9-71 тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2010 жылғы 9 ақпандағы № 32-8 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '158010000002'
version_date:
  kaz: 2009-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43441/kaz/19.02.2009
caused_by:
  code: '44815'
  requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2009 жылғы 19 ақпандағы № 20-2 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2009 жылғы 16 наурызда 6-9-73 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2010 жылғы 9 ақпандағы № 32-8 шешімімен
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Сарысу аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 17-3 шешіміне өзгерістер енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Сарысу аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 17-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/44815/rus
