act_code: '92318'
requisite: Решение Жамбылского областного маслихата от 25 июня 2015 года № 38-12. Зарегистрировано Департаментом юстиции Жамбылской области 29 июля 2015 года № 2708
title:
  rus: Об утверждении норм бесплатного, без разрешительных документов сбора  физическими лицами для собственных  нужд на территории государственного  лесного фонда   дикорастущих плодов, орехов, грибов, ягод  лекарственного сырья и иных лесных ресурсов
  kaz: Мемлекеттік орман қоры аумағында  жеке тұлғалардың өз қажеттілігіне ақысыз, рұқсат беру құжаттарынсыз жабайы  жеміс, жаңғақ, аңырауқұлақ, дәрілік өсімдік шикізаттарын және орман ресурстарын жинау нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-25
approved_by:
- '158000000002'
version_date:
  kaz: 2015-06-25
  rus: 2015-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/92318/kaz/25.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92318/rus/25.06.2015
