act_code: '190594'
requisite: Решение акима Ойталского сельского округа Меркенского района Жамбылской области от 22 декабря 2023 года № 70
title:
  rus: О переименовании улиц станции Мерке и села Ойтал Ойталского сельского округа
  kaz: Ойтал ауылдық округі Меркі станциясы және Ойтал ауылының көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '158008004002'
version_date:
  kaz: 2023-12-22
  rus: 2023-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/190594/kaz/22.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190594/rus/22.12.2023
