act_code: '166906'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 19 апреля 2022 года № 16-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 апреля 2022 года № 27719
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения, культуры и спорта, являющимся гражданскими служащими и работающим в сельских населенных пунктах Мойынкумского района
  kaz: Мойынқұм ауданының азаматтық қызметші болып табылатын және ауылдық елді мекендерде жұмыс істейтін әлеуметтік қамсыздандыру, мәдениет және спорт саласының мамандарына жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-19
approved_by:
- '158009000002'
version_date:
  kaz: 2022-04-19
  rus: 2022-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/166906/kaz/19.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166906/rus/19.04.2022
