act_code: '129201'
requisite: Решение Меркенского районного маслихата Жамбылской области от 7 февраля 2019 года № 42-4. Зарегистрировано Департаментом юстиции Жамбылской области 11 февраля 2019 года № 4098
title:
  rus: О предоставлении социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Меркенского района в 2019 году
  kaz: 2019 жылы Меркі ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарына әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-07
approved_by:
- '158008000002'
version_date:
  kaz: 2019-02-07
  rus: 2019-02-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/129201/kaz/07.02.2019
  rus: https://zan.gov.kz/client/#!/doc/129201/rus/07.02.2019
