act_code: '194520'
requisite: Решение Таласского районного маслихата Жамбылской области от 13 марта 2024 года № 17-7. Зарегистрировано Департаментом юстиции Жамбылской области от 18 марта 2024 года № 5171-08
title:
  rus: О признании утратившим силу решение Таласского районного маслихата от 23 ноября 2018 года №43-3 «О повышении базовых ставок земельного налога и ставок единого земельного налога на неиспользуемые земли сельскохозяйственного назначения»
  kaz: «Пайданылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін арттыру туралы» Талас аудандық мәслихатының 2018 жылғы 23 қарашадағы №43-3 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-13
approved_by:
- '158011000002'
version_date:
  kaz: 2024-03-13
  rus: 2024-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/194520/kaz/13.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194520/rus/13.03.2024
