act_code: '144168'
requisite: Решение Шуского районного маслихата Жамбылской области от 25 июня 2020 года № 65-2. Зарегистрировано Департаментом юстиции Жамбылской области 26 июня 2020 года № 4645
title:
  rus: Об определении специализированных мест для проведения собраний, митингов, демонстраций, шествий, пикетирований и правил их использования в Шуском районе
  kaz: Шу ауданында жиналыстар, митингілер, демонстрациялар, шерулер мен пикеттерді өткізуге арналған арнайы орындарды белгілеу және оларды пайдалану тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '158012000002'
version_date:
  kaz: 2020-06-25
  rus: 2020-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/144168/kaz/25.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144168/rus/25.06.2020
