act_code: '199753'
requisite: Решение акима города Тараз Жамбылской области от 7 августа 2024 года № 8. Зарегистрировано Департаментом юстиции Жамбылской области от 9 августа 2024 года № 5222-08. Утратило силу решением акима города Тараз Жамбылской области от 27 апреля 2026 года № 3 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-07
approved_by:
- '158002000003'
version_date:
  kaz: 2024-08-07
  rus: 2024-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/199753/kaz/07.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199753/rus/07.08.2024
