act_code: '199753'
requisite: Решение акима города Тараз Жамбылской области от 7 августа 2024 года № 8. Зарегистрировано Департаментом юстиции Жамбылской области от 9 августа 2024 года № 5222-08. Утратило силу решением акима города Тараз Жамбылской области от 27 апреля 2026 года № 3 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-07
approved_by:
- '158002000003'
version_date:
  kaz: 2025-04-23
  rus: 2025-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/199753/kaz/23.04.2025
  rus: https://zan.gov.kz/client/#!/doc/199753/rus/23.04.2025
caused_by:
  code: '209656'
  requisite: Решение акима города Тараз Жамбылской области от 23 апреля 2025 года № 21. Зарегистрировано Департаментом юстиции Жамбылской области 25 апреля 2025 года № 5274-08. Утратило силу решением акима города Тараз Жамбылской области от 27 апреля 2026 года № 3 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: Решение акима Тараз "О внесении дополнений в решение акима города Тараз  от 7 августа 2024 года № 8 «Об образовании избирательных участков»
    kaz: «Сайлау учаскелерін құру туралы» Тараз қаласы әкімінің 2024 жылғы 7 тамыздағы № 8 шешіміне толықтырулар енгізу туралы" Тараз қаласы әкімінің шешімі
  link: https://zan.gov.kz/client/#!/doc/209656/rus
