act_code: '56999'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 24 декабря 2010 года № 30-8. Зарегистрировано Управлением юстиции района Т.Рыскулова 13 января 2011 года за № 6-8-119. Утратило силу решением маслихата района Т.Рыскулова Жамбылской области от 29 марта 2013 года № 10-6
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) по Т.Рыскуловскому району
  kaz: Т.Рысқұлов ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '158007000002'
version_date:
  kaz: 2010-12-24
  rus: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56999/kaz/24.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56999/rus/24.12.2010
