act_code: '53550'
requisite: Жамбыл облысы Т. Рысқұлов ауданы Тереңөзек ауылдық округі әкімінің 2010 жылғы 7 маусымдағы № 07 шешімі. Жамбыл облысы Т.Рысқұлов ауданының Әділет басқармасында 2010 жылғы 2 шілдеде 6-8-105 нөмірімен тіркелді
title:
  rus: Шолаққайынды ауылындағы Мир көшесін Ұлы Отан Соғысының ардагері Байдосов Тоқтарқұлдың атына өзгерту туралы
  kaz: Шолаққайынды ауылындағы Мир көшесін Ұлы Отан Соғысының ардагері Байдосов Тоқтарқұлдың атына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-07
approved_by:
- '158007003002'
version_date:
  kaz: 2010-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/53550/kaz/07.06.2010
