act_code: '75207'
requisite: Решение маслихата района Т.Рыскулова Жамбылской области от 10 октября 2013 года № 18-7. Зарегистрировано Департаментом юстиции Жамбылской области от 6 ноября 2013 года № 2035. Утратило силу решением маслихата района Т.Рыскулова Жамбылской области от 12.04.2017 № 14-5
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Т.Рыскуловскому району
  kaz: Т.Рысқұлов ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін  белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-10-10
approved_by:
- '158007000002'
version_date:
  kaz: 2013-10-10
  rus: 2013-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/75207/kaz/10.10.2013
  rus: https://zan.gov.kz/client/#!/doc/75207/rus/10.10.2013
