act_code: '63135'
requisite: Решение Шуского районного акимата Жамбылской области от 30 декабря 2011 года № 11. Зарегистрировано Шуским управлением юстиции 2 февраля 2012 года за № 6-11-118. Утратило силу решением акима Шуского района Жамбылской области от 10 сентября 2015 года № 4
title:
  rus: Об организации приписки в 2012 году к призывному участку граждан мужского пола 1995 года рождения, проживающие на территории Шуского района
  kaz: 2012 жылы Шу ауданының аумағында тұратын 1995 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-30
approved_by:
- '158012000001'
version_date:
  kaz: 2011-12-30
  rus: 2011-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/63135/kaz/30.12.2011
  rus: https://zan.gov.kz/client/#!/doc/63135/rus/30.12.2011
