act_code: '195731'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 15 апреля 2024 года № 21-9
title:
  rus: Об утверждении Программы по управлению коммунальными отходами города Жанатас Сарысуского района на 2024-2028 годы
  kaz: Сарысу ауданы Жаңатас қаласының коммуналдық қалдықтарды басқару жөніндегі 2024-2028 жылдарға арналған бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-15
approved_by:
- '158010000002'
version_date:
  kaz: 2024-04-15
  rus: 2024-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/195731/kaz/15.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195731/rus/15.04.2024
