act_code: '110460'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 2 марта 2017 года № 9-6. Зарегистрировано Департаментом юстиции Жамбылской области 14 марта 2017 года № 3348
title:
  rus: О признании утратившим силу решение маслихата Жамбылского района от 26 октября 2005 года № 18-2 «Об утверждении правил защиты зеленых насаждений, порядок содержания и благоустройства населенных пунктов района»
  kaz: «Ауданның елді мекендерін көріктендіру, жасыл желекті тәртіпте ұстау мен қорғаудың Ережесін бекіту туралы» Жамбыл аудандық мәслихатының 2005 жылғы 26 қазандағы № 18-2 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-02
approved_by:
- '158004000002'
version_date:
  kaz: 2017-03-02
  rus: 2017-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/110460/kaz/02.03.2017
  rus: https://zan.gov.kz/client/#!/doc/110460/rus/02.03.2017
