act_code: '62142'
requisite: Решение Таразского городского маслихата Жамбылской области от 14 декабря 2011 года № 45-3. Зарегистрировано управлением юстиции города Тараз Жамбылской области от 23 декабря 2011 года № 6-1-138. Утратило силу в связи с истечением срока применения - (письмо Департамента юстиции Жамбылской области от 11 марта 2013 года № 2-2-17/388)
title:
  rus: О городском бюджете на 2012 - 2014 годы
  kaz: 2012-2014 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-14
approved_by:
- '158002000002'
version_date:
  kaz: 2012-10-03
  rus: 2012-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/62142/kaz/03.10.2012
  rus: https://zan.gov.kz/client/#!/doc/62142/rus/03.10.2012
caused_by:
  code: '68043'
  requisite: Решение Таразского городского маслихата Жамбылской области от 3 октября 2012 года № 8-4. Зарегистрировано Департаментом юстиции Жамбылской области 9 октября 2012 года № 1827
  title:
    rus: О внесении изменений в решение Таразского городского маслихата от 14 декабря 2011 года № 45-3 "О городском бюджете на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған қалалық бюджет туралы" Тараз қалалық мәслихатының 2011 жылғы 14 желтоқсандағы № 45-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/68043/rus
