act_code: '43286'
requisite: Жамбыл облысы Жуалы ауданы әкімінің 2008 жылғы 3 желтоқсандағы № 12 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда 6-4-66 нөмірімен тіркелді
title:
  rus: 2009 жылы Жуалы ауданының аумағында тұратын 1992 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2009 жылы Жуалы ауданының аумағында тұратын 1992 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-03
approved_by:
- '158005000003'
version_date:
  kaz: 2008-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/43286/kaz/03.12.2008
