act_code: '219128'
requisite: Решение акима Колькайнарского сельского округа Жамбылского района Жамбылской области от 3 ноября 2025 года № 108
title:
  rus: О присвоении наименований некоторым составным частям села Костобе Жамбылского района Жамбылской области
  kaz: Жамбыл облысы Жамбыл ауданы Қостөбе ауылының құрамдас бөлігіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-03
approved_by:
- '158004009001'
version_date:
  kaz: 2025-11-03
  rus: 2025-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/219128/kaz/03.11.2025
  rus: https://zan.gov.kz/client/#!/doc/219128/rus/03.11.2025
