act_code: '126383'
requisite: Решение Байзакского районного маслихата Жамбылской области от 26 ноября 2018 года № 35-2. Зарегистрировано Департаментом юстиции Жамбылской области 29 ноября 2018 года № 3995
title:
  rus: О корректировке ставок земельного налога по Байзакскому району
  kaz: Байзақ ауданы бойынша жер салығының мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-26
approved_by:
- '158003000002'
version_date:
  kaz: 2018-11-26
  rus: 2018-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/126383/kaz/26.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126383/rus/26.11.2018
