act_code: '129254'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 13 февраля 2019 года № 39-4. Зарегистрировано Департаментом юстиции Жамбылской области 18 февраля 2019 года № 4104
title:
  rus: Об определении размеров предоставления мер социальной поддержки специалистам в области  здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты района в 2019 году
  kaz: 2019 жылы ауданның ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы  мамандарына әлеуметтік қолдау шараларын ұсыну мөлшерлерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-13
approved_by:
- '158005000002'
version_date:
  kaz: 2019-09-09
  rus: 2019-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/129254/kaz/09.09.2019
  rus: https://zan.gov.kz/client/#!/doc/129254/rus/09.09.2019
caused_by:
  code: '134926'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 9 сентября 2019 года № 50-2. Зарегистрировано Департаментом юстиции Жамбылской области 13 сентября 2019 года № 4328
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата Жамбылской области от 13 февраля 2019 года № 39-4 «Об определении размеров предоставления мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса прибывшим для работы и проживания в сельские населенные пункты района в 2019 году»
    kaz: «2019 жылы ауданның ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарына әлеуметтік қолдау шараларын ұсыну мөлшерлерін айқындау туралы» Жамбыл облысы Жуалы аудандық мәслихатының 2019 жылғы 13 ақпандағы № 39-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134926/rus
