act_code: '56584'
requisite: Жамбыл облысы Байзақ ауданың әкімінің 2010 жылғы 6 желтоқсандағы № 33 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2011 жылғы 6 қаңтарда 6-2-122 нөмірімен тіркелді
title:
  rus: 2011 жылы Байзақ ауданының аумағында тұратын 1994 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2011 жылы Байзақ ауданының аумағында тұратын 1994 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-06
approved_by:
- '158003000001'
version_date:
  kaz: 2010-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/56584/kaz/06.12.2010
