act_code: '62658'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 14 декабря 2011 года № 47-5. Зарегистрировано Управлением юстиции Жамбылского района 10 января 2012 года № 6-3-134. Утратило силу решением Жамбылского районного маслихата Жамбылской области от 19.07.2018 № 28-5
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-14
approved_by:
- '158004000002'
version_date:
  kaz: 2011-12-14
  rus: 2011-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/62658/kaz/14.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62658/rus/14.12.2011
