act_code: '191510'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 29 декабря 2023 года № 17-4
title:
  rus: Об установлении стимулирующих надбавок к долностным окладам работников организаций, финансируемых из местного бюджета
  kaz: Жергілікті бюджеттен қаржыландырылатын ұйымдар жұмыскерлерінің лауазымдық айлықақыларына ынталандыру үстемеақы белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '158010000002'
version_date:
  kaz: 2023-12-29
  rus: 2023-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/191510/kaz/29.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191510/rus/29.12.2023
