act_code: '14661'
requisite: Жамбыл облыстық мәслихатының 2002 жылғы 22 қарашадағы № 15-4 шешімі. Жамбыл облыстық әділет басқармасында 2003 жылғы 13 қаңтарда № 808 тіркелді. Шешімінің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Жамбыл облыстық мәслихатының 2007 жылғы 30 наурыздағы № 22-22 шешімімен
title:
  rus: Жамбыл облысының 2003-2005 жылдарға арналған аграрлық азық-түлік "Ауыл" бағдарламасы туралы
  kaz: Жамбыл облысының 2003-2005 жылдарға арналған аграрлық азық-түлік "Ауыл" бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-11-22
approved_by:
- '158000000002'
version_date:
  kaz: 2002-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/14661/kaz/22.11.2002
