act_code: '108795'
requisite: Решение Сарысуского районного маслихата Жамбылской области от 6 декабря 2016 года № 11-6. Зарегистрировано Департаментом юстиции Жамбылской области 5 января 2017 года № 3279. Утратило силу решением Сарысуского районного маслихата Жамбылской области от 23 декабря 2020 года № 87-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил выдачи служебного удостоверения аппарата Сарысуского районного маслихата и его описания
  kaz: Сарысу аудандық мәслихаты аппаратының қызметтік куәлігін беру Қағидаларын және оның сипаттамасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-12-06
approved_by:
- '158010000002'
version_date:
  kaz: 2016-12-06
  rus: 2016-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/108795/kaz/06.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108795/rus/06.12.2016
