act_code: '75021'
requisite: Решение Жамбылского областного маслихата от 27 сентября 2013 года № 17-12. Зарегистрировано Департаментом юстиции Жамбылской области 29 октября 2013 года № 2031
title:
  rus: Об утверждении Правил подготовки и проведения отопительного сезона в Жамбылской области
  kaz: Жамбыл облысында жылу маусымына дайындық және оны өткізу Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-09-27
approved_by:
- '158000000002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/75021/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/75021/rus/12.12.2019
caused_by:
  code: '137100'
  requisite: Решение Жамбылского областного маслихата от 12 декабря 2019 года № 41-13. Зарегистрировано Департаментом юстиции Жамбылской области 18 декабря 2019 года № 4446
  title:
    rus: О внесении изменения в решение Жамбылского областного маслихата от 27 сентября 2013 года № 17-12 «Об утверждении Правил подготовки и проведения отопительного сезона в Жамбылской области»
    kaz: «Жамбыл облысында жылу маусымына дайындық және оны өткізу Қағидаларын бекіту туралы» Жамбыл облыстық мәслихатының 2013 жылғы 27 қыркүйектегі № 17-12 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137100/rus
