act_code: '17596'
requisite: Жамбыл облысы Байзақ аудандық мәслихатының 2003 жылғы 21 қарашадағы № 2-8 шешімі. Жамбыл облыстық Әділет басқармасында 2003 жылғы 28 қарашада № 1153 тіркелді
title:
  rus: Аудандағы тұрмысы кедейшілік шегінен төмен отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Ережесін бекіту туралы
  kaz: Аудандағы тұрмысы кедейшілік шегінен төмен отбасыларына коммуналдық қызметтерді тұтынуға берілетін бір жолғы материалдық көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-11-21
approved_by:
- '158003000002'
version_date:
  kaz: 2003-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/17596/kaz/21.11.2003
