act_code: '151462'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 29 декабря 2020 года № 78-2. Зарегистрировано Департаментом юстиции Жамбылской области 8 января 2021 года № 4887
title:
  rus: О бюджетах сельских округов и села Б. Момышулы Жуалынского района на 2021-2023 годы
  kaz: "2021-2023 жылдарға арналған Жуалы ауданы Б. Момышұлы ауылы және ауылдық\tокругтерінің бюджеттері туралы"
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '158005000002'
version_date:
  kaz: 2021-12-15
  rus: 2021-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/151462/kaz/15.12.2021
  rus: https://zan.gov.kz/client/#!/doc/151462/rus/15.12.2021
caused_by:
  code: '161788'
  requisite: Решение Жуалынского районного маслихата Жамбылской области от 15 декабря 2021 года № 17-2
  title:
    rus: О внесении изменений в решение Жуалынского районного маслихата от 29 декабря 2020 года № 78-2 «О бюджетах сельских округов и села Б. Момышулы Жуалынского района на 2021-2023 годы»
    kaz: Жуалы аудандық мәслихатының 2020 жылғы 29 желтоқсандағы № 78-2 «2021-2023 жылдарға арналған Жуалы ауданы Б. Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161788/rus
