act_code: '53236'
requisite: Жамбыл облысы Қордай аудандық мәслихатының 2010 жылғы 18 мамырдағы № 27-4 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 21 маусымда 6-5-93 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Қордай аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 13-12 шешімімен
title:
  rus: Біржолғы талондардың құны туралы
  kaz: Біржолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-18
approved_by:
- '158006000002'
version_date:
  kaz: 2012-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/53236/kaz/02.03.2012
caused_by:
  code: '64432'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 2 марта 2012 года № 3-3. Зарегистрировано Кордайским управлением юстиции Жамбылской области 5 апреля 2012 года № 6-5-140. Утратило силу - решением Кордайского районного маслихата Жамбылской области от 28 марта 2013 года № 14-13
  title:
    rus: О внесении дополнений в решение Кордайского районного маслихата от 18 мая 2010 года № 27-4 "О стоимости разовых талонов"
    kaz: '"Біржолғы талондардың құны туралы" Қордай аудандық мәслихатының 2010 жылғы 18 мамырдағы № 27-4 шешіміне толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/64432/rus
