act_code: '53236'
requisite: Жамбыл облысы Қордай аудандық мәслихатының 2010 жылғы 18 мамырдағы № 27-4 шешімі. Жамбыл облысы Қордай ауданының Әділет басқармасында 2010 жылғы 21 маусымда 6-5-93 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Қордай аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 13-12 шешімімен
title:
  rus: Біржолғы талондардың құны туралы
  kaz: Біржолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-18
approved_by:
- '158006000002'
version_date:
  kaz: 2010-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/53236/kaz/18.05.2010
