act_code: '53771'
requisite: Решение Таразского городского маслихата Жамбылской области от 25 июня 2010 года № 30-9. Зарегистрировано Управлением юстиции города Тараз Жамбылской области 30 июля 2010 года за номером 6-1-110. Утратило силу решением Таразского городского маслихата Жамбылской области от 27 июня 2012 года № 5-8
title:
  rus: Об утверждении Правил содержания собак и кошек в городе Таразе
  kaz: Тараз қаласында иттер мен мысықтарды ұстау ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-06-25
approved_by:
- '158002000002'
version_date:
  kaz: 2010-06-25
  rus: 2010-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/53771/kaz/25.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53771/rus/25.06.2010
