act_code: '48468'
requisite: Жамбыл облысы Жамбыл ауданы Қаратөбе ауылдық округі әкімінің 2009 жылғы 20 қазандағы № 17 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 5 қарашада 6-3-102 нөмірімен тіркелді
title:
  rus: Бектөбе ауылындағы Жаңа-3 көшесінің атауын өзгерту туралы
  kaz: Бектөбе ауылындағы Жаңа-3 көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-20
approved_by:
- '158004013001'
version_date:
  kaz: 2010-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/48468/kaz/12.04.2010
caused_by:
  code: '52275'
  requisite: Жамбыл облысы Жамбыл ауданы Қаратөбе ауылдық округі әкімінің 2010 жылғы 12 сәуірдегі № 31 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 6 мамырда 6-3-113 нөмірімен тіркелді
  title:
    rus: '"Бектөбе ауылындағы Жаңа-3 көшесінің атауын өзгерту туралы" Қаратөбе ауылдық округі әкімінің 2009 жылғы  20 қазандағы  № 17 шешіміне өзгерістер енгізу туралы'
    kaz: '"Бектөбе ауылындағы Жаңа-3 көшесінің атауын өзгерту туралы" Қаратөбе ауылдық округі әкімінің 2009 жылғы  20 қазандағы  № 17 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/52275/rus
