act_code: '48468'
requisite: Жамбыл облысы Жамбыл ауданы Қаратөбе ауылдық округі әкімінің 2009 жылғы 20 қазандағы № 17 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 5 қарашада 6-3-102 нөмірімен тіркелді
title:
  rus: Бектөбе ауылындағы Жаңа-3 көшесінің атауын өзгерту туралы
  kaz: Бектөбе ауылындағы Жаңа-3 көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-20
approved_by:
- '158004013001'
version_date:
  kaz: 2009-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/48468/kaz/20.10.2009
