act_code: '225289'
requisite: Совместное постановление акимата Жамбылской области от 5 мая 2026 года № 88 и решение маслихата Жамбылской области от 5 мая 2026 года № 33-5
title:
  rus: Об изменении административной подчиненности некоторых населенных пунктов и границ сельских округов Жамбылского района Жамбылской области
  kaz: Жамбыл облысы Жамбыл ауданының кейбір елді мекендерінің әкімшілік бағыныстылығын және ауылдық округтердің шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-05
approved_by:
- '158000000002'
version_date:
  kaz: 2026-05-05
  rus: 2026-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/225289/kaz/05.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225289/rus/05.05.2026
