act_code: '138377'
requisite: Решение Кордайского районного маслихата Жамбылской области от 30 декабря 2019 года № 63-2. Зарегистрировано Департаментом юстиции Жамбылской области 10 января 2020 года № 4491
title:
  rus: О бюджете сельских округов Кордайского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Қордай ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '158006000002'
version_date:
  kaz: 2020-11-03
  rus: 2020-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/138377/kaz/03.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138377/rus/03.11.2020
caused_by:
  code: '148345'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 3 ноября 2020 года № 76-2. Зарегистрировано Департаментом юстиции Жамбылской области 11 ноября 2020 года № 4802
  title:
    rus: О внесении изменений в решение Кордайского районного маслихата от 30 декабря 2019 года № 63-2 «О бюджете сельских округов Кордайского района на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Қордай ауданы ауылдық округтерінің бюджеттері туралы» Қордай аудандық мәслихатының 2019 жылғы 30 желтоқсандағы №63-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148345/rus
