act_code: '2066'
requisite: Решение Акима Жамбылской области от 24 февраля 1998 года № 61. Зарегистрировано Управлением юстиции Жамбылской области 13 апреля 1998 года № 19. Отменена государственная регистрация – Заключение Управлении юстиции Жамбылской области от 23 октября 2000 года об отмене государственной регистрации
title:
  rus: О создании тендерной комиссии
  kaz: О создании тендерной комиссии
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-02-24
approved_by:
- '158000000003'
version_date:
  rus: 1998-02-24
source:
  rus: https://zan.gov.kz/client/#!/doc/2066/rus/24.02.1998
