act_code: '173960'
requisite: Решение акима Темирбекского сельского округа Байзакского района Жамбылской области от 10 ноября 2022 года № 21. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 ноября 2022 года № 30568
title:
  rus: О переименовании некоторых составных частей села Шахан Темирбекского сельского округа Байзакского района
  kaz: Байзақ ауданы Темірбек ауылдық округінің Шахан ауылының кейбір құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-10
approved_by:
- '158003014002'
version_date:
  kaz: 2022-11-10
  rus: 2022-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/173960/kaz/10.11.2022
  rus: https://zan.gov.kz/client/#!/doc/173960/rus/10.11.2022
