act_code: '215663'
requisite: Решение Кордайского районного маслихата Жамбылской области от 13 октября 2025 года № 49-4
title:
  rus: Об утверждении Регламента Кордайского районного маслихата
  kaz: Қордай аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-13
approved_by:
- '158006000002'
version_date:
  kaz: 2025-10-13
  rus: 2025-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/215663/kaz/13.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215663/rus/13.10.2025
