act_code: '65905'
requisite: Решение маслихата Меркенского района Жамбылской области от 16 мая 2012 года № 5-6. Зарегистрировано Меркенским управлением юстиции 07 июня 2012 года за № 6-6-111. Утратило силу решением маслихата Меркенского района Жамбылской области от 20.05.2016 № 3-5
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам  государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим  в сельских населенных пунктах
  kaz: Ауылдық елдi мекендерде тұратын және жұмыс істейтiн мемлекеттiк денсаулық сақтау, әлеуметтiк қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшiн әлеуметтік  көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-16
approved_by:
- '158008000002'
version_date:
  kaz: 2013-04-04
  rus: 2013-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/65905/kaz/04.04.2013
  rus: https://zan.gov.kz/client/#!/doc/65905/rus/04.04.2013
caused_by:
  code: '72295'
  requisite: Решение маслихата Меркенского района Жамбылской области от 4 апреля 2013 года № 12-7. Зарегистрировано Департаментом юстиции Жамбылской области 26 апреля 2013 года № 1930. Утратило силу решением маслихата Меркенского района Жамбылской области от 20.05.2016 № 3-5
  title:
    rus: О внесении изменения в решение Меркенского районного маслихата от 16 мая 2012 года № 5-6 "О предоставлении социальной помощи на приобретение топлива  специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах"
    kaz: '"Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы" Меркі аудандық мәслихатының 2012 жылдың 16 мамырдағы № 5-6 шешіміне өзгеріс енгізу туралы.'
  link: https://zan.gov.kz/client/#!/doc/72295/rus
