act_code: '38296'
requisite: Жамбыл облысы Меркі ауданы Жамбыл ауылдық округі әкімінің 2008 жылғы 15 ақпандағы № 17 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2008 жылғы 11 наурызда № 6-6-52 тіркелді
title:
  rus: Жамбыл ауылдық округіндегі Жеңістің 30 жылдық көшесінің атын өзгерту туралы
  kaz: Жамбыл ауылдық округіндегі Жеңістің 30 жылдық көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-15
approved_by:
- '158008002002'
version_date:
  kaz: 2008-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/38296/kaz/15.02.2008
