act_code: '191864'
requisite: Решение Жуалынского районного маслихата Жамбылской области от 28 декабря 2023 года № 15-2
title:
  rus: О бюджетах сельских округов и села Бауыржан Момышулы Жуалынского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Жуалы ауданы Бауыржан Момышұлы ауылы және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '158005000002'
version_date:
  kaz: 2023-12-28
  rus: 2023-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/191864/kaz/28.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191864/rus/28.12.2023
