act_code: '43659'
requisite: Жамбыл облысы Байзақ ауданы әкімінің 2008 жылғы 22 желтоқсандағы № 17 шешімі. Жамбыл облысы Байзақ ауданының Әділет басқармасында 2009 жылғы 22 қаңтарда 6-2-87 нөмірімен тіркелді
title:
  rus: 2009 жылы Байзақ ауданының аумағында тұратын 1992 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
  kaz: 2009 жылы Байзақ ауданының аумағында тұратын 1992 жылы туылған еркек жынысты азаматтарды шақыру учаскесінде тіркеуді жүргізуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '158003000003'
version_date:
  kaz: 2008-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43659/kaz/22.12.2008
