act_code: '138238'
requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 30 декабря 2019 года № 52-4. Зарегистрировано Департаментом юстиции Жамбылской области 10 января 2020 года № 4490
title:
  rus: О бюджете сельских округов района Т.Рыскулова на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Т.Рысқұлов ауданы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '158007000002'
version_date:
  kaz: 2020-04-24
  rus: 2020-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/138238/kaz/24.04.2020
  rus: https://zan.gov.kz/client/#!/doc/138238/rus/24.04.2020
caused_by:
  code: '142286'
  requisite: Решение маслихата района Т. Рыскулова Жамбылской области от 24 апреля 2020 года № 54-4. Зарегистрировано Департаментом юстиции Жамбылской области 28 апреля 2020 года № 4590
  title:
    rus: О внесении изменений в решение маслихата района Т.Рыскулова от 30 декабря 2019 года №52-4 «О бюджете сельских округов района Т.Рыскулова на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Т.Рысқұлов ауданы ауылдық округтерінің бюджеттері туралы» Т.Рысқұлов аудандық мәслихатының 2019 жылғы 30 желтоқсандағы №52-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142286/rus
