act_code: '144483'
requisite: Решение Кордайского районного маслихата Жамбылской области от 25 июня 2020 года № 68-2. Зарегистрировано Департаментом юстиции Жамбылской области 3 июля 2020 года № 4669
title:
  rus: Об определении специализированных мест, порядка использования специализированных мест, норм их предельного наполнения, а также требований к материально-техническому и организационному обеспечению для организации и проведения мирных собраний в Кордайском районе
  kaz: Қордай ауданында бейбіт жиналыстарды ұйымдастыру және өткізуге арналған арнайы орындар, арнайы орындарды пайдалану тәртібі, олардың шекті толу нормалары, сондай-ақ материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '158006000002'
version_date:
  kaz: 2024-01-23
  rus: 2024-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/144483/kaz/23.01.2024
  rus: https://zan.gov.kz/client/#!/doc/144483/rus/23.01.2024
caused_by:
  code: '192945'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 23 января 2024 года № 18-3. Зарегистрировано Департаментом юстиции Жамбылской области от 29 января 2024 года № 5145
  title:
    rus: О внесении изменение в решение Кордайского районного маслихата от 25 июня 2020 года № 68-2 «Об определении специализированных мест, порядка использования специализированных мест, норм их предельного наполнения, а также требований к материально-техническому и организационному обеспечению для организации и проведения мирных собраний в Кордайском районе»
    kaz: «Қордай ауданында бейбіт жиналыстарды ұйымдастыру және өткізуге арналған арнайы орындар, арнайы орындарды пайдалану тәртібі, олардың шекті толу нормалары, сондай-ақ материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды айқындау туралы» Қордай аудандық мәслихатының 2020 жылғы 25 маусымдағы №68-2 шешiмiне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/192945/rus
