act_code: '129028'
requisite: Решение акима Кокталского сельского округа Таласского района Жамбылской области от 24 января 2019 года № 2. Зарегистрировано Департаментом юстиции Жамбылской области 31 января 2019 года № 4094
title:
  rus: О переименовании улицы Пионерская в селе Коктал Кокталского сельcкого округа
  kaz: Көктал ауылдық округінің Көктал ауылындағы Пионерская көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-24
approved_by:
- '158011014002'
version_date:
  kaz: 2019-01-24
  rus: 2019-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/129028/kaz/24.01.2019
  rus: https://zan.gov.kz/client/#!/doc/129028/rus/24.01.2019
