act_code: '180591'
requisite: Решение Мойынкумского районного маслихата Жамбылской области от 28 апреля 2023 года № 2-4
title:
  rus: О предоставлении в 2023 году мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Мойынкумского района
  kaz: Мойынқұм ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне 2023 жылы әлеуметтік қолдау шараларын көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-28
approved_by:
- '158009000002'
version_date:
  kaz: 2023-04-28
  rus: 2023-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/180591/kaz/28.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180591/rus/28.04.2023
