act_code: '18737'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2004 жылғы 2 ақпандағы № 3-6 қаулысы. Жамбыл облыстық әділет департаментінде 2004 жылғы 18 ақпанда 1205 нөмерімен тіркелді. Күші жойылды - Жамбыл облысы Талас аудандық мәслихатының 2008 жылғы 30 маусымдағы № 11-13 шешімімен
title:
  rus: Азаматтардың жекелеген санаттарына тұрғын үйді ұстауға және коммуналдық қызметтерге төлеу үшін тұрғын үй жәрдем ақысын тағайындау тәртібі туралы ережені бекіту туралы
  kaz: Азаматтардың жекелеген санаттарына тұрғын үйді ұстауға және коммуналдық қызметтерге төлеу үшін тұрғын үй жәрдем ақысын тағайындау тәртібі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-02-02
approved_by:
- '158011000002'
version_date:
  kaz: 2005-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/18737/kaz/18.04.2005
caused_by:
  code: '24062'
  requisite: Жамбыл облысы Талас аудандық мәслихатының 2005 жылғы 18 сәуірдегі № 13-4 шешімі. Жамбыл облысы Талас аудандық әділет басқармасында 2005 жылғы 6 мамырда 6-10-4 нөмірімен тіркелді
  title:
    rus: Аудандық мәслихаттың 2004 жылғы 2 ақпандағы № 3-6 "Азаматтардың жекелеген санаттарына тұрғын үйді ұстауға және коммуналдық қызметтерге төлеу үшін тұрғын үй жәрдемақысын тағайындау тәртібі туралы Ережені бекіту туралы" шешіміне толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2004 жылғы 2 ақпандағы № 3-6 "Азаматтардың жекелеген санаттарына тұрғын үйді ұстауға және коммуналдық қызметтерге төлеу үшін тұрғын үй жәрдемақысын тағайындау тәртібі туралы Ережені бекіту туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24062/rus
