act_code: '144241'
requisite: Решение Таразского городского маслихата Жамбылской области от 24 июня 2020 года № 59-6. Зарегистрировано Департаментом юстиции Жамбылской области 29 июня 2020 года № 4652
title:
  rus: Об определении специализированных мест для проведения собраний, митингов, демонстраций, шествий, пикетирований и правил их использования в городе Таразе
  kaz: Тараз қаласында жиналыстар, митингілер, демонстрациялар, шерулер мен пикеттерді өткізуге арналған  арнайы орындарды белгілеу және оларды пайдалану тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '158002000002'
version_date:
  kaz: 2024-01-26
  rus: 2024-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/144241/kaz/26.01.2024
  rus: https://zan.gov.kz/client/#!/doc/144241/rus/26.01.2024
caused_by:
  code: '193008'
  requisite: Решение Таразского городского маслихата Жамбылской области от 26 января 2024 года № 12-2. Зарегистрировано Департаментом юстиции Жамбылской области от 31 января 2024 года № 5147
  title:
    rus: О внесении изменений в решение маслихата города Тараза №59-6 от 24 июня 2020 года «Об определении специализированных мест для проведения собраний, митингов, демонстраций, шествий, пикетирований и правил их использования в городе Таразе»
    kaz: «Тараз қаласында жиналыстар, митингілер, демонстрациялар, шерулер мен пикеттерді өткізуге арналған арнайы орындарды белгілеу және оларды пайдалану тәртібі туралы» Тараз қалалық мәслихатының 2020 жылғы 24 маусымдағы №59-6 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193008/rus
