act_code: '118610'
requisite: Решение акима Гродиковского сельского округа Жамбылского района Жамбылской области от 12 января 2018 года № 3. Зарегистрировано Департаментом юстиции Жамбылской области 29 января 2018 года № 3690
title:
  rus: О переименовании улиц села Гродиково Гродиковского сельского округа
  kaz: Гродиково ауылдық округі Гродиково ауылындағы көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-12
approved_by:
- '158004006002'
version_date:
  kaz: 2018-01-12
  rus: 2018-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/118610/kaz/12.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118610/rus/12.01.2018
