act_code: '52578'
requisite: Жамбыл облысы Жамбыл ауданы Көлқайнар селолық округі әкімінің 2010 жылғы 4 мамырдағы № 02 шешімі. Жамбыл облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 19 мамырда 6-3-116 нөмірімен тіркелді
title:
  rus: Тастөбе ауылындағы Жеңістің 40 жылдығы көшесінің атауын өзгерту туралы
  kaz: Тастөбе ауылындағы Жеңістің 40 жылдығы көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-04
approved_by:
- '158004009002'
version_date:
  kaz: 2010-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/52578/kaz/04.05.2010
