act_code: '150789'
requisite: Решение Меркенского районного маслихата Жамбылской области от 24 декабря 2020 года № 79-3. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2020 года № 4871
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '158008000002'
version_date:
  kaz: 2021-12-20
  rus: 2021-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/150789/kaz/20.12.2021
  rus: https://zan.gov.kz/client/#!/doc/150789/rus/20.12.2021
caused_by:
  code: '162341'
  requisite: Решение Меркенского районного маслихата Жамбылской области от 20 декабря 2021 года № 18-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26114
  title:
    rus: О внесении изменений в решение Меркенского районного маслихата от 24 декабря 2020 года №79-3 «О районном бюджете на 2021-2023 годы»
    kaz: Меркі аудандық мәслихатының 2020 жылғы 24 желтоқсандағы №79-3 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162341/rus
