act_code: '84465'
requisite: Решение акима Жанакогамского сельского округа Шуского района Жамбылской области от 10 ноября 2014 года № 17. Зарегистрировано Департаментом юстиции Жамбылской области 21 ноября 2014 года № 2381
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением карантинного режима на территории Жанакогамского сельского округа
  kaz: Жаңақоғам селолық округінде карантин режимін енгізе отырып карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-10
approved_by:
- '158012012001'
version_date:
  kaz: 2014-11-10
  rus: 2014-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/84465/kaz/10.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84465/rus/10.11.2014
