act_code: '183880'
requisite: Решение акима Бирликского сельского округа Шуского района Жамбылской области от 12 июля 2023 года № 15
title:
  rus: О переименовании некоторых составных частей села Бирлик Бирликского сельского округа
  kaz: Бірлік ауылдық округінің Бірлік ауылындағы кейбір құрамдас бөліктерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-12
approved_by:
- '158012009002'
version_date:
  kaz: 2023-07-12
  rus: 2023-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/183880/kaz/12.07.2023
  rus: https://zan.gov.kz/client/#!/doc/183880/rus/12.07.2023
