act_code: '188825'
requisite: Решение Кордайского районного маслихата Жамбылской области от 22 ноября 2023 года № 13-5
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Кордайскому району
  kaz: Қордай ауданы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-22
approved_by:
- '158006000002'
version_date:
  kaz: 2023-11-22
  rus: 2023-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/188825/kaz/22.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188825/rus/22.11.2023
