act_code: '170256'
requisite: Решение Жамбылского областного маслихата от 29 июля 2022 года № 19-12. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 августа 2022 года № 28970. Утратило силу решением Жамбылского областного маслихата от 19 марта 2025 года № 22-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном предоставлении гарантированного объема бесплатной медицинской помощи, в том числе лекарственных средств, специализированных лечебных продуктов, медицинских изделий, отдельным категориям граждан Республики Казахстан, постоянно проживающим в Жамбылской области при амбулаторном лечении бесплатно
  kaz: Жамбыл облысында тұрақты тұратын Қазақстан Республикасы азаматтарының жекелеген санаттарына, амбулаториялық емделу кезінде қосымша тегін медициналық көмектің кепілдік берілген көлемін, оның ішінде  дәрілік заттарды, мамандандырылған емдік өнімдер мен медициналық бұйымдарды беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-29
approved_by:
- '158000000002'
version_date:
  kaz: 2024-09-25
  rus: 2024-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/170256/kaz/25.09.2024
  rus: https://zan.gov.kz/client/#!/doc/170256/rus/25.09.2024
caused_by:
  code: '201662'
  requisite: Решение Жамбылского областного маслихата от 25 сентября 2024 года № 17-6
  title:
    rus: О внесении изменений и дополнений в решение Жамбылского областного маслихата от 29 июля 2022 года № 19-12 «О дополнительном предоставлении гарантированного объема бесплатной медицинской помощи, в том числе лекарственных средств, специализированных лечебных продуктов, медицинских изделий, отдельным категориям граждан Республики Казахстан, постоянно проживающим в Жамбылской области при амбулаторном лечении бесплатно»
    kaz: «Жамбыл облысында тұрақты тұратын Қазақстан Республикасы азаматтарының жекелеген санаттарына, амбулаториялық емделу кезінде қосымша тегін медициналық көмектің кепілдік берілген көлемін, оның ішінде дәрілік заттарды, мамандандырылған емдік өнімдер мен медициналық бұйымдарды беру туралы» Жамбыл облыстық мәслихатының 2022 жылғы 29 шілдедегі № 19-12 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201662/rus
