act_code: '191477'
requisite: Решение Шуского районного маслихата Жамбылской области от 25 декабря 2023 года № 14-3
title:
  rus: О районном бюджете на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '158012000002'
version_date:
  kaz: 2024-12-09
  rus: 2024-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/191477/kaz/09.12.2024
  rus: https://zan.gov.kz/client/#!/doc/191477/rus/09.12.2024
caused_by:
  code: '208921'
  requisite: Решение Шуского районного маслихата Жамбылской области от 9 декабря 2024 года № 32-2
  title:
    rus: О внесении изменений в решение Шуского районного маслихата от 25 декабря 2023 года № 14-3 «О районном бюджете на 2024-2026 годы»
    kaz: «2024-2026 жылдарға арналған аудандық бюджет туралы» Шу аудандық мәслихатының 2023 жылғы 25 желтоқсандағы № 14-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208921/rus
