act_code: '129217'
requisite: Решение Таразского городского маслихата Жамбылской области от 15 февраля 2019 года № 42-7. Зарегистрировано Департаментом юстиции Жамбылской области 19 февраля 2019 года № 4107. Утратило силу решением Таразского городского маслихата Жамбылской области от 26 марта 2021 года № 3-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов и тарифов на сбор, вывоз,утилизацию твердых бытовых отходов по городу Тараз
  kaz: Тараз қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормалары және тұрмыстық қатты қалдықтарды жинауға, әкетуге, кәдеге жаратуға,арналған тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-15
approved_by:
- '158002000002'
version_date:
  kaz: 2019-02-15
  rus: 2019-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/129217/kaz/15.02.2019
  rus: https://zan.gov.kz/client/#!/doc/129217/rus/15.02.2019
