act_code: '50309'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 27-3 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 18 қаңтарда 6-10-92 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158011000002'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50309/kaz/25.12.2009
