act_code: '50309'
requisite: Жамбыл облысы Талас аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 27-3 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 18 қаңтарда 6-10-92 нөмірімен тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '158011000002'
version_date:
  kaz: 2010-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/50309/kaz/15.04.2010
caused_by:
  code: '52198'
  requisite: Жамбыл облысы Талас аудандық мәслихатының 2010 жылғы 15 сәуірдегі № 30-2 шешімі. Жамбыл облысы Талас ауданының Әділет басқармасында 2010 жылғы 27 сәуірде 6-10-97 нөмірімен тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Жамбыл облыстық Әділет департаментінің 2013 жылғы 11 наурыздағы № 2-2-17/388 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Талас аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 27-3 шешіміне өзгерістер мен толықтыру енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Талас аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 27-3 шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/52198/rus
