act_code: '187866'
requisite: Решение Таласского районного маслихата Жамбылской области от 2 ноября 2023 года № 9-6
title:
  rus: Об установлении стимулирующих надбавок к должностным окладам работников организаций, финансируемых из местного бюджета
  kaz: Жергілікті бюджеттен қаржыландырылатын ұйымдар жұмыскерлерінің лауазымдық айлықақыларына ынталандыру үстемеақы белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-02
approved_by:
- '158011000002'
version_date:
  kaz: 2023-11-02
  rus: 2023-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/187866/kaz/02.11.2023
  rus: https://zan.gov.kz/client/#!/doc/187866/rus/02.11.2023
