act_code: '43287'
requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 12-4 шешімі. Жамбыл облысы Жуалы ауданының Әділет басқармасында 2009 жылғы 12 қаңтарда 6-4-67 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Жуалы аудандық мәслихатының 2010 жылғы 4 ақпандағы № 24-5 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '158005000002'
version_date:
  kaz: 2009-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/43287/kaz/06.05.2009
caused_by:
  code: '45716'
  requisite: Жамбыл облысы Жуалы аудандық мәслихатының 2009 жылғы 6 мамырдағы № 16-3 шешімі. Жамбыл облысы Жуалы ауданының әділет басқармасында 2009 жылғы 8 мамырда 6-4-71 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Жуалы аудандық мәслихатының 2010 жылғы 4 ақпандағы № 24-5 шешімімен
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Жуалы аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 12-4 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Жуалы аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 12-4 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45716/rus
