act_code: '150796'
requisite: Решение Кордайского районного маслихата Жамбылской области от 25 декабря 2020 года № 80-5. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2020 года № 4872. Утратило силу решением Кордайского районного маслихата Жамбылской области от 20 октября 2023 года № 10-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Кордайскому району
  kaz: Қордай ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-25
approved_by:
- '158006000002'
version_date:
  kaz: 2021-12-15
  rus: 2021-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150796/kaz/15.12.2021
  rus: https://zan.gov.kz/client/#!/doc/150796/rus/15.12.2021
caused_by:
  code: '162336'
  requisite: Решение Кордайского районного маслихата Жамбылской области от 15 декабря 2021 года № 17-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26073. Утратило силу решением Кордайского районного маслихата Жамбылской области от 20 октября 2023 года № 10-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Кордайского районного маслихата от 25 декабря 2020 года №80-5 «Об утверждении Правил оказания социальной помощи, установления  размеров и определения перечня отдельных категорий нуждающихся граждан по Кордайскому району»
    kaz: Қордай аудандық мәслихатының 2020 жылғы 25 желтоқсандағы №80-5 «Қордай ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162336/rus
