act_code: '92364'
requisite: Решение Жамбылского областного маслихата от 25 июня 2015 года № 38-8. Зарегистрировано Департаментом юстиции Жамбылской области 29 июля 2015 года № 2707. Утратило силу решением Жамбылского областного маслихата от 21.06.2019 № 36-7
title:
  rus: Об утверждении правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в Байзакском районе
  kaz: Байзақ ауданында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер  мен мысықтарды аулау және  жою Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-06-25
approved_by:
- '158000000002'
version_date:
  kaz: 2015-06-25
  rus: 2015-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/92364/kaz/25.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92364/rus/25.06.2015
