act_code: '37222'
requisite: Жамбыл облысы Меркі ауданы Ойтал кенттік округі әкімінің 2008 жылғы 9 қаңтардағы № 5 шешімі. Жамбыл облысы Меркі ауданының Әділет басқармасында 2008 жылғы 30 қаңтарда 6-6-50 нөмірімен тіркелді
title:
  rus: Ойтал кенттік округіндегі Крылов көшесінің атын өзгерту туралы
  kaz: Ойтал кенттік округіндегі Крылов көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-09
approved_by:
- '158008004002'
version_date:
  kaz: 2008-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/37222/kaz/09.01.2008
