act_code: '85427'
requisite: Решение маслихата Т.Рыскулова Жамбылской области от 24 декабря 2014 года № 30-5. Зарегистрировано Департаментом юстиции Жамбылской области 29 декабря 2014 года № 2457
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '158007000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/85427/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85427/rus/24.12.2014
