act_code: '38316'
requisite: Решение Жамбылского областного маслихата от 8 февраля 2008 года № 4-16. Зарегистрировано Департаментом юстиции Жамбылской области 11 марта 2008 года за номером 1676. Утратило силу решением Жамбылского областного маслихата от 17.07.2019 № 37-7
title:
  rus: Об утверждении ставок платы за пользование водными ресурсами из поверхностных источников Жамбылской области
  kaz: Жамбыл облысында жер үсті көздеріндегі су ресуртарын пайдаланғаны үшін төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-08
approved_by:
- '158000000002'
version_date:
  kaz: 2008-02-08
  rus: 2008-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/38316/kaz/08.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38316/rus/08.02.2008
