act_code: '204972'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 25 декабря 2024 года № 33-2
title:
  rus: «О районном бюджете на 2025-2027 годы»
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '158004000002'
version_date:
  kaz: 2025-08-15
  rus: 2025-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/204972/kaz/15.08.2025
  rus: https://zan.gov.kz/client/#!/doc/204972/rus/15.08.2025
caused_by:
  code: '213357'
  requisite: Решение Жамбылского районного маслихата Жамбылской области от 15 августа 2025 года № 40-2
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 25 декабря 2024 года № 33-2 «О районном бюджете на 2025-2027 годы»
    kaz: Жамбыл аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 33-2 «2025-2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213357/rus
