act_code: '204972'
requisite: Решение Жамбылского районного маслихата Жамбылской области от 25 декабря 2024 года № 33-2
title:
  rus: «О районном бюджете на 2025-2027 годы»
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '158004000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/204972/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204972/rus/25.12.2024
