act_code: '50053'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 30-5 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2010 жылғы 19 қаңтарда 6-9-85 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2011 жылғы 8 маусымдағы № 51-11 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '158010000002'
version_date:
  kaz: 2010-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/50053/kaz/13.08.2010
caused_by:
  code: '54062'
  requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2010 жылғы 13 тамыздағы № 41-3 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2010 жылғы 17 тамызда 6-9-98 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2011 жылғы 8 маусымдағы № 51-11 шешімімен
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Сарысу аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 30-5 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Сарысу аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 30-5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54062/rus
