act_code: '50053'
requisite: Жамбыл облысы Сарысу аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 30-5 шешімі. Жамбыл облысы Сарысу ауданының Әділет басқармасында 2010 жылғы 19 қаңтарда 6-9-85 нөмірімен тіркелді. Күші жойылды - Жамбыл облысы Сарысу аудандық мәслихатының 2011 жылғы 8 маусымдағы № 51-11 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '158010000002'
version_date:
  kaz: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/50053/kaz/24.12.2009
