act_code: '20239'
requisite: Решение Таразского городского маслихата Жамбылской области № 4-6 от 6 мая 2004 года. Зарегистрировано Департаментом юстиции Жамбылской области 10 июня 2004 года за № 1372. Отменено решением Таразского городского маслихата Жамбылской области от 25 июня 2010 года № 30-8
title:
  rus: Об утверждении Обязательных правил, действующих на территории города Тараза, за нарушение которых предусматривается административная ответственность
  kaz: Тараз қаласы аумағында тәртіп бұзғаны үшін әкімшілік жауапкершілікке тарту жөніндегі, қолданылатын міндетті Ережелерді бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-05-05
approved_by:
- '158002000002'
version_date:
  kaz: 2005-10-26
  rus: 2005-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/20239/kaz/26.10.2005
  rus: https://zan.gov.kz/client/#!/doc/20239/rus/26.10.2005
caused_by:
  code: '25649'
  requisite: Решение Таразского городского маслихата Жамбылской области от 26 октября 2005 года № 16-3. Зарегистрировано Управлением юстиции г.Тараз Жамбылской области 27 октября 2005 года за № 6-1-14. Отменено решением Таразского городского маслихата Жамбылской области от 25 июня 2010 года № 30-8
  title:
    rus: О внесении дополнений в решение Таразского городского маслихата N 4-6 от 6 мая 2004 года "Об утверждении Обязательных правил, действующих на территории города Тараза, за нарушение которых предусматривается административная ответственность"
    kaz: Тараз қалалық мәслихатының 2004 жылғы 6 мамырдағы N 4-6 "Тараз қаласы аумағында тәртіп бұзғаны үшін әкімшілік жауапкершілікке тарту жөніндегі, қолданылатын міндетті Ережелерді бекіту туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/25649/rus
